apache/doris-website

index.html
versions.json

[Enhancement] documents rebuild with Vuepress

[Enhancement] documents rebuild with Vuepress

---

versions.json

add version option for branch-0.13

add version option for branch-0.13

---

community/feedback.md
community/how-to-contribute/contributor-guide.md
community/how-to-contribute/how-to-contribute.md
community/how-to-contribute/pull-request.md
community/subscribe-mail-list.md

[typo]fix incubator word

---

docs/admin-manual/config/be-config.md

fix default value and type error

[typo](doc)fix be config buffer_pool_limit default value

---

docs/ecosystem/mysql-to-doris.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/mysql-to-doris.md
sidebars.json

[doc](mysql2doris)Add mysql to doris documentation

---

docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-TABLE.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-TABLE.md

create table missing string type

[doc](fix) Add string to create table column_type 

---

docs/data-operate/import/import-scenes/jdbc-load.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-scenes/jdbc-load.md

Change the wrong port in JDBC demo

Change error port

---

.github/workflows/manual-deploy-website.yml
.gitmodules

[CDN] Use aliyun-oss-website-action in our repo

---

.github/workflows/cron-deploy-website.yml
.github/workflows/manual-deploy.yml
src/constant/download.data.ts
src/pages/download/index.tsx

- [[feature] use mirror url while language was zh_CN](https://github.com/apache/doris-website/commit/b5467cd82c3af2cb013e7c568c5e09ad6f84d502)

[feature] use mirror url while language was zh_CN

---

docs/sql-manual/sql-reference/Data-Manipulation-Statements/Load/STREAM-LOAD.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-reference/Data-Manipulation-Statements/Load/STREAM-LOAD.md

filter out the first row of your csv file

[fix](doc) stream load 'format' parameter description

---

docs/data-operate/import/import-way/load-json-format.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/load-json-format.md

Specify JSON root document when adding JSON import, and add JSON file size limit parameter prompt

add some json format load doc

---

.gitignore
community/developer-guide/fe-idea-dev.md
i18n/zh-CN/docusaurus-plugin-content-docs-community/current/developer-guide/fe-idea-dev.md

Hi @jackwener  Can you review this PR,  thx~
It contains `zh-cn` and `en`

[fix](docs) Added FE dev env setting guide for mac m1

---

docs/sql-manual/sql-reference/Data-Manipulation-Statements/Manipulation/DELETE.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-reference/Data-Manipulation-Statements/Manipulation/DELETE.md

Remove the ambiguity in the description of the operating instructions document

[fix](doc) remove the ambiguity in the description of the operating instructions document

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/get-starting/get-starting.md

[typo] Correct Chinese text error

---

docs/admin-manual/cluster-management/upgrade.md
docs/admin-manual/maint-monitor/metadata-operation.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/cluster-management/upgrade.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/maint-monitor/metadata-operation.md

fix_link_err

---

docs/ecosystem/udf/native-user-defined-function.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/udf/native-user-defined-function.md

vectorization needs to be turned off to use native udf.

[typo](docs) vectorization needs to be turned off to use native udf

---

docs/data-operate/import/import-way/spark-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/spark-load-manual.md

Changing the Jump Address of BrokerLoad in SparkLoad

[typo](docs)Changing the Jump Address of BrokerLoad in SparkLoad

---

docs/data-operate/import/import-way/broker-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/broker-load-manual.md

Changing the Jump Address of SparkLoad in BrokerLoad

[typo](docs) Changing the Jump Address of SparkLoad in BrokerLoad

---

docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-TABLE-AS-SELECT.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-TABLE-AS-SELECT.md

Add some description

---

docs/get-starting/get-starting.md
docs/install/install-deploy.md
docs/sql-manual/sql-reference/Data-Definition-Statements/Alter/ALTER-TABLE-PARTITION.md
docs/sql-manual/sql-reference/Data-Manipulation-Statements/Load/BROKER-LOAD.md

doc_fix_404_221008

---

docs/data-operate/import/import-scenes/kafka-load.md

Fix jump link 404 in kafka load.md

[typo](docs)  Fix jump link 404

---

versioned_docs/version-0.15/best-practices/star-schema-benchmark.md
versioned_docs/version-0.15/extending-doris/logstash.md
versioned_docs/version-0.15/extending-doris/udf/user-defined-function.md
versioned_docs/version-0.15/installing/install-deploy.md

404 repair

---

docs/admin-manual/data-admin/delete-recover.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/data-admin/delete-recover.md

Fix the jump link 404 in delete recover.md

[typo](docs)Fix the jump link 404 in delete recover.md

---

docs/admin-manual/http-actions/fe/table-schema-action.md

Fix FE Configuration Jump Link 404

[typo](docs)Fix FE Configuration Jump Link 404

---

docs/get-starting/get-starting.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/get-starting/get-starting.md

[typo](doc) fix doc table name

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/get-starting/get-starting.md

pr in doris repo：https://github.com/apache/doris/pull/14001
fix get-starting doc

[typo](doc) fix get-starting doc

---

docs/data-table/data-model.md
docs/data-table/data-partition.md
docs/get-starting/get-starting.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-table/data-model.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-table/data-partition.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/get-starting/get-starting.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.15/getting-started/data-model-rollup.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.15/getting-started/data-partition.md
versioned_docs/version-0.15/getting-started/data-model-rollup.md
versioned_docs/version-0.15/getting-started/data-partition.md

[Doc] fix spelling errors

---

sidebars.json

- [enhance] resort release note docs

[enhance] resort release note docs

---

.gitmodules
local_build_docs.sh

Deploy to OSS Error, use aliyun-oss-website-action temporarily

[OSS] use aliyun-oss-website-action temporarily

---

docusaurus.config.js
i18n/zh-CN/code.json
src/pages/index.tsx

(feature) add doris summit

---

docusaurus.config.js
i18n/zh-CN/code.json
src/pages/index.tsx

- [(fix) delete unused doris folder](https://github.com/apache/doris-website/commit/7f116014991811685ef29e156ac43a15e24dc549)

(fix) delete unused doris folder

---

.github/workflows/cron-generate-pdf.yml

- [PDF] update generate pdf action

[PDF] update generate pdf action

---

.github/workflows/cron-deploy-website.yml
.github/workflows/manual-deploy-website.yml

Update to actions/setup-node@v3

Use Node.js 16

---

.github/workflows/cron-deploy-website.yml
.github/workflows/manual-deploy-website.yml

Reverts apache/doris-website#226

Revert "Generate PDF"

---

src/constant/download.data.ts

checksums, detached signatures link mast point to downloads.apache.org

Update checksums, detached signatures link

---

config/custom-docusaurus-plugin.js
config/ssrTemplate.js
docusaurus.config.js
src/pages/download/index.tsx
src/theme/SearchBar/fetchIndexes.js

```cdn-tencent.selectdb.com``` met some problems, and GFW may ban some IP addresses (outside of China).
use ```cdnd.selectdb.com``` instead.
- (app) use cdnd.selectdb.com

(app) use cdnd.selectdb.com

---

docusaurus.config.js
package.json

- (search) fix search-index error
It seems the new version makes the search unavailable. 
reference issue: https://github.com/easyops-cn/docusaurus-search-local/issues/320

(search) fix search-index error

---

docusaurus.config.js
src/components/PageBanner/styles.scss
src/scss/components/sidebar.scss

search result layer below the markdown code block makes an error

(fix) fix styles error

---

src/pages/learning/index.tsx

[fix] doc index link

---

.github/workflows/cron-deploy-website.yml
.github/workflows/cron-generate-pdf.yml
.github/workflows/manual-deploy-website.yml

- (fix) delete download-scripts

(fix) delete download-scripts

---

i18n/zh-CN/code.json
src/constant/download.data.ts
src/pages/download/index.tsx
src/pages/index.tsx

- (feature) add release doris 2.0.0beta

(feature) add release doris 2.0-beta

---

src/pages/download/index.tsx
src/pages/index.tsx

(fix) use path 2.0-beta

---

i18n/zh-CN/code.json
src/constant/download.data.ts
src/pages/index.tsx

- (fix) fix 2.0-beta release date error

(fix) fix 2.0-beta release date error

---

src/scss/_variables.scss

(fix) fix font missing bug

---

i18n/zh-CN/code.json
src/constant/download.data.ts
src/pages/index.tsx

(feature) Release 1.2.6

---

docusaurus.config.js
i18n/zh-CN/code.json
src/constant/download.data.ts
src/pages/download/index.tsx
src/pages/index.tsx

- (fix) fix release note expression

(fix) fix release note expression

---

docusaurus.config.js
src/components/PageBanner/styles.scss
src/pages/index.tsx

- [feature](community) add join-community & fix spell error

[feature](community) add join-community & fix spell error

---

docusaurus.config.js
package.json

Add docs redirects
Old links redirect to new links to avoid user bookmark or search engine results broken

(feat) add docs redirects

---

.gitignore
src/constant/download.data.ts

- [fix] fix 2.0.0 release date error

[fix] fix 2.0.0 release date error

---

docusaurus.config.js
prepare_local_dev.sh
src/scss/_variables.scss

(feat) use theme dracula

---

src/constant/download.data.ts
src/constant/newsletter.data.ts
src/pages/download/index.tsx

- (release) release 2.0.1 & 1.2.7

(release) release 2.0.1 & 1.2.7

---

docusaurus.config.js

(feat) add summit banner

---

docusaurus.config.js

- [(feat) update summit banner](https://github.com/apache/doris-website/commit/97986e96b0b5b9e6eff7f2d52d40d1d485711222)

(feat) update summit banner url

---

src/pages/download/index.tsx

- (fix) fix zh_CN text in code

(fix) fix zh_CN text in code

---

docusaurus.config.js

- (feat) use announcementBar id doris-summit2023

(feat) use announcementBar id doris-summit2023

---

docusaurus.config.js
src/theme/DocSidebar/Desktop/index.tsx

(feat) nav docs go to 2.0 by default

---

docusaurus.config.js

- (feat) announcement-bar rollback to GitHub star

(feat) announcement-bar rollback to github star

---

docusaurus.config.js

[fix] fix get-starting/quick-start error

---

src/theme/Navbar/Content/index.tsx

[feat] update star display

---

src/pages/index.tsx

[index] update the link to docs on index page

Update the link to docs on index page

---

src/theme/Navbar/Content/index.tsx

- (fix) fix github button missed link

(fix) fix github button missed link

---

src/constant/newsletter.data.ts

Update Newsletter about Summit Blog on Home page

[blogs] Update Newsletter about Summit Blog on Home page 

---

src/constant/newsletter.data.ts

Update newsletters for CIGNA&CMB Blog

[blog] Update newsletter

---

src/pages/index.tsx
src/theme/Footer/index.tsx

[docs] Update Slack link on home page and footer

---

i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/install/source-install/compilation-with-ldb-toolchain.md
versioned_docs/version-1.2/install/source-install/compilation-with-ldb-toolchain.md

update LDB compose JDK8 download url

---

src/hooks/use-animation-frame.ts
src/pages/index.tsx

(fix) fix first-page tabs animation bug

---

docusaurus.config.js
src/components/PageBanner/index.tsx
src/components/link-arrow/index.tsx
src/components/recent-blogs/index.tsx
src/components/recent-blogs/recent-blogs.data.ts
src/constant/core-capabilities.data.tsx
src/hooks/use-animation-frame.ts
src/pages/download/index.tsx
src/pages/index.scss
src/pages/index.tsx
src/pages/users/index.tsx
src/pages/users/user-item.tsx
src/scss/components/breadcrumbs.scss
src/scss/components/markdown.scss
src/scss/components/navbar.scss
src/scss/components/search.scss
src/theme/BlogListItem/HeadItem/index.tsx
src/theme/BlogPostItem/index.tsx
src/theme/BlogPostPage/Metadata/index.tsx
src/theme/BlogPostPage/index.tsx
src/theme/DocSidebarItem/Category/style.scss
src/theme/Footer/index.tsx
src/theme/Footer/styles.scss
src/theme/SearchBar/SearchBar.jsx
src/theme/SearchBar/SearchBar.module.css
static/js/custom-script.js
versioned_sidebars/version-2.0-sidebars.json

(feat) update styles & fix bugs

---

src/components/PageColumn/styles.scss
src/components/PageHeader/index.tsx
src/components/PageHeader/style.scss
src/components/get-started/get-started.tsx
src/theme/BlogLayout/index.tsx
src/theme/BlogPostItem/index.tsx
src/theme/Footer/index.tsx

(feat) update mobile styles

---

.github/workflows/cron-deploy-website.yml
cspell.json
package.json
src/components/Icons/arrow.tsx
src/components/Icons/external-link-arrow-icon.tsx
src/components/PageBanner/index.tsx
src/components/ReadMore/index.tsx
src/components/download-form/download-form-all-release.tsx
src/components/form-select/form-select.tsx
src/components/link-arrow/index.tsx
src/constant/download.data.ts
src/constant/various-analytics.data.tsx
src/pages/_download/index.tsx
src/pages/download/index.scss
src/pages/download/index.tsx
src/pages/users/index.tsx
src/theme/SearchBar/SearchBar.module.css
src/theme/SearchBar/icons.js
static/images/cpu-flame-demo.svg
static/images/cpu-pprof-demo.svg
static/images/table_connectors.svg
versioned_sidebars/version-1.2-sidebars.json
versioned_sidebars/version-2.0-sidebars.json

- [feat](download) update download page

[feat](download) update download page

---

docusaurus.config.js
src/pages/index.tsx

- [feat] update apache security

[feat] update apache security

---

src/theme/Navbar/Content/index.tsx

- [fix] fix get github star api error

[fix] fix get github star api error

---

src/constant/download.data.ts
src/pages/download/index.tsx

[feat] release apache doris 2.0.5

[feat] release apache doris 2.0.5

---

docusaurus.config.js
package.json

[feat] add analytic matomo

---

src/constant/download.data.ts
src/pages/download/index.tsx

- [feat] add kafka-doris-connector

[feat] add kafka-doris-connector

---

docs/query-acceleration/hint/joinHint.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/hint/joinHint.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-acceleration/hint/joinHint.md
versioned_docs/version-2.1/query-acceleration/hint/joinHint.md

multi leading is supported in branch 2.1 and master

[docs](Nereids) update join hint support multi leading in 2.1 and master

---

docs/sql-manual/sql-reference/Data-Manipulation-Statements/Manipulation/EXPORT.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-reference/Data-Manipulation-Statements/Manipulation/EXPORT.md

https://github.com/apache/doris/pull/31290

[Fix](Docs) fix Export Docs

---

docusaurus.config.js
src/theme/TOC/index.tsx

- [fix] update join discussion url

[fix] update join discussion url

---

docs/admin-manual/config/be-config.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/config/be-config.md

remove some not used conf in be
https://github.com/apache/doris/pull/31607

[doc](config) remove some not used conf in be

---

docs/sql-manual/sql-reference/Data-Manipulation-Statements/Manipulation/EXPORT.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-reference/Data-Manipulation-Statements/Manipulation/EXPORT.md

[# 32830](https://github.com/apache/doris/pull/32830)

[fix](Export) fix description of  `data_consitency`

---

docs/sql-manual/sql-functions/string-functions/int-to-uuid.md
docs/sql-manual/sql-functions/string-functions/uuid-to-int.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/string-functions/int-to-uuid.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/string-functions/uuid-to-int.md

master pr: https://github.com/apache/doris/pull/33005

[Doc](function) Support uuid_to_int and int_to_uuid functions

---

docs/admin-manual/maint-monitor/metadata-operation.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/maint-monitor/metadata-operation.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/admin-manual/maint-monitor/metadata-operation.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/maint-monitor/metadata-operation.md
versioned_docs/version-2.0/admin-manual/maint-monitor/metadata-operation.md
versioned_docs/version-2.1/admin-manual/maint-monitor/metadata-operation.md

Add a --daemon, if you don't, there's a bug in the foreground startup.

fix the startup of fe

---

.github/workflows/cron-deploy-website.yml
.github/workflows/manual-deploy-website.yml

see: https://github.com/peaceiris/actions-gh-pages

[opt] enable force_orphan to avoid asf-site too large

---

.github/workflows/approve-check.yml
tools/check_review.py
tools/maintainers.json

Core modules require maintainer review
discuss link:https://lists.apache.org/thread/3dxvr1ow2pgx7znnjwdh2ymsfs97bktf
Configuration File Documentation
This configuration file is used to set maintainers for each path in a code repository. Only maintainers of a path can approve code changes under that path before they can be merged.
Configuration File Format
The configuration file is a JSON file that contains a paths array. Each element in the array represents a path and its list of maintainers.
Example
```
{
"paths": [
{
"path": "docs/*",
"maintainers": [
"luzhijing",
"morningman"
]
}
]
}
```
Configurationの
paths: An array of objects that represent paths and their maintainers.
path: A string that represents the path that maintainers need to be set for. You can use the wildcard * to match …

Add maintainer check

---

docs/advanced/partition/auto-partition.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/advanced/partition/auto-partition.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/advanced/partition/auto-partition.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-table/data-partition.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-reference/Data-Manipulation-Statements/Manipulation/INSERT-OVERWRITE.md
versioned_docs/version-2.1/advanced/partition/auto-partition.md
versioned_docs/version-2.1/data-table/data-partition.md
versioned_docs/version-2.1/sql-manual/sql-reference/Data-Manipulation-Statements/Manipulation/INSERT-OVERWRITE.md

NULL partition and AUTO DETECT OVERWRITE supported from 2.1.3

[Doc](version) Fix some functions version

---

docs/install/source-install/compilation-arm.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/install/source-install/compilation-arm.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/install/source-install/compilation-arm.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/install/source-install/compilation-arm.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/source-install/compilation-arm.md

Fix Maven download link failure, related to https://github.com/apache/doris/issues/32944

[doc](fix)Fix Maven download link failure

---

docs/sql-manual/sql-functions/string-functions/quote.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/string-functions/quote.md
sidebars.json

related to https://github.com/apache/doris/pull/33055

[doc] function quote update

---

docs/sql-manual/sql-functions/aggregate-functions/foreach.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/foreach.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/aggregate-functions/foreach.md
sidebars.json
versioned_docs/version-2.1/sql-manual/sql-functions/aggregate-functions/foreach.md
versioned_sidebars/version-2.1-sidebars.json

master pr https://github.com/apache/doris/pull/31913

[Doc](function) Support agg foreach 

---

docs/sql-manual/sql-functions/numeric-functions/xor.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/numeric-functions/xor.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/numeric-functions/xor.md
sidebars.json
versioned_docs/version-2.1/sql-manual/sql-functions/numeric-functions/xor.md
versioned_sidebars/version-2.1-sidebars.json

https://github.com/apache/doris/pull/33634

[doc](pred) Support xor function

---

docs/sql-manual/sql-functions/aggregate-functions/group-array-intersect.md
docs/sql-manual/sql-functions/hll-functions/hll-from-base64.md
docs/sql-manual/sql-functions/hll-functions/hll-to-base64.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/group-array-intersect.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/hll-functions/hll-from-base64.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/hll-functions/hll-to-base64.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/aggregate-functions/group-array-intersect.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/hll-functions/hll-from-base64.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/hll-functions/hll-to-base64.md
sidebars.json
versioned_docs/version-2.1/sql-manual/sql-functions/aggregate-functions/group-array-intersect.md
versioned_docs/version-2.1/sql-manual/sql-functions/hll-functions/hll-from-base64.md
versioned_docs/version-2.1/sql-manual/sql-functions/hll-functions/hll-to-base64.md
versioned_sidebars/version-2.1-sidebars.json

- hll_from_base64, hll_to_base64:
master pr: https://github.com/apache/doris/pull/32089
- group_array_intersect:
master pr: https://github.com/apache/doris/pull/33265

[Doc](function) Support hll_from_base64, hll_to_base64, group_array_intersect functions

---

docs/advanced/partition/auto-partition.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/advanced/partition/auto-partition.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/advanced/partition/auto-partition.md
versioned_docs/version-2.1/advanced/partition/auto-partition.md

master pr: https://github.com/apache/doris/pull/33736

[Doc](auto-partition) Forbid use Auto and Dynamic partition at the same time

---

docs/ecosystem/hive-hll-udf.md
docs/sql-manual/sql-functions/hll-functions/hll-from-base64.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/hive-hll-udf.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/hll-functions/hll-from-base64.md
sidebars.json

master pr: https://github.com/apache/doris/pull/33896

[Doc](function) Support Hive HLL UDFs

---

docs/install/source-install/compilation-mac.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/install/source-install/compilation-mac.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/install/source-install/compilation-mac.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/source-install/compilation-mac.md
versioned_docs/version-2.0/install/source-install/compilation-mac.md
versioned_docs/version-2.1/install/source-install/compilation-mac.md

Fix configuration append problem

[docs](fix) Fix Compilation on MacOS

---

docs/separation-of-storage-and-compute/install-fdb.md
docs/separation-of-storage-and-compute/storage-vault.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/separation-of-storage-and-compute/deployment.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/separation-of-storage-and-compute/install-fdb.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/separation-of-storage-and-compute/meta-service-resource-http-api.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/separation-of-storage-and-compute/storage-vault.md
sidebars.json

* Add vault description and update deployment
* Remove clear FDB kv in deployment
* Add some id/name instruction for meta-service API

[docs](doris-cloud) Add storage vault and update deployment

---

community/developer-guide/pipeline-tracing.md
docs/lakehouse/datalake-analytics/iceberg.md
docs/lakehouse/datalake-analytics/paimon.md
i18n/zh-CN/docusaurus-plugin-content-docs-community/current/developer-guide/pipeline-tracing.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/datalake-analytics/iceberg.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/datalake-analytics/paimon.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/lakehouse/datalake/paimon.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/datalake-analytics/iceberg.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/datalake-analytics/paimon.md
versioned_docs/version-2.0/lakehouse/datalake/paimon.md
versioned_docs/version-2.1/lakehouse/datalake-analytics/iceberg.md
versioned_docs/version-2.1/lakehouse/datalake-analytics/paimon.md

map "Row" of Paimon to "Struct" of Doris and fix some error

[doc](fix)map "Row" of Paimon to "Struct" of Doris

---

docs/sql-manual/sql-functions/table-functions/s3.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-functions/s3.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/table-functions/s3.md
versioned_docs/version-2.1/sql-manual/sql-functions/table-functions/s3.md

[Doc] (s3-tvf) Update s3 tvf docs after https://github.com/apache/doris/pull/33858.

[Doc](s3-tvf) Update s3 tvf docs.

---

docs/admin-manual/resource-admin/workload-group.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/resource-admin/workload-group.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/resource-admin/workload-group.md
versioned_docs/version-2.1/admin-manual/resource-admin/workload-group.md

Correcting spelling mistakes  chonw--> chown

Correcting spelling mistakes

---

docs/lakehouse/database/jdbc.md
docs/sql-manual/sql-functions/table-functions/query.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/database/jdbc.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-functions/query.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/database/jdbc.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/table-functions/query.md
sidebars.json
versioned_docs/version-2.1/lakehouse/database/jdbc.md
versioned_docs/version-2.1/sql-manual/sql-functions/table-functions/query.md
versioned_sidebars/version-2.1-sidebars.json

docs from https://github.com/apache/doris/pull/34516

[docs](function) add query tvf docs

---

docs/admin-manual/resource-admin/workload-system-table.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/resource-admin/workload-system-table.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/resource-admin/workload-system-table.md
sidebars.json
versioned_docs/version-2.1/admin-manual/resource-admin/workload-system-table.md
versioned_sidebars/version-2.1-sidebars.json

[docs]Add workload system table

---

docs/sql-manual/sql-statements/Database-Administration-Statements/ADMIN-SET-CONFIG.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Database-Administration-Statements/ADMIN-SET-CONFIG.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-reference/Database-Administration-Statements/ADMIN-SET-CONFIG.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/Database-Administration-Statements/ADMIN-SET-CONFIG.md
versioned_docs/version-2.0/sql-manual/sql-reference/Database-Administration-Statements/ADMIN-SET-CONFIG.md
versioned_docs/version-2.1/sql-manual/sql-statements/Database-Administration-Statements/ADMIN-SET-CONFIG.md

Implementation: https://github.com/apache/doris/pull/34685

[docs](set) enable admin_set_frontend_config can apply to all fe

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/data-partition.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/data-partition.md

master pr: https://github.com/apache/doris/pull/33712

[Doc](partition) Refactor dynamic partition docs

---

docs/admin-manual/resource-admin/workload-group.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/resource-admin/workload-group.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/resource-admin/workload-group.md
versioned_docs/version-2.1/admin-manual/resource-admin/workload-group.md

1 Fix dead link for workload group
2 add more note for workload group

[docs] Fix dead link for workload group

---

docs/data-operate/import/stream-load-manual.md
versioned_docs/version-2.0/data-operate/import/stream-load-manual.md
versioned_docs/version-2.1/data-operate/import/stream-load-manual.md

Stream Load 页的代码 comment 残余少量中文：https://doris.apache.org/docs/dev/data-operate/import/stream-load-manual
用户ID
用户姓名
用户年龄
名称
数组

[docs](doc) Update stream load: user name, user ID, user age

---

docs/install/source-install/compilation-with-docker.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/install/source-install/compilation-with-docker.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/source-install/compilation-with-docker.md

issue: https://github.com/apache/doris/discussions/33688

[fix](build) Fix docker build docs

---

community/design/metadata-design.md
docs/admin-manual/maint-monitor/metadata-operation.md
i18n/zh-CN/docusaurus-plugin-content-docs-community/current/design/metadata-design.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/maint-monitor/metadata-operation.md

* fix `metadata-operation.md` doc error
* remove fe metadata recovery mode step

[doc][fe] Fix fe metadata operation doc error

---

docs/query/udf/java-user-defined-function.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query/udf/java-user-defined-function.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query/udf/java-user-defined-function.md
versioned_docs/version-2.1/query/udf/java-user-defined-function.md

update doc for https://github.com/apache/doris/pull/34990

[doc](java-udf)update udf static load in custom_lib

---

docs/sql-manual/sql-functions/aggregate-functions/percentile_approx_weighted.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/percentile_approx_weighted.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/aggregate-functions/percentile_approx_weighted.md
sidebars.json
versioned_docs/version-2.1/sql-manual/sql-functions/aggregate-functions/percentile_approx_weighted.md
versioned_sidebars/version-2.1-sidebars.json

wait for this merge
https://github.com/apache/doris/pull/35132

[doc](function)  percentile_approx_weighted 

---

docs/sql-manual/sql-functions/array-functions/array-reverse-split.md
docs/sql-manual/sql-functions/array-functions/array-split.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/array-functions/array-reverse-split.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/array-functions/array-split.md
sidebars.json

master pr: https://github.com/apache/doris/pull/35619

[feat] add docs of new functions array_split, array_reverse_split

---

docs/admin-manual/config/be-config.md
docs/query/query-variables/time-zone.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/config/be-config.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query/query-variables/time-zone.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/admin-manual/config/be-config.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/query/query-variables/time-zone.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/config/be-config.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query/query-variables/time-zone.md
versioned_docs/version-2.0/admin-manual/config/be-config.md
versioned_docs/version-2.0/query/query-variables/time-zone.md
versioned_docs/version-2.1/admin-manual/config/be-config.md
versioned_docs/version-2.1/query/query-variables/time-zone.md

master pr: https://github.com/apache/doris/pull/35316

[Revert](timezone) Remove a function of timezone and its documents

---

i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/date-time-functions/str-to-date.md
versioned_docs/version-2.0/sql-manual/sql-functions/date-time-functions/str-to-date.md

Indicates from which version a particular feature is supported

[fix](docs) add version comment of str_to_date function

---

docs/sql-manual/sql-functions/table-functions/hdfs.md
docs/sql-manual/sql-functions/table-functions/s3.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-functions/hdfs.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-functions/s3.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/table-functions/hdfs.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/table-functions/s3.md
versioned_docs/version-2.1/sql-manual/sql-functions/table-functions/hdfs.md
versioned_docs/version-2.1/sql-manual/sql-functions/table-functions/s3.md

related: https://github.com/apache/doris/pull/35139

[fix](docs) tvf add `resource` property

---

docs/data-operate/import/routine-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/routine-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/data-operate/import/routine-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/routine-load-manual.md
versioned_docs/version-2.0/data-operate/import/routine-load-manual.md
versioned_docs/version-2.1/data-operate/import/routine-load-manual.md

[doc](routine load) add tips when using Single-task Loading to Multiple Tables

---

blog/release-note-2.1.0.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/releasenotes/release-2.1.0.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/releasenotes/release-2.1.0.md

create table stmt is not correct

[doc] fix release-2.1.0.md

---

docs/admin-manual/config/fe-config.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/config/fe-config.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/admin-manual/config/fe-config.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/config/fe-config.md
versioned_docs/version-2.0/admin-manual/config/fe-config.md
versioned_docs/version-2.1/admin-manual/config/fe-config.md

only Doris 1.2  max_query_retry_time default value is 1

[docs](fix) update max_query_retry_time default value

---

docs/data-operate/delete/delete-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/delete/delete-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/data-operate/delete/delete-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/delete/delete-manual.md
versioned_docs/version-2.0/data-operate/delete/delete-manual.md
versioned_docs/version-2.1/data-operate/delete/delete-manual.md

[doc](delete) delete support predicates on unique key's value column since 2.0

---

docs/lakehouse/datalake-analytics/hive.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/datalake-analytics/hive.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/datalake-analytics/hive.md
versioned_docs/version-2.1/lakehouse/datalake-analytics/hive.md

add doc for https://github.com/apache/doris/pull/36430

[doc][kerberos] add kerberos doc for hive catalog

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/query-admin/sql-interception.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/database/sap-hana.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/admin-manual/query-admin/sql-interception.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/query-admin/sql-interception.md

1. Update the tile "高危 SQL 限制" to “SQL 拦截” for better search.
2. Fix mistaken content for SAP HANA Chinese doc in dev version.

[doc] Resolve doc issues

---

i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/Data-Manipulation-Statements/Manipulation/INSERT-OVERWRITE.md
versioned_docs/version-2.1/sql-manual/sql-statements/Data-Manipulation-Statements/Manipulation/INSERT-OVERWRITE.md

Add insert overwriter partiton(*) version support

Add insert overwriter partiton(*) version support

---

blog/arrow-flight-sql-in-apache-doris-for-10x-faster-data-transfer.md
docs/db-connect/arrow-flight-sql-connect.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/db-connect/arrow-flight-sql-connect.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/db-connect/arrow-flight-sql-connect.md
versioned_docs/version-2.1/db-connect/arrow-flight-sql-connect.md

Add supplementary content and make corrections to the Arrow Flight SQL documentation.

[doc][arrow-flight-sql-connect]Update and Correct Arrow Flight SQL Documentation

---

docs/admin-manual/auth/certificate.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/auth/certificate.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/admin-manual/certificate.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/admin-manual/privilege-ldap/certificate.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/auth/certificate.md
versioned_docs/version-1.2/admin-manual/certificate.md
versioned_docs/version-2.0/admin-manual/privilege-ldap/certificate.md
versioned_docs/version-2.1/admin-manual/auth/certificate.md

[doc] fix mysql ssl pack server-key common

---

docs/admin-manual/resource-admin/workload-policy.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/resource-admin/workload-policy.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/resource-admin/workload-policy.md
versioned_docs/version-2.1/admin-manual/resource-admin/workload-policy.md

Add workload metric query_be_memory_bytes
https://github.com/apache/doris/pull/35662

[docs]Add workload metric query_be_memory_bytes

---

docs/query/join-optimization/runtime-filter.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query/join-optimization/runtime-filter.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query/join-optimization/runtime-filter.md
versioned_docs/version-2.1/query/join-optimization/runtime-filter.md

[doc] update runtime-filter.md

---

docs/sql-manual/sql-statements/Show-Statements/SHOW-CREATE-ASYNC-MATERIALIZED-VIEW.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Show-Statements/SHOW-CREATE-ASYNC-MATERIALIZED-VIEW.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/Show-Statements/SHOW-CREATE-ASYNC-MATERIALIZED-VIEW.md
sidebars.json
versioned_docs/version-2.1/sql-manual/sql-statements/Show-Statements/SHOW-CREATE-ASYNC-MATERIALIZED-VIEW.md
versioned_sidebars/version-2.1-sidebars.json

[doc](mtmv)show create materialized view

---

docs/query/view-materialized-view/query-async-materialized-view.md
docs/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-ASYNC-MATERIALIZED-VIEW.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query/view-materialized-view/query-async-materialized-view.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-ASYNC-MATERIALIZED-VIEW.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query/view-materialized-view/query-async-materialized-view.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-ASYNC-MATERIALIZED-VIEW.md
versioned_docs/version-2.1/query/view-materialized-view/query-async-materialized-view.md
versioned_docs/version-2.1/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-ASYNC-MATERIALIZED-VIEW.md

Add docs for some feature in 2.1.5
such as 
- enable nondeterministic function when create materialized view
- support more query rewrite

[doc](mtmv) Add some feature docs for 2.1.5 and master

---

docs/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-ASYNC-MATERIALIZED-VIEW.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-ASYNC-MATERIALIZED-VIEW.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-ASYNC-MATERIALIZED-VIEW.md
versioned_docs/version-2.1/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-ASYNC-MATERIALIZED-VIEW.md

[doc](mtmv)replace mtmv

---

docs/lakehouse/datalake-analytics/hive.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/datalake-analytics/hive.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/lakehouse/datalake/hive.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/datalake-analytics/hive.md
versioned_docs/version-2.0/lakehouse/datalake/hive.md
versioned_docs/version-2.1/lakehouse/datalake-analytics/hive.md

doris pr： https://github.com/apache/doris/pull/36823

(multicatalog) add docs for hive on tencent dlc

---

docs/sql-manual/sql-functions/debug-functions/ignore.md
docs/sql-manual/sql-functions/debug-functions/non-nullable.md
docs/sql-manual/sql-functions/debug-functions/nullable.md
docs/sql-manual/sql-functions/debug-functions/sleep.md
i18n/zh-CN/docusaurus-plugin-content-docs/current.json
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/debug-functions/ignore.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/debug-functions/non-nullable.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/debug-functions/nullable.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/debug-functions/sleep.md
sidebars.json

debug functions should only appear in dev docs. so no need add to others.
there's no code related.

[Refactor](doc) Add debug functions in dev branch

---

docs/admin-manual/auth/ranger.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/auth/ranger.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/auth/ranger.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/auth/ranger.md
versioned_docs/version-2.1/admin-manual/auth/ranger.md
versioned_docs/version-3.0/admin-manual/auth/ranger.md

add specific jar package directory

[doc](ranger)add specific jar package directory 

---

docs/lakehouse/database/es.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/database/es.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/lakehouse/database/es.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/database/es.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/database/es.md
versioned_docs/version-2.0/lakehouse/database/es.md
versioned_docs/version-2.1/lakehouse/database/es.md
versioned_docs/version-3.0/lakehouse/database/es.md

1. Add json type mapping https://github.com/apache/doris/pull/37101
2. Add session instruction `enable_es_parallel_scroll` and `batch_size` https://github.com/apache/doris/pull/37180

[doc](ES Catalog) Update ES Catalog docs

---

docs/ecosystem/beats.md
docs/ecosystem/logstash.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/beats.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/logstash.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/ecosystem/beats.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/ecosystem/logstash.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/ecosystem/beats.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/ecosystem/logstash.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/beats.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/logstash.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/ecosystem/beats.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/ecosystem/logstash.md
versioned_docs/version-1.2/ecosystem/beats.md
versioned_docs/version-1.2/ecosystem/logstash.md
versioned_docs/version-2.0/ecosystem/beats.md
versioned_docs/version-2.0/ecosystem/logstash.md
versioned_docs/version-2.1/ecosystem/beats.md
versioned_docs/version-2.1/ecosystem/logstash.md
versioned_docs/version-3.0/ecosystem/beats.md
versioned_docs/version-3.0/ecosystem/logstash.md

update logstash and filebeat docs for new configuration and examples

[docs](ecosystem) update logstash and filebeat docs

---

docs/sql-manual/sql-functions/string-functions/auto_partition_name.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/string-functions/auto_partition_name.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/string-functions/auto_partition_name.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/string-functions/auto_partition_name.md
sidebars.json
versioned_docs/version-2.1/sql-manual/sql-functions/string-functions/auto_partition_name.md
versioned_docs/version-3.0/sql-manual/sql-functions/string-functions/auto_partition_name.md
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

https://github.com/apache/doris/pull/34258

[docs](function) support auto_partition_name function

---

docs/admin-manual/config/be-config.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/config/be-config.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/admin-manual/config/be-config.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/config/be-config.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/config/be-config.md
versioned_docs/version-2.0/admin-manual/config/be-config.md
versioned_docs/version-2.1/admin-manual/config/be-config.md
versioned_docs/version-3.0/admin-manual/config/be-config.md

remove the useless config:doris_scanner_queue_size

[Refactor](exec) remove the useless config:doris_scanner_queue_size

---

docs/db-connect/arrow-flight-sql-connect.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/db-connect/arrow-flight-sql-connect.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/db-connect/arrow-flight-sql-connect.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/db-connect/arrow-flight-sql-connect.md
versioned_docs/version-3.0/db-connect/arrow-flight-sql-connect.md

Adding dependencies required by `FlightSqlDriver`

[doc]Adding dependencies required by `FlightSqlDriver`

---

docs/admin-manual/system-tables/table_options.md
docs/admin-manual/system-tables/table_properties.md

adding document for table_options and table_properties.
code PR #38746

[Enhancement] add information_schema.table_options ,table_properties.

---

common_docs_zh/gettingStarted/tutorials/log-storage-analysis.md
gettingStarted/tutorials/log-storage-analysis.md
versioned_docs/version-2.0/practical-guide/log-storage-analysis.md
versioned_docs/version-2.1/practical-guide/log-storage-analysis.md
versioned_docs/version-3.0/practical-guide/log-storage-analysis.md

1. config: enable_compaction_priority_scheduling, total_permits_for_compaction_score, inverted_index_ram_dir_enable
2. remove misused \

update log storage docs

---

common_docs_zh/ecosystem/flink-doris-connector.md
ecosystem/flink-doris-connector.md

Add a guide related to Mongo CDC to the flink-doris-connector documentation.

Add a guide related to Mongo CDC to the flink-doris-connector doc

---

docs/admin-manual/auth/user-privilege.md

doc update for[ #39575](https://github.com/apache/doris/pull/39575)

[Enhancement] doris to support function SESSION_USER()

---

.asf.yaml
.github/PULL_REQUEST_TEMPLATE.md

@jeffreys-cat and @KassieZ are now the maintainers of this repo

add collaborators

---

docs/sql-manual/sql-statements/Cluster-Management-Statements/ALTER-SYSTEM-DROP-FOLLOWER.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Cluster-Management-Statements/ALTER-SYSTEM-DROP-FOLLOWER.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-reference/Cluster-Management-Statements/ALTER-SYSTEM-DROP-FOLLOWER.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-reference/Cluster-Management-Statements/ALTER-SYSTEM-DROP-FOLLOWER.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/Cluster-Management-Statements/ALTER-SYSTEM-DROP-FOLLOWER.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/Cluster-Management-Statements/ALTER-SYSTEM-DROP-FOLLOWER.md
versioned_docs/version-1.2/sql-manual/sql-reference/Cluster-Management-Statements/ALTER-SYSTEM-DROP-FOLLOWER.md
versioned_docs/version-2.0/sql-manual/sql-reference/Cluster-Management-Statements/ALTER-SYSTEM-DROP-FOLLOWER.md
versioned_docs/version-2.1/sql-manual/sql-statements/Cluster-Management-Statements/ALTER-SYSTEM-DROP-FOLLOWER.md
versioned_docs/version-3.0/sql-manual/sql-statements/Cluster-Management-Statements/ALTER-SYSTEM-DROP-FOLLOWER.md

Issue : https://github.com/apache/doris-website/issues/1002

[docs](sql-manual) Fix typo of ALTER SYSTEM DROP FOLLOWER from user feedbacks

---

docs/admin-manual/config/be-config.md
docs/query/query-variables/variables.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/config/be-config.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query/query-variables/variables.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/config/be-config.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query/query-variables/variables.md
versioned_docs/version-3.0/admin-manual/config/be-config.md
versioned_docs/version-3.0/query/query-variables/variables.md

https://github.com/apache/doris/pull/39219

[doc]remove som be.conf

---

docs/sql-manual/sql-functions/aggregate-functions/regr_sxx.md
docs/sql-manual/sql-functions/aggregate-functions/regr_sxy.md
docs/sql-manual/sql-functions/aggregate-functions/regr_syy.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/regr_sxx.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/regr_sxy.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/regr_syy.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/aggregate-functions/regr_sxx.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/aggregate-functions/regr_sxy.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/aggregate-functions/regr_syy.md
sidebars.json
versioned_docs/version-3.0/sql-manual/sql-functions/aggregate-functions/regr_sxx.md
versioned_docs/version-3.0/sql-manual/sql-functions/aggregate-functions/regr_sxy.md
versioned_docs/version-3.0/sql-manual/sql-functions/aggregate-functions/regr_syy.md
versioned_sidebars/version-3.0-sidebars.json

https://github.com/apache/doris/pull/39187

[docs](function) support aggregrate function regr_sxx regr_sxy regr_syy

---

docs/sql-manual/sql-functions/conditional-functions/assert-true.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/conditional-functions/assert-true.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/conditional-functions/assert-true.md
sidebars.json
versioned_docs/version-3.0/sql-manual/sql-functions/conditional-functions/assert-true.md
versioned_sidebars/version-3.0-sidebars.json

code pr: https://github.com/apache/doris/pull/39393

[Feature](function) Support function assert_true

---

docs/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-TABLE-PARTITION.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-TABLE-PARTITION.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-reference/Data-Definition-Statements/Alter/ALTER-TABLE-PARTITION.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-TABLE-PARTITION.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-TABLE-PARTITION.md
versioned_docs/version-2.0/sql-manual/sql-reference/Data-Definition-Statements/Alter/ALTER-TABLE-PARTITION.md
versioned_docs/version-2.1/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-TABLE-PARTITION.md
versioned_docs/version-3.0/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-TABLE-PARTITION.md

Doris PR: https://github.com/apache/doris/pull/37114

[doc](alter) alter to add partitions in batches

---

docs/sql-manual/sql-functions/aggregate-functions/percentile.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/percentile.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/aggregate-functions/percentile.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/aggregate-functions/percentile.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/aggregate-functions/percentile.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/aggregate-functions/percentile.md
versioned_docs/version-1.2/sql-manual/sql-functions/aggregate-functions/percentile.md
versioned_docs/version-2.0/sql-manual/sql-functions/aggregate-functions/percentile.md
versioned_docs/version-2.1/sql-manual/sql-functions/aggregate-functions/percentile.md
versioned_docs/version-3.0/sql-manual/sql-functions/aggregate-functions/percentile.md

[Enhancement](function) add more explaination for function percentile

---

docs/sql-manual/sql-functions/numeric-functions/acos.md
docs/sql-manual/sql-functions/numeric-functions/sqrt.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/numeric-functions/sqrt.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/math-functions/sqrt.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/numeric-functions/sqrt.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/numeric-functions/acos.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/numeric-functions/asin.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/numeric-functions/sqrt.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/numeric-functions/acos.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/numeric-functions/asin.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/numeric-functions/sqrt.md
versioned_docs/version-1.2/sql-manual/sql-functions/math-functions/sqrt.md
versioned_docs/version-2.0/sql-manual/sql-functions/numeric-functions/sqrt.md
versioned_docs/version-2.1/sql-manual/sql-functions/numeric-functions/acos.md
versioned_docs/version-2.1/sql-manual/sql-functions/numeric-functions/asin.md
versioned_docs/version-2.1/sql-manual/sql-functions/numeric-functions/sqrt.md
versioned_docs/version-3.0/sql-manual/sql-functions/numeric-functions/acos.md
versioned_docs/version-3.0/sql-manual/sql-functions/numeric-functions/asin.md
versioned_docs/version-3.0/sql-manual/sql-functions/numeric-functions/sqrt.md

https://github.com/apache/doris/pull/40267

[doc](update) asin/acos/sqrt related

---

docs/data-operate/update/update-of-unique-model.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/update/update-of-unique-model.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/data-operate/update/update-of-unique-model.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/update/update-of-unique-model.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/update/update-of-unique-model.md
versioned_docs/version-2.0/data-operate/update/update-of-unique-model.md
versioned_docs/version-2.1/data-operate/update/update-of-unique-model.md
versioned_docs/version-3.0/data-operate/update/update-of-unique-model.md

[doc](partial update) update docs of partial update

---

src/theme/DocSidebar/Desktop/Content/index.js

fix: fix docs sidebar version error

fix: fix docs sidebar version error

---

docs/admin-manual/config/be-config.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/config/be-config.md

this config of code have beed removed,  so the doc should be update.

[doc](config) remove some unused config desc in BE

---

blog/variant-in-apache-doris-2.1.md
docs/sql-manual/sql-data-types/semi-structured/VARIANT.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-data-types/semi-structured/VARIANT.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-data-types/semi-structured/VARIANT.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-data-types/semi-structured/VARIANT.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-data-types/semi-structured/VARIANT.md
versioned_docs/version-2.0/sql-manual/sql-data-types/semi-structured/VARIANT.md
versioned_docs/version-2.1/sql-manual/sql-data-types/semi-structured/VARIANT.md
versioned_docs/version-3.0/sql-manual/sql-data-types/semi-structured/VARIANT.md

modify github events sample download link, and add some FQA

---

docs/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-quickstart.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-quickstart.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/cluster-deployment/k8s-deploy/install-quickstart.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-quickstart.md
sidebars.json
versioned_docs/version-2.1/install/cluster-deployment/k8s-deploy/install-quickstart.md
versioned_docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-quickstart.md
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

 [docs](k8s) add k8s operator quickstart

---

docs/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-RESOURCE.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-RESOURCE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-RESOURCE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-RESOURCE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-RESOURCE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-RESOURCE.md
versioned_docs/version-1.2/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-RESOURCE.md
versioned_docs/version-2.0/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-RESOURCE.md
versioned_docs/version-2.1/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-RESOURCE.md
versioned_docs/version-3.0/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-RESOURCE.md

[fix](resource) username of hdfs is hadoop.username

---

i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/resource-admin/workload-group.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/resource-admin/workload-group.md
versioned_docs/version-2.1/admin-manual/resource-admin/workload-group.md
versioned_docs/version-3.0/admin-manual/resource-admin/workload-group.md

Fix tip format error

---

docs/admin-manual/cluster-management/upgrade.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/cluster-management/upgrade.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/admin-manual/cluster-management/upgrade.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/cluster-management/upgrade.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/cluster-management/upgrade.md
versioned_docs/version-2.0/admin-manual/cluster-management/upgrade.md
versioned_docs/version-2.1/admin-manual/cluster-management/upgrade.md
versioned_docs/version-3.0/admin-manual/cluster-management/upgrade.md

(doc)fix upgrade.md

---

common_docs_zh/ecosystem/doris-kafka-connector.md
ecosystem/doris-kafka-connector.md

[ecosystem]doris-kafka-connector adds poll data timeout processing method

---

i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/query/udf/java-user-defined-function.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query/udf/java-user-defined-function.md
versioned_docs/version-2.0/query/udf/java-user-defined-function.md
versioned_docs/version-2.1/query/udf/java-user-defined-function.md

as UDTF is supported starting from Doris version 3.0

[doc](udtf) remove some doc about udtf in branch2.0/2.1

---

docs/sql-manual/sql-functions/aggregate-functions/linear-histogram.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/linear-histogram.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/aggregate-functions/linear-histogram.md
sidebars.json
versioned_docs/version-3.0/sql-manual/sql-functions/aggregate-functions/linear-histogram.md
versioned_sidebars/version-3.0-sidebars.json

[linear_histogram](https://github.com/apache/doris/pull/39546) in doris

[doc](agg-func) add linear_histogram dev doc

---

docs/query/query-analysis/import-analysis.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query/query-analysis/import-analysis.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/query/query-analysis/import-analysis.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query/query-analysis/import-analysis.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query/query-analysis/import-analysis.md
versioned_docs/version-2.0/query/query-analysis/import-analysis.md
versioned_docs/version-2.1/query/query-analysis/import-analysis.md
versioned_docs/version-3.0/query/query-analysis/import-analysis.md

fix query analysis file link error

---

src/constant/download.data.ts
src/theme/DocItem/Layout/pathTransfer.ts
src/theme/DocSidebar/Desktop/Content/index.js

fix: fix the 3.0/2.1 version docs edit this page link error

---

docs/lakehouse/database/sqlserver.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/database/sqlserver.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/lakehouse/database/sqlserver.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/database/sqlserver.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/database/sqlserver.md
versioned_docs/version-2.0/lakehouse/database/sqlserver.md
versioned_docs/version-2.1/lakehouse/database/sqlserver.md
versioned_docs/version-3.0/lakehouse/database/sqlserver.md

(faq)(jdbc catalog) add sqlserver tls faq

---

common_docs_zh/gettingStarted/tutorials/building-lakehouse/doris-hudi.md
docs/lakehouse/datalake-building/hive-build.md
gettingStarted/tutorials/building-lakehouse/doris-hudi.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/datalake-building/hive-build.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/datalake-building/hive-build.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/datalake-building/hive-build.md
versioned_docs/version-2.1/lakehouse/datalake-building/hive-build.md
versioned_docs/version-3.0/lakehouse/datalake-building/hive-build.md

fix some mispelling

---

docs/data-operate/import/migrate-data-from-other-olap.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/migrate-data-from-other-olap.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/migrate-data-from-other-olap.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/migrate-data-from-other-olap.md
versioned_docs/version-2.1/data-operate/import/migrate-data-from-other-olap.md
versioned_docs/version-3.0/data-operate/import/migrate-data-from-other-olap.md

fix some branding issues

---

src/theme/DocSidebar/Desktop/Content/index.js

fix: disable pdf download on locale en

fix: disable pdf download on locale en

---

common_docs_zh/gettingStarted/tutorials/log-storage-analysis.md

[doc] Fix missing words in log storage zh doc

---

docs/compute-storage-decoupled/compilation-and-deployment.md
versioned_docs/version-3.0/compute-storage-decoupled/compilation-and-deployment.md

- [ *] dev
- [ *] 3.0
- [* ] English

[fix](typo) fix typo in compute and storage decoupled

---

docusaurus.config.js
gettingStarted/demo-block/latest.tsx

[events] Update singapore events

---

docs/compute-storage-decoupled/before-deployment.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/before-deployment.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/compute-storage-decoupled/before-deployment.md
versioned_docs/version-3.0/compute-storage-decoupled/before-deployment.md

[fix](cloud) add download link for fdb_ctl.sh

---

i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/overview.md
versioned_docs/version-2.1/table-design/overview.md
versioned_docs/version-3.0/table-design/overview.md
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

[pick] pick table overview from dev to 3.0 and 2.1

---

docusaurus.config.js
gettingStarted/demo-block/latest.tsx

[events] Update events link

---

blog/release-note-2.0.15.md
common_docs_zh/releasenotes/v2.0/release-2.0.15.md
releasenotes/v2.0/release-2.0.15.md

[fix](release) Fix 2.0.15 release note

---

docs/data-operate/import/load-data-format.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/load-data-format.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/load-data-format.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/load-data-format.md
versioned_docs/version-2.1/data-operate/import/load-data-format.md
versioned_docs/version-3.0/data-operate/import/load-data-format.md

[fix](load) fix the examples in the load-data-format document

---

docs/lakehouse/database/jdbc.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/database/jdbc.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/lakehouse/database/jdbc.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/database/jdbc.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/database/jdbc.md
versioned_docs/version-2.0/lakehouse/database/jdbc.md
versioned_docs/version-2.1/lakehouse/database/jdbc.md
versioned_docs/version-3.0/lakehouse/database/jdbc.md

improve jdbc catalog connection pool doc

---

docs/admin-manual/config/fe-config.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/config/fe-config.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/config/fe-config.md
versioned_docs/version-3.0/admin-manual/config/fe-config.md

https://github.com/apache/doris/pull/40302

profile_manager_gc_interval_seconds

---

community/developer-guide/bitmap-hll-file-format.md
i18n/zh-CN/docusaurus-plugin-content-docs-community/current/developer-guide/bitmap-hll-file-format.md

[doc] Add type of SET for BitmapValue

---

docusaurus.config.js

- fix: fix announcementBar id error

fix: fix announcementBar id error

---

common_docs_zh/ecosystem/doris-kafka-connector.md
ecosystem/doris-kafka-connector.md

[ecosystem]Kafka-connector properties adds timeout adjustment suggestions

---

docs/data-operate/delete/delete-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/delete/delete-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/delete/delete-manual.md
versioned_docs/version-2.1/data-operate/delete/delete-manual.md

[docs](delete) Update delete timeout related docs

---

i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/open-api/be-http/check-tablet-segment.md

[fix]modify error description of Request and Examples

---

common_docs_zh/gettingStarted/demo-block/latest.tsx
docusaurus.config.js

[event] Update doris meetup 

---

docs/admin-manual/open-api/be-http/health.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/health.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/open-api/be-http/health.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/open-api/be-http/health.md
versioned_docs/version-2.1/admin-manual/open-api/be-http/health.md
versioned_docs/version-3.0/admin-manual/open-api/be-http/health.md

[fix] Modify the incorrect description of the returned field content

---

i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/table-design/data-partition.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/data-partition.md
versioned_docs/version-2.0/table-design/data-partition.md
versioned_docs/version-2.1/table-design/data-partition.md

[fix](doc) add partitions now only support 3.0

---

docs/sql-manual/sql-functions/string-functions/count_substrings.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/string-functions/count_substrings.md
sidebars.json

[doc](function)support count_substrings functions

---

docs/admin-manual/system-tables/information_schema/columns.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/system-tables/overview.md
versioned_docs/version-2.1/admin-manual/system-tables/information_schema/columns.md
versioned_docs/version-3.0/admin-manual/system-tables/information_schema/columns.md

[docs](systemTable) Fix typo of system table

---

common_docs_zh/ecosystem/doris-streamloader.md
ecosystem/doris-streamloader.md

(doc)[doris streamloader] update doris streamloader installation link

---

docs/data-operate/import/load-data-format.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/load-data-format.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/load-data-format.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/load-data-format.md
versioned_docs/version-2.1/data-operate/import/load-data-format.md
versioned_docs/version-3.0/data-operate/import/load-data-format.md

[fix](load) fix some typos for load data format

---

i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-TABLE-PROPERTY.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-DATABASE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/data-partition.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/tiered-storage/diff-disk-medium-migration.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/tiered-storage/remote-storage.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-TABLE-PROPERTY.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-DATABASE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/data-partition.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/tiered-storage/diff-disk-medium-migration.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/tiered-storage/remote-storage.md
versioned_docs/version-2.1/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-TABLE-PROPERTY.md
versioned_docs/version-2.1/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-DATABASE.md
versioned_docs/version-2.1/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE.md
versioned_docs/version-2.1/table-design/data-partition.md
versioned_docs/version-2.1/table-design/tiered-storage/diff-disk-medium-migration.md
versioned_docs/version-2.1/table-design/tiered-storage/remote-storage.md
versioned_docs/version-3.0/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-TABLE-PROPERTY.md
versioned_docs/version-3.0/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-DATABASE.md
versioned_docs/version-3.0/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE.md
versioned_docs/version-3.0/table-design/data-partition.md
versioned_docs/version-3.0/table-design/tiered-storage/diff-disk-medium-migration.md
versioned_docs/version-3.0/table-design/tiered-storage/remote-storage.md
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

pick
https://github.com/apache/doris-website/pull/874/files

[doc](tiered) Add dynamic partition migration Pick #874 to 2.1 and 3.0

---

docs/data-operate/transaction.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/transaction.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/transaction.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/transaction.md
versioned_docs/version-2.1/data-operate/transaction.md
versioned_docs/version-3.0/data-operate/transaction.md

[doc](stream_load)fix_stream_load2pc_doc

---

common_docs_zh/ecosystem/flink-doris-connector.md
ecosystem/flink-doris-connector.md

[Doc](flink) add arrow flight sql read doc

---

docs/sql-manual/sql-functions/date-time-functions/hour.md
docs/sql-manual/sql-functions/date-time-functions/minute.md
docs/sql-manual/sql-functions/date-time-functions/second.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/date-time-functions/hour.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/date-time-functions/minute.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/date-time-functions/second.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/date-time-functions/hour.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/date-time-functions/minute.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/date-time-functions/second.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/date-time-functions/hour.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/date-time-functions/minute.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/date-time-functions/second.md
versioned_docs/version-2.1/sql-manual/sql-functions/date-time-functions/hour.md
versioned_docs/version-2.1/sql-manual/sql-functions/date-time-functions/minute.md
versioned_docs/version-2.1/sql-manual/sql-functions/date-time-functions/second.md
versioned_docs/version-3.0/sql-manual/sql-functions/date-time-functions/hour.md
versioned_docs/version-3.0/sql-manual/sql-functions/date-time-functions/minute.md
versioned_docs/version-3.0/sql-manual/sql-functions/date-time-functions/second.md

https://github.com/apache/doris/pull/41008

[doc]  hour/minute/second functions support time as an argument.

---

.github/workflows/build-check.yml

[Fix](CI) make file move related deadlink check enable

---

docs/sql-manual/sql-functions/debug-functions/sleep.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/debug-functions/sleep.md

[Fix](function) Add highlight reminder for function sleep

---

docs/data-operate/scheduler/job-scheduler.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/scheduler/job-scheduler.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/scheduler/job-scheduler.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/scheduler/job-scheduler.md
versioned_docs/version-2.1/data-operate/scheduler/job-scheduler.md
versioned_docs/version-3.0/data-operate/scheduler/job-scheduler.md

[doc](typo) fix some typo in job-scheduler.md

---

docs/lakehouse/database/gbase-8a.md
docs/lakehouse/datalake-analytics/hive.md
docs/lakehouse/datalake-analytics/paimon.md
docs/lakehouse/datalake-building/hive-build.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/database/gbase-8a.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/datalake-analytics/hive.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/datalake-analytics/paimon.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/datalake-building/hive-build.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/datalake-analytics/hive.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/datalake-analytics/paimon.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/datalake-building/hive-build.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/datalake-analytics/hive.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/datalake-analytics/paimon.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/datalake-building/hive-build.md
versioned_docs/version-2.1/lakehouse/datalake-analytics/hive.md
versioned_docs/version-2.1/lakehouse/datalake-analytics/paimon.md
versioned_docs/version-2.1/lakehouse/datalake-building/hive-build.md
versioned_docs/version-3.0/lakehouse/datalake-analytics/hive.md
versioned_docs/version-3.0/lakehouse/datalake-analytics/paimon.md
versioned_docs/version-3.0/lakehouse/datalake-building/hive-build.md

[mod](catalog) update doc for 2.1.7 and 3.0.3

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/stream-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/data-operate/import/stream-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/stream-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/stream-load-manual.md

[docs](streamload) Update deadlink of CN docs

---

docs/lakehouse/cloud-auth.md
docs/lakehouse/datalake-analytics/iceberg.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/cloud-auth.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/datalake-analytics/iceberg.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/cloud-auth.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/datalake-analytics/iceberg.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/cloud-auth.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/datalake-analytics/iceberg.md
versioned_docs/version-2.1/lakehouse/cloud-auth.md
versioned_docs/version-2.1/lakehouse/datalake-analytics/iceberg.md
versioned_docs/version-3.0/lakehouse/cloud-auth.md
versioned_docs/version-3.0/lakehouse/datalake-analytics/iceberg.md

[fix](catalog) fix iceberg catalog with glue doc

---

i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-reference/Data-Definition-Statements/Alter/ALTER-TABLE-PARTITION.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-TABLE-PARTITION.md
versioned_docs/version-2.0/sql-manual/sql-reference/Data-Definition-Statements/Alter/ALTER-TABLE-PARTITION.md
versioned_docs/version-2.1/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-TABLE-PARTITION.md

[fix](doc) add partitions not support 2.0 2.1

---

docs/data-operate/import/import-way/stream-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/stream-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/data-operate/import/stream-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/stream-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/stream-load-manual.md
versioned_docs/version-2.0/data-operate/import/stream-load-manual.md
versioned_docs/version-2.1/data-operate/import/import-way/stream-load-manual.md
versioned_docs/version-3.0/data-operate/import/import-way/stream-load-manual.md

[doc](stream load) fix stream load doc error

---

docs/compute-storage-decoupled/file-cache.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/file-cache.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/compute-storage-decoupled/file-cache.md
versioned_docs/version-3.0/compute-storage-decoupled/file-cache.md

- [ x] dev
- [ x] 3.0
- [ x] Chinese
- [ x] English

[doc](cloud) update file cache eviction policy (#42451)

---

docs/data-operate/import/import-way/stream-load-manual.md
docs/data-operate/import/load-data-format.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/stream-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/load-data-format.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/data-operate/import/stream-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/stream-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/load-data-format.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/stream-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/load-data-format.md
versioned_docs/version-2.0/data-operate/import/stream-load-manual.md
versioned_docs/version-2.1/data-operate/import/import-way/stream-load-manual.md
versioned_docs/version-2.1/data-operate/import/load-data-format.md
versioned_docs/version-3.0/data-operate/import/import-way/stream-load-manual.md
versioned_docs/version-3.0/data-operate/import/load-data-format.md

[doc](stream load) fix stream load doc escape error

---

docs/table-design/row-store.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/row-store.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/row-store.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/row-store.md
versioned_docs/version-2.1/table-design/row-store.md
versioned_docs/version-3.0/table-design/row-store.md

opt description of row-store

---

docusaurus.config.js

[web](topbanner) Update top banner info

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/data-admin/repairing-data.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/compaction-run.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/admin-manual/be/compaction-run.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/open-api/be-http/compaction-run.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/data-admin/repairing-data.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/open-api/be-http/compaction-run.md

[docs](data-admin) Fix deadlink of dat

---

docs/data-operate/import/import-way/stream-load-manual.md
docs/data-operate/import/load-data-format.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/stream-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/load-data-format.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/stream-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/load-data-format.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/stream-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/load-data-format.md
versioned_docs/version-2.1/data-operate/import/import-way/stream-load-manual.md
versioned_docs/version-2.1/data-operate/import/load-data-format.md
versioned_docs/version-3.0/data-operate/import/import-way/stream-load-manual.md
versioned_docs/version-3.0/data-operate/import/load-data-format.md

[doc](load) fix some load doc error

---

common_docs_zh/ecosystem/kettle.md
ecosystem/kettle.md
sidebars.json
versioned_sidebars/version-1.2-sidebars.json
versioned_sidebars/version-2.0-sidebars.json
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

[ecosystem](kettle) add kettle plugin for ecosystem

---

docs/table-design/tiered-storage/remote-storage.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/tiered-storage/remote-storage.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/tiered-storage/remote-storage.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/tiered-storage/remote-storage.md
versioned_docs/version-2.1/table-design/tiered-storage/remote-storage.md
versioned_docs/version-3.0/table-design/tiered-storage/remote-storage.md

[Doc](remote storage)Modify remote storage doc

---

docs/data-operate/import/import-way/broker-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/broker-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/data-operate/import/broker-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/broker-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/broker-load-manual.md
versioned_docs/version-2.0/data-operate/import/broker-load-manual.md
versioned_docs/version-2.1/data-operate/import/import-way/broker-load-manual.md
versioned_docs/version-3.0/data-operate/import/import-way/broker-load-manual.md

[doc](typo) fix some typo in `broker-load` section

---

common_docs_zh/ecosystem/datax.md
ecosystem/datax.md

[doc](ecosystem) improve datax doriswriter doc

---

docs/lakehouse/database/max-compute.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/database/max-compute.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/database/max-compute.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/database/max-compute.md
versioned_docs/version-2.1/lakehouse/database/max-compute.md
versioned_docs/version-3.0/lakehouse/database/max-compute.md

Since I refactored the maxcompute code before, some properties changed when creating the catalog, so I refactored the corresponding documents here.
pr : https://github.com/apache/doris/pull/40225

[Refactor](maxcompute)Rewrite maxcompute cn and en document.

---

docs/admin-manual/audit-plugin.md
docs/admin-manual/system-tables/internal_schema/audit_log.md
docs/admin-manual/system-tables/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/current.json
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/audit-plugin.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/system-tables/internal_schema/audit_log.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/system-tables/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1.json
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/audit-plugin.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/system-tables/internal_schema/audit_log.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/system-tables/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0.json
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/audit-plugin.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/system-tables/internal_schema/audit_log.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/system-tables/overview.md
sidebars.json
versioned_docs/version-2.1/admin-manual/audit-plugin.md
versioned_docs/version-2.1/admin-manual/system-tables/internal_schema/audit_log.md
versioned_docs/version-2.1/admin-manual/system-tables/overview.md
versioned_docs/version-3.0/admin-manual/audit-plugin.md
versioned_docs/version-3.0/admin-manual/system-tables/internal_schema/audit_log.md
versioned_docs/version-3.0/admin-manual/system-tables/overview.md
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

[opt] opt audit log related doc

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-data-types/semi-structured/JSON.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-data-types/semi-structured/JSON.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-data-types/semi-structured/JSON.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-data-types/semi-structured/JSON.md

[fix](sql-type) string_type_length_soft_limit_bytes case

---

docs/admin-manual/resource-admin/workload-group.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/resource-admin/workload-group.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/resource-admin/workload-group.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/resource-admin/workload-group.md
versioned_docs/version-2.1/admin-manual/resource-admin/workload-group.md
versioned_docs/version-3.0/admin-manual/resource-admin/workload-group.md

[Docs]update cgroup v1/v2 usage

---

docs/admin-manual/system-tables/information_schema/partitions.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/system-tables/information_schema/partitions.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/system-tables/information_schema/partitions.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/system-tables/information_schema/partitions.md
versioned_docs/version-2.1/admin-manual/system-tables/information_schema/partitions.md
versioned_docs/version-3.0/admin-manual/system-tables/information_schema/partitions.md

[Doc](systable) Support system table information_schema.partitions

---

docs/sql-manual/sql-functions/date-time-functions/str-to-date.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/date-time-functions/str-to-date.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/date-time-functions/str-to-date.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/date-time-functions/str-to-date.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/date-time-functions/str-to-date.md
versioned_docs/version-2.0/sql-manual/sql-functions/date-time-functions/str-to-date.md
versioned_docs/version-2.1/sql-manual/sql-functions/date-time-functions/str-to-date.md
versioned_docs/version-3.0/sql-manual/sql-functions/date-time-functions/str-to-date.md

[Fix](doc) Fix wrong description of behavior of str_to_date

---

docs/compute-storage-decoupled/managing-storage-vault.md
docs/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-STORAGE-VAULT.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/managing-storage-vault.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-STORAGE-VAULT.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/compute-storage-decoupled/managing-storage-vault.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-STORAGE-VAULT.md
versioned_docs/version-3.0/compute-storage-decoupled/managing-storage-vault.md
versioned_docs/version-3.0/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-STORAGE-VAULT.md

* Add `use_path_style` property for s3 storage vault
* Add `example` for alter storage vault

[opt] opt storage vault doc

---

docs/data-operate/import/import-way/routine-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/routine-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/routine-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/routine-load-manual.md
versioned_docs/version-2.1/data-operate/import/import-way/routine-load-manual.md
versioned_docs/version-3.0/data-operate/import/import-way/routine-load-manual.md

[doc](routine load) optimize routine load doc

---

docs/table-design/index/inverted-index.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/index/inverted-index.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/table-design/index/inverted-index.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/index/inverted-index.md
versioned_docs/version-2.0/table-design/index/inverted-index.md
versioned_docs/version-2.1/table-design/index/inverted-index.md

Fix inverted index demo dataset url

---

src/theme/Navbar/Layout/index.tsx

Remove the slash from the URL.

fix:Solve the problem of URL automatically carrying slashes causing dead links

---

docs/table-design/schema-change.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/schema-change.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/schema-change.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/schema-change.md
versioned_docs/version-2.1/table-design/schema-change.md
versioned_docs/version-3.0/table-design/schema-change.md

[docs](schema-change) Refine schema change rlated docs

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/insert-into-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/routine-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/stream-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/insert-into-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/routine-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/stream-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/insert-into-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/routine-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/stream-load-manual.md

[doc](load) update create table comment

---

common_docs_zh/ecosystem/datax.md
common_docs_zh/ecosystem/kettle.md
ecosystem/datax.md
ecosystem/kettle.md

[doc](ecosystem) update kettle plugin add options

---

docs/query-acceleration/tuning/runtime-filter.md
docs/query-acceleration/tuning/topn-query.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/runtime-filter.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/topn-query.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-acceleration/tuning/runtime-filter.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-acceleration/tuning/topn-query.md
versioned_docs/version-3.0/query-acceleration/tuning/runtime-filter.md
versioned_docs/version-3.0/query-acceleration/tuning/topn-query.md

update topn_filter_ratio doc

---

docs/data-operate/import/import-way/broker-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/broker-load-manual.md

[docs](load) improve broker load structure

---

common_docs_zh/ecosystem/fluentbit.md
ecosystem/fluentbit.md
sidebars.json
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

[doc] (fluentbit) fluentbit doris output plugin

---

i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/index/inverted-index.md

drop index response delete index not construct index

[Chinese] Update inverted-index.md

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/tiered-storage/remote-storage.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/tiered-storage/remote-storage.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/tiered-storage/remote-storage.md

[Fix] Update remote-storage.md

---

docs/sql-manual/sql-functions/table-functions/posexplode.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-functions/posexplode.md
sidebars.json

[doc](function) support table-function posexplode

---

common_docs_zh/gettingStarted/tutorials/building-lakehouse/doris-lakesoul.md
gettingStarted/tutorials/building-lakehouse/doris-lakesoul.md

[doc] fix link error of lakesoul tutorial

---

i18n/zh-CN/docusaurus-plugin-content-docs-community/current.json

[fix] fix cron deploy1

---

docusaurus.config.js
package.json

Update:add event Doris Summit Asia 2024

---

common_docs_zh/ecosystem/dbt-doris-adapter.md
ecosystem/dbt-doris-adapter.md

[doc](dbt)add dbt doc example

---

docs/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-quickstart.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-quickstart.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/cluster-deployment/k8s-deploy/install-quickstart.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-quickstart.md
versioned_docs/version-2.1/install/cluster-deployment/k8s-deploy/install-quickstart.md
versioned_docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-quickstart.md

[doc](fixed) selectdb to apache

---

common_docs_zh/gettingStarted/demo-block/latest.tsx
gettingStarted/demo-block/latest.tsx

[fix] Update Doris Summit Asia

---

i18n/zh-CN/docusaurus-plugin-content-docs-community/current/doris-announcement/announcement-2401.md

[mod] modify the announcement

---

docs/query-data/udf/java-user-defined-function.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query-data/udf/java-user-defined-function.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-FUNCTION.md

[doc](udf) refactor the java-udf function doc

---

docs/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-TABLE-REPLACE.md

[#43537](https://github.com/apache/doris/issues/43537)
https://github.com/apache/doris/pull/43538

[Enhancement] replace table options to keep original dropped table in recycle bin

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/join-hint.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/query/join-optimization/join-hint.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-acceleration/tuning/join-hint.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-acceleration/tuning/join-hint.md

[Chinese] update join hint

---

check_move.py

[Fix](CI) ignore markdown file suffix changes in deadlink check

---

docusaurus.config.js

[update] update banner link

---

docs/compute-storage-decoupled/compilation-and-deployment.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/compilation-and-deployment.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/compute-storage-decoupled/compilation-and-deployment.md
versioned_docs/version-3.0/compute-storage-decoupled/compilation-and-deployment.md

[improvement](cluster_id) provide a shell generating random cluster_id

---

.github/workflows/build-check.yml
src/theme/SearchBar/fetchIndexes.js

modify the request url of search

---

releasenotes/v3.0/release-3.0.3.md

[fix] release 3.0.3

---

docs/admin-manual/auth/ranger.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/auth/ranger.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/auth/ranger.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/auth/ranger.md
versioned_docs/version-2.1/admin-manual/auth/ranger.md
versioned_docs/version-3.0/admin-manual/auth/ranger.md

[auth]change default log level of ranger to warn

---

docs/query-acceleration/high-concurrent-point-query.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/high-concurrent-point-query.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/query/high-concurrent-point-query.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-acceleration/high-concurrent-point-query.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-acceleration/high-concurrent-point-query.md
versioned_docs/version-2.0/query/high-concurrent-point-query.md
versioned_docs/version-2.1/query-acceleration/high-concurrent-point-query.md
versioned_docs/version-3.0/query-acceleration/high-concurrent-point-query.md

fix name SQL conflict error in point query docs

---

docs/query-data/mysql-compatibility.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query-data/mysql-compatibility.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-data/mysql-compatibility.md
versioned_docs/version-2.0/query/query-data/mysql-compatibility.md
versioned_docs/version-2.1/query-data/mysql-compatibility.md
versioned_docs/version-3.0/query-data/mysql-compatibility.md

Related PR: https://github.com/apache/doris-website/pull/1498

[update] Fix typo of MySQL Compatibility

---

docs/query-data/multi-dimensional-analytics.md
docs/query-data/window-function.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query-data/multi-dimensional-analytics.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query-data/window-function.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-data/multi-dimensional-analytics.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-data/window-function.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-data/multi-dimensional-analytics.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-data/window-function.md
versioned_docs/version-2.1/query-data/multi-dimensional-analytics.md
versioned_docs/version-2.1/query-data/window-function.md
versioned_docs/version-3.0/query-data/multi-dimensional-analytics.md
versioned_docs/version-3.0/query-data/window-function.md

[fix] add the window-function doc and multi-dimensional-analytics doc sql used table data

---

docusaurus.config.js

Restore announcementBar

---

docs/query-data/udf/java-user-defined-function.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query-data/udf/java-user-defined-function.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-data/udf/java-user-defined-function.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-data/udf/java-user-defined-function.md
versioned_docs/version-2.1/query-data/udf/java-user-defined-function.md
versioned_docs/version-3.0/query-data/udf/java-user-defined-function.md

[doc](udf) update some error about java-udf type

---

docs/gettingStarted/tutorials/building-lakehouse/doris-iceberg.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/gettingStarted/tutorials/building-lakehouse/doris-iceberg.md

add interacting with PyIceberg.
Co-authored-by: lutinglt

[doc](iceberg) add interacting with PyIceberg

---

src/scss/components/markdown.scss

fix:li margin-bottom

---

i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/small-file-mgr.md

[fix] Fix title of small file mananger

---

src/theme/Admonition/Layout/styles.module.css

fix:admonition style

---

sidebars.json

[fix](ccr) update ccr dir

---

check_all_deadlink.py

[script] Deadlink check script

---

docs/sql-manual/sql-statements/Data-Manipulation-Statements/Manipulation/DELETE.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/delete/delete-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Data-Manipulation-Statements/Manipulation/DELETE.md
versioned_docs/version-2.0/data-operate/delete/delete-manual.md

[doc](delete) update delete manual

---

check_move.py

[Fix](CI) Support remove spare suffix of links in documents

---

docs/data-operate/import/import-way/routine-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/routine-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/routine-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/routine-load-manual.md
versioned_docs/version-2.1/data-operate/import/import-way/routine-load-manual.md
versioned_docs/version-3.0/data-operate/import/import-way/routine-load-manual.md

[fix](routine-load) fix wrong properties

---

docs/admin-manual/data-admin/ccr/manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/data-admin/ccr/manual.md

Update CCR manual

---

docs/admin-manual/data-admin/ccr/performance.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/data-admin/ccr/performance.md
sidebars.json

[ccr] add performance

---

docs/compute-storage-decoupled/upgrade.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/upgrade.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/compute-storage-decoupled/upgrade.md
sidebars.json
versioned_docs/version-3.0/compute-storage-decoupled/upgrade.md
versioned_sidebars/version-3.0-sidebars.json

[upgrade] add docs for upgrading storage&compute decoupling

---

docs/sql-manual/sql-statements/Database-Administration-Statements/RECOVER.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Database-Administration-Statements/RECOVER.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-reference/Database-Administration-Statements/RECOVER.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/recycle/RECOVER.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/recycle/RECOVER.md
versioned_docs/version-2.0/sql-manual/sql-reference/Database-Administration-Statements/RECOVER.md
versioned_docs/version-2.1/sql-manual/sql-statements/recycle/RECOVER.md
versioned_docs/version-3.0/sql-manual/sql-statements/recycle/RECOVER.md

[bug][recover] fix example

---

docs/gettingStarted/tutorials/building-lakehouse/doris-iceberg.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/gettingStarted/tutorials/building-lakehouse/doris-iceberg.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/gettingStarted/tutorials/building-lakehouse/doris-iceberg.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/gettingStarted/tutorials/building-lakehouse/doris-iceberg.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/gettingStarted/tutorials/building-lakehouse/doris-iceberg.md
versioned_docs/version-2.0/gettingStarted/tutorials/building-lakehouse/doris-iceberg.md
versioned_docs/version-2.1/gettingStarted/tutorials/building-lakehouse/doris-iceberg.md
versioned_docs/version-3.0/gettingStarted/tutorials/building-lakehouse/doris-iceberg.md

[iceberg] add pyiceberg doc for other branch

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/db-connect/arrow-flight-sql-connect.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/db-connect/arrow-flight-sql-connect.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/db-connect/arrow-flight-sql-connect.md

[doc] update arrow-flight-sql-connect.md markdown format

---

docs/data-operate/import/group-commit-manual.md
docs/data-operate/import/import-way/insert-into-values-manual.md
docs/data-operate/import/load-manual.md
docs/data-operate/transaction.md
docs/releasenotes/v2.1/release-2.1.0.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/group-commit-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/insert-into-values-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/transaction.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/group-commit-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/insert-into-values-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/transaction.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/group-commit-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/insert-into-values-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/transaction.md
sidebars.json
versioned_docs/version-2.1/data-operate/import/group-commit-manual.md
versioned_docs/version-2.1/data-operate/import/import-way/insert-into-values-manual.md
versioned_docs/version-2.1/data-operate/import/load-manual.md
versioned_docs/version-2.1/data-operate/transaction.md
versioned_docs/version-2.1/releasenotes/v2.1/release-2.1.0.md
versioned_docs/version-3.0/data-operate/import/group-commit-manual.md
versioned_docs/version-3.0/data-operate/import/import-way/insert-into-values-manual.md
versioned_docs/version-3.0/data-operate/import/load-manual.md
versioned_docs/version-3.0/data-operate/transaction.md
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

[doc](group-commit) Optimize the document of group commit

---

docs/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-STORAGE-VAULT.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-STORAGE-VAULT.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/storage-management/CREATE-STORAGE-VAULT.md
versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/storage-management/CREATE-STORAGE-VAULT.md

* `use_path_style` default vault from `false` to `true`

[opt] Modify storage vault `use_path_style` default behavior

---

docs/query-acceleration/performance-tuning-overview/analysis-tools.md
docs/query-acceleration/tuning/tuning-plan/adjusting-join-shuffle.md
docs/query-acceleration/tuning/tuning-plan/controlling-hints-with-cbo-rule.md
docs/query-acceleration/tuning/tuning-plan/dml-tuning-plan.md
docs/query-acceleration/tuning/tuning-plan/optimizing-join-with-colocate-group.md
docs/query-acceleration/tuning/tuning-plan/transparent-rewriting-with-async-mv.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/tuning-plan/optimizing-join-with-colocate-group.md

[Improvement](docs) refine query acceleration doc

---

docs/query-acceleration/optimization-technology-principle/pipeline-execution-engine.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/optimization-technology-principle/pipeline-execution-engine.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-acceleration/pipeline-execution-engine.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-acceleration/pipeline-execution-engine.md
versioned_docs/version-2.1/query-acceleration/pipeline-execution-engine.md
versioned_docs/version-3.0/query-acceleration/pipeline-execution-engine.md

- [ x] dev
- [ x] 3.0
- [ x] 2.1

small fix for pipeline execute engine

---

docs/admin-manual/data-admin/recyclebin.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/data-admin/recyclebin.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/data-admin/recyclebin.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/data-admin/recyclebin.md
sidebars.json
versioned_docs/version-2.1/admin-manual/data-admin/recyclebin.md
versioned_docs/version-3.0/admin-manual/data-admin/recyclebin.md
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

fix recover

---

i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/data-partitioning/data-distribution.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/data-partitioning/data-distribution.md
versioned_docs/version-2.1/table-design/data-partitioning/data-distribution.md
versioned_docs/version-3.0/table-design/data-partitioning/data-distribution.md
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

[fix] add data-distribution for 3.0 and 2.1

---

docs/lakehouse/filecache.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/filecache.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/filecache.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/filecache.md
versioned_docs/version-2.1/lakehouse/filecache.md
versioned_docs/version-3.0/lakehouse/filecache.md

[fix](filecache) fix data cache

---

i18n/zh-CN/docusaurus-plugin-content-docs/current.json
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/workload-management/compute-group.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/workload-management/compute-group.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/workload-management/compute-group.md
sidebars.json
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

update Workload management sidebar

---

docs/query-acceleration/hints/distribute-hint.md
docs/query-acceleration/hints/hints-overview.md
docs/query-acceleration/hints/leading-hint.md
docs/query-acceleration/tuning/tuning-plan/adjusting-join-shuffle.md
docs/query-acceleration/tuning/tuning-plan/controlling-hints-with-cbo-rule.md
docs/query-acceleration/tuning/tuning-plan/reordering-join-with-leading-hint.md

add English version of hints documents

---

i18n/zh-CN/docusaurus-plugin-content-docs/current.json
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1.json
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0.json

[fix] Business continuity & data recovery directory name in zh

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/workload-management/kill-query.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/workload-management/kill-query.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/workload-management/kill-query.md

refactor kill

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/workload-management/compute-group.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/workload-management/kill-query.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/workload-management/kill-query.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/workload-management/compute-group.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/workload-management/kill-query.md

fix some typo error according to AI

---

docs/admin-manual/workload-management/concurrency-control-and-queuing.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/workload-management/workload-group.md

concurrency control and queue

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/compilation-and-deployment.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/compute-storage-decoupled/compilation-and-deployment.md

[typo](doc) fix typo

---

docs/data-operate/import/import-way/insert-into-manual.md
docs/data-operate/import/import-way/insert-into-values-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/insert-into-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/insert-into-values-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/insert-into-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/insert-into-values-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/insert-into-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/insert-into-values-manual.md
versioned_docs/version-2.1/data-operate/import/import-way/insert-into-manual.md
versioned_docs/version-2.1/data-operate/import/import-way/insert-into-values-manual.md
versioned_docs/version-3.0/data-operate/import/import-way/insert-into-manual.md
versioned_docs/version-3.0/data-operate/import/import-way/insert-into-values-manual.md

[improve](docs) fix and improve insert into manual

---

docusaurus.config.js

chore:reduce the priority of docs v1.2

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/workload-management/sql-blocking.md

[docs]update policy

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/workload-management/workload-group.md

[docs]update workload group

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/install-quickstart.md
sidebars.json
versioned_sidebars/version-3.0-sidebars.json

[Doc](refactor)update sequence

---

docs/admin-manual/workload-management/resource-group.md
versioned_docs/version-2.1/admin-manual/workload-management/resource-group.md
versioned_docs/version-3.0/admin-manual/workload-management/resource-group.md

refine rg en doc

---

docs/query-data/window-function.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query-data/window-function.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-data/window-function.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-data/window-function.md
versioned_docs/version-2.1/query-data/window-function.md
versioned_docs/version-3.0/query-data/window-function.md

[fix] make create table and load data procedure easily

---

docs/admin-manual/workload-management/compute-group.md
versioned_docs/version-3.0/admin-manual/workload-management/compute-group.md

refine compute group en docs

---

docs/admin-manual/workload-management/job-scheduler.md
docs/admin-manual/workload-management/sql-blocking.md
sidebars.json
versioned_docs/version-2.1/admin-manual/workload-management/job-scheduler.md
versioned_docs/version-2.1/admin-manual/workload-management/sql-blocking.md
versioned_docs/version-3.0/admin-manual/workload-management/job-scheduler.md
versioned_docs/version-3.0/admin-manual/workload-management/sql-blocking.md
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

update sql-block and job-scheduler for en

---

sidebars.json
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

update Import sidebar

---

sidebars.json
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

Import sidebar

---

docs/data-operate/import/load-data-convert.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/load-data-convert.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/load-data-convert.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/load-data-convert.md
versioned_docs/version-2.1/data-operate/import/load-data-convert.md
versioned_docs/version-3.0/data-operate/import/load-data-convert.md

[doc](load) optimize load transform

---

docs/data-operate/import/load-data-convert.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/load-data-convert.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/load-data-convert.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/load-data-convert.md
versioned_docs/version-2.1/data-operate/import/load-data-convert.md
versioned_docs/version-3.0/data-operate/import/load-data-convert.md

[doc](load) fix some typo for data transform

---

docs/query-acceleration/optimization-technology-principle/statistics.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/optimization-technology-principle/statistics.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-acceleration/optimization-technology-principle/statistics.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-acceleration/optimization-technology-principle/statistics.md
versioned_docs/version-2.1/query-acceleration/optimization-technology-principle/statistics.md
versioned_docs/version-3.0/query-acceleration/optimization-technology-principle/statistics.md

Update statistics doc

---

docs/admin-manual/workload-management/kill-query.md
versioned_docs/version-2.1/admin-manual/workload-management/kill-query.md
versioned_docs/version-3.0/admin-manual/workload-management/kill-query.md

change kill query docs

---

community/subscribe-mail-list.md
i18n/zh-CN/docusaurus-plugin-content-docs-community/current/subscribe-mail-list.md

update unsubscribe mail list

---

docs/sql-manual/sql-functions/date-time-functions/date-add.md
docs/sql-manual/sql-functions/date-time-functions/date-sub.md
docs/sql-manual/sql-functions/date-time-functions/quarters-add.md
docs/sql-manual/sql-functions/date-time-functions/quarters-sub.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/date-time-functions/date-add.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/date-time-functions/quarters-add.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/date-time-functions/quarters-sub.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/date-time-functions/date-add.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/date-time-functions/date-sub.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/date-time-functions/quarters-add.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/date-time-functions/quarters-sub.md
sidebars.json
versioned_docs/version-3.0/sql-manual/sql-functions/date-time-functions/date-add.md
versioned_docs/version-3.0/sql-manual/sql-functions/date-time-functions/date-sub.md
versioned_docs/version-3.0/sql-manual/sql-functions/date-time-functions/quarters-add.md
versioned_docs/version-3.0/sql-manual/sql-functions/date-time-functions/quarters-sub.md
versioned_sidebars/version-3.0-sidebars.json

pr: https://github.com/apache/doris/pull/45370

[Feature](function) Support function quarters_add/sub for nereids

---

docs/lakehouse/database/postgresql.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/database/postgresql.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/database/postgresql.md
versioned_docs/version-3.0/lakehouse/database/postgresql.md

add postgresql catalog array type doc

---

docs/ecosystem/doris-kafka-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/doris-kafka-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/ecosystem/doris-kafka-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/doris-kafka-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/ecosystem/doris-kafka-connector.md
versioned_docs/version-2.0/ecosystem/doris-kafka-connector.md
versioned_docs/version-2.1/ecosystem/doris-kafka-connector.md
versioned_docs/version-3.0/ecosystem/doris-kafka-connector.md

- [ ☑️] dev
- [ ☑️]3.0
- [ ☑️] 2.1
- [ ☑️] 2.0
- [ ☑️] Chinese
- [ ☑️] English

[ecosystem]Improve kafka synchronization json best practices

---

sidebars.json
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

update sidebar for table-design

---

docs/lakehouse/datalake-analytics/dlf.md
docs/lakehouse/datalake-analytics/hive.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/datalake-analytics/dlf.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/datalake-analytics/hive.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/datalake-analytics/dlf.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/datalake-analytics/hive.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/datalake-analytics/dlf.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/datalake-analytics/hive.md
versioned_docs/version-2.1/lakehouse/datalake-analytics/dlf.md
versioned_docs/version-2.1/lakehouse/datalake-analytics/hive.md
versioned_docs/version-3.0/lakehouse/datalake-analytics/dlf.md
versioned_docs/version-3.0/lakehouse/datalake-analytics/hive.md

[opt](hive) add oss-hdfs example

---

sidebars.json
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

update Security sidebar - delete security from admin-manual

---

src/theme/Admonition/Layout/styles.module.css

[fix]:Remove marin-bottom from nested child elements

---

.github/workflows/manual-deploy-website.yml

set search-index.json catch-control max-age to zero

set search-index.json catch-control max-age to zero

---

docs/table-design/index/inverted-index.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/index/inverted-index.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/table-design/index/inverted-index.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/index/inverted-index.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/index/inverted-index.md
versioned_docs/version-2.0/table-design/index/inverted-index.md
versioned_docs/version-2.1/table-design/index/inverted-index.md
versioned_docs/version-3.0/table-design/index/inverted-index.md

Update the description of the usage of match_phrase_prefix.

---

src/theme/SearchBar/searchByWorker.js

[fix]:add timestamp to load workerjs

---

docs/data-operate/import/load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/load-manual.md
versioned_docs/version-2.1/data-operate/import/load-manual.md
versioned_docs/version-3.0/data-operate/import/load-manual.md

[doc](load) fix load manual

---

docs/data-operate/import/data-source/migrate-data-from-other-olap.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/migrate-data-from-other-olap.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/migrate-data-from-other-olap.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/migrate-data-from-other-olap.md
versioned_docs/version-2.1/data-operate/import/data-source/migrate-data-from-other-olap.md
versioned_docs/version-3.0/data-operate/import/data-source/migrate-data-from-other-olap.md

[doc](load) optimize migration from olap

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalog-overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/hive-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/iceberg-catalog.md

[fix](catalog) refine catalog doc

---

docs/lakehouse/catalog-overview.md
docs/lakehouse/catalogs/hive-catalog.md
docs/lakehouse/catalogs/hudi-catalog.md
docs/lakehouse/catalogs/iceberg-catalog.md
docs/lakehouse/catalogs/jdbc-catalog-overview.md
docs/lakehouse/catalogs/paimon-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current.json
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalog-overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/hive-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/hudi-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/jdbc-catalog-overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/paimon-catalog.md
sidebars.json

[opt](catalog) add english version for part of catalog docs

---

docs/lakehouse/best-practices/doris-hudi.md
docs/lakehouse/best-practices/doris-iceberg.md
docs/lakehouse/best-practices/doris-lakesoul.md
docs/lakehouse/best-practices/doris-paimon.md
docs/lakehouse/catalogs/hudi-catalog.md
docs/lakehouse/catalogs/iceberg-catalog.md
docs/lakehouse/catalogs/paimon-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/hudi-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/iceberg-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/lakesoul-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/paimon-catalog.md

[opt](lakehouse) update lakehouse doc

---

docs/data-operate/import/group-commit-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/group-commit-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/group-commit-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/group-commit-manual.md
versioned_docs/version-2.1/data-operate/import/group-commit-manual.md
versioned_docs/version-3.0/data-operate/import/group-commit-manual.md

[doc](load) optimize group commit

---

docs/admin-manual/auth/authentication/federation.md
docs/admin-manual/auth/authentication/internal.md
docs/admin-manual/auth/authorization/data.md
docs/admin-manual/auth/authorization/internal.md
docs/admin-manual/auth/authorization/ranger.md
i18n/zh-CN/docusaurus-plugin-content-docs/current.json
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/auth/authentication/federation.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/auth/authentication/internal.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/auth/authorization/data.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/auth/authorization/internal.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/auth/authorization/ranger.md
sidebars.json

[auth]Authentication and Authorization

---

docs/data-operate/import/group-commit-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/group-commit-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/group-commit-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/group-commit-manual.md
versioned_docs/version-2.1/data-operate/import/group-commit-manual.md
versioned_docs/version-3.0/data-operate/import/group-commit-manual.md

[doc](load) fix group commit

---

docs/data-operate/update/unique-update-concurrent-control.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/update/unique-update-concurrent-control.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/update/unique-update-concurrent-control.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/update/unique-update-concurrent-control.md
versioned_docs/version-2.1/data-operate/update/unique-update-concurrent-control.md
versioned_docs/version-3.0/data-operate/update/unique-update-concurrent-control.md

[doc](update) address comment of unique-update-concurrent-control

---

docs/data-operate/update/update-of-aggregate-model.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/update/update-of-aggregate-model.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/update/update-of-aggregate-model.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/update/update-of-aggregate-model.md
versioned_docs/version-2.1/data-operate/update/update-of-aggregate-model.md
versioned_docs/version-3.0/data-operate/update/update-of-aggregate-model.md

[doc](data update)Address comment on update of agg model and translate en doc by LLM

---

sidebars.json
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

update table-design sidebar

---

docs/data-operate/delete/truncate-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/delete/truncate-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/delete/truncate-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/delete/truncate-manual.md
versioned_docs/version-2.1/data-operate/delete/truncate-manual.md
versioned_docs/version-3.0/data-operate/delete/truncate-manual.md

[doc](trancate table) address comment and update english doc by LLM

---

docs/data-operate/import/import-way/routine-load-manual.md
docs/data-operate/import/import-way/stream-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/routine-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/stream-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/doris-streamloader.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/ecosystem/doris-streamloader.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/data-operate/import/stream-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/ecosystem/doris-streamloader.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/routine-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/stream-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/doris-streamloader.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/routine-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/stream-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/ecosystem/doris-streamloader.md
versioned_docs/version-2.0/data-operate/import/stream-load-manual.md
versioned_docs/version-2.1/data-operate/import/import-way/routine-load-manual.md
versioned_docs/version-3.0/data-operate/import/import-way/routine-load-manual.md

[doc](load) fix some error and refactor load doc

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/broker-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/broker-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/broker-load-manual.md

[improve](broker-load) reorder s3 providers in chinese docs

---

docs/data-operate/import/import-way/insert-into-manual.md
docs/data-operate/import/import-way/insert-into-values-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/insert-into-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/insert-into-values-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/insert-into-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/insert-into-values-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/insert-into-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/insert-into-values-manual.md
versioned_docs/version-2.1/data-operate/import/import-way/insert-into-manual.md
versioned_docs/version-2.1/data-operate/import/import-way/insert-into-values-manual.md
versioned_docs/version-3.0/data-operate/import/import-way/insert-into-manual.md
versioned_docs/version-3.0/data-operate/import/import-way/insert-into-values-manual.md

[docs](insert-into) reformat parameters in tables

---

i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-data/udf/java-user-defined-function.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-data/udf/java-user-defined-function.md
versioned_docs/version-2.1/query-data/udf/java-user-defined-function.md
versioned_docs/version-3.0/query-data/udf/java-user-defined-function.md

update java-udf for 2.1 & 3.0

---

docs/data-operate/import/import-way/broker-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/broker-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/broker-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/broker-load-manual.md
versioned_docs/version-2.1/data-operate/import/import-way/broker-load-manual.md
versioned_docs/version-3.0/data-operate/import/import-way/broker-load-manual.md

[docs](broker-load) remove `exec_mem_limit` property

---

docs/data-operate/import/import-way/broker-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/broker-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/broker-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/broker-load-manual.md
versioned_docs/version-2.1/data-operate/import/import-way/broker-load-manual.md
versioned_docs/version-3.0/data-operate/import/import-way/broker-load-manual.md

[docs](broker-load) explain broker load legacy usages

---

docs/sql-manual/sql-functions/aggregate-functions/percentile.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/percentile.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/aggregate-functions/percentile.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/aggregate-functions/percentile.md
versioned_docs/version-2.1/sql-manual/sql-functions/aggregate-functions/percentile.md
versioned_docs/version-3.0/sql-manual/sql-functions/aggregate-functions/percentile.md

[doc] Add sql function PERCENTILE SQL Manual

---

docs/compute-storage-decoupled/managing-storage-vault.md
docs/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-STORAGE-VAULT.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/managing-storage-vault.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-STORAGE-VAULT.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/compute-storage-decoupled/managing-storage-vault.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/storage-management/CREATE-STORAGE-VAULT.md
versioned_docs/version-3.0/compute-storage-decoupled/managing-storage-vault.md
versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/storage-management/CREATE-STORAGE-VAULT.md

[opt] Add more storage vault demo about different product

---

docs/data-operate/update/update-of-aggregate-model.md
versioned_docs/version-2.1/data-operate/update/update-of-aggregate-model.md
versioned_docs/version-3.0/data-operate/update/update-of-aggregate-model.md

[doc](update-of-agg-model) fix title error for en doc

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/json-functions/json-array.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/json-functions/json-array.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/json-functions/json-array.md

[doc] Fix json_array zh_doc

---

docs/data-operate/delete/delete-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/delete/delete-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/delete/delete-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/delete/delete-manual.md
versioned_docs/version-2.1/data-operate/delete/delete-manual.md
versioned_docs/version-3.0/data-operate/delete/delete-manual.md

[doc](delete manual) address comments and translate en doc by LLM

---

static/googlef7f149d83d332f5e.html

refer to  https://docusaurus.io/docs/static-assets

[build]:add static html for root directory

---

docs/sql-manual/sql-functions/table-valued-functions/backends.md
docs/sql-manual/sql-functions/table-valued-functions/frontends.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-valued-functions/backends.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-valued-functions/frontends.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/table-valued-functions/backends.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/table-valued-functions/frontends.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/table-valued-functions/backends.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/table-valued-functions/frontends.md
versioned_docs/version-2.1/sql-manual/sql-functions/table-valued-functions/backends.md
versioned_docs/version-2.1/sql-manual/sql-functions/table-valued-functions/frontends.md
versioned_docs/version-3.0/sql-manual/sql-functions/table-valued-functions/backends.md
versioned_docs/version-3.0/sql-manual/sql-functions/table-valued-functions/frontends.md

improve the article format of backends() and frontends() function

---

docs/sql-manual/sql-statements/data-modification/backup-and-restore/CREATE-REPOSITORY.md
docs/sql-manual/sql-statements/data-modification/backup-and-restore/DROP-REPOSITORY.md
docs/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-CREATE-REPOSITORY.md
docs/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-REPOSITORIES.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/backup-and-restore/CREATE-REPOSITORY.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/backup-and-restore/DROP-REPOSITORY.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-CREATE-REPOSITORY.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-REPOSITORIES.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/CREATE-REPOSITORY.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/DROP-REPOSITORY.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-CREATE-REPOSITORY.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-REPOSITORIES.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/CREATE-REPOSITORY.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/DROP-REPOSITORY.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-CREATE-REPOSITORY.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-REPOSITORIES.md
versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/CREATE-REPOSITORY.md
versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/DROP-REPOSITORY.md
versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-CREATE-REPOSITORY.md
versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-REPOSITORIES.md
versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/CREATE-REPOSITORY.md
versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/DROP-REPOSITORY.md
versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-CREATE-REPOSITORY.md
versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/SHOW-REPOSITORIES.md

```
CREATE REPOSITOR
DROP REPOSITORY
DROP REPOSITORY
SHOW REPOSITORIES
```

improve Backup and Restore Statements SQL Manual

---

community/source-install/compilation-with-ldb-toolchain.md
i18n/zh-CN/docusaurus-plugin-content-docs-community/current/source-install/compilation-with-ldb-toolchain.md

for our toolchain now, old bison is not usable. change to an available version.

[Fix](doc) fix Build docs with ldb toolchain

---

docs/lakehouse/catalogs/bigquery-catalog.md
docs/lakehouse/catalogs/delta-lake-catalog.md
docs/lakehouse/catalogs/jdbc-catalog-overview.md
docs/lakehouse/catalogs/jdbc-clickhouse-catalog.md
docs/lakehouse/catalogs/jdbc-ibmdb2-catalog.md
docs/lakehouse/catalogs/jdbc-mysql-catalog.md
docs/lakehouse/catalogs/jdbc-oceanbase-catalog.md
docs/lakehouse/catalogs/jdbc-oracle-catalog.md
docs/lakehouse/catalogs/jdbc-pg-catalog.md
docs/lakehouse/catalogs/jdbc-saphana-catalog.md
docs/lakehouse/catalogs/jdbc-sqlserver-catalog.md
docs/lakehouse/catalogs/kudu-catalog.md
docs/lakehouse/catalogs/lakesoul-catalog.md
docs/lakehouse/catalogs/maxcompute-catalog.md
docs/lakehouse/compute-node.md
docs/lakehouse/data-cache.md
docs/lakehouse/file-analysis.md
docs/lakehouse/meta-cache.md
docs/lakehouse/sql-convertor/sql-convertor-overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/bigquery-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/delta-lake-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/jdbc-catalog-overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/jdbc-mysql-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/kudu-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/lakesoul-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/maxcompute-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/data-cache.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/meta-cache.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/sql-convertor/sql-convertor-overview.md

[opt] add more lakehouse doc

---

docs/sql-manual/sql-statements/job/CREATE-JOB.md
docs/sql-manual/sql-statements/job/DROP-JOB.md
docs/sql-manual/sql-statements/job/PAUSE-JOB.md
docs/sql-manual/sql-statements/job/RESUME-JOB.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/job/CREATE-JOB.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/job/DROP-JOB.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/job/PAUSE-JOB.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/job/RESUME-JOB.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/job/CREATE-JOB.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/job/DROP-JOB.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/job/PAUSE-JOB.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/job/RESUME-JOB.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/job/CREATE-JOB.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/job/DROP-JOB.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/job/PAUSE-JOB.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/job/RESUME-JOB.md
versioned_docs/version-2.1/sql-manual/sql-statements/job/CREATE-JOB.md
versioned_docs/version-2.1/sql-manual/sql-statements/job/DROP-JOB.md
versioned_docs/version-2.1/sql-manual/sql-statements/job/PAUSE-JOB.md
versioned_docs/version-2.1/sql-manual/sql-statements/job/RESUME-JOB.md
versioned_docs/version-3.0/sql-manual/sql-statements/job/CREATE-JOB.md
versioned_docs/version-3.0/sql-manual/sql-statements/job/DROP-JOB.md
versioned_docs/version-3.0/sql-manual/sql-statements/job/PAUSE-JOB.md
versioned_docs/version-3.0/sql-manual/sql-statements/job/RESUME-JOB.md

[doc](job)Optimize the documentation of job related statements

---

docs/admin-manual/workload-management/workload-group.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/workload-management/workload-group.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/workload-management/workload-group.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/workload-management/workload-group.md
versioned_docs/version-2.1/admin-manual/workload-management/workload-group.md
versioned_docs/version-3.0/admin-manual/workload-management/workload-group.md

[docs]add faq for workload group

---

docs/sql-manual/sql-functions/scalar-functions/distance-functions/cosine-distance.md
docs/sql-manual/sql-functions/scalar-functions/distance-functions/inner-product.md
docs/sql-manual/sql-functions/scalar-functions/distance-functions/l1-distance.md
docs/sql-manual/sql-functions/scalar-functions/distance-functions/l2-distance.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/distance-functions/cosine-distance.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/distance-functions/inner-product.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/distance-functions/l1-distance.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/distance-functions/l2-distance.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/distance-functions/cosine-distance.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/distance-functions/inner-product.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/distance-functions/l1-distance.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/distance-functions/l2-distance.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/distance-functions/cosine-distance.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/distance-functions/inner-product.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/distance-functions/l1-distance.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/distance-functions/l2-distance.md
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/distance-functions/cosine-distance.md
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/distance-functions/inner-product.md
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/distance-functions/l1-distance.md
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/distance-functions/l2-distance.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/distance-functions/cosine-distance.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/distance-functions/inner-product.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/distance-functions/l1-distance.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/distance-functions/l2-distance.md

[Doc] Add vectorized functions

---

docs/sql-manual/sql-statements/function/DROP-FUNCTION.md
docs/sql-manual/sql-statements/function/SHOW-CREATE-FUNCTION.md
docs/sql-manual/sql-statements/function/SHOW-FUNCTIONS.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/function/DROP-FUNCTION.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/function/SHOW-CREATE-FUNCTION.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/function/SHOW-FUNCTIONS.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-reference/Data-Definition-Statements/Drop/DROP-FUNCTION.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-reference/Show-Statements/SHOW-CREATE-FUNCTION.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-reference/Show-Statements/SHOW-FUNCTIONS.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/function/DROP-FUNCTION.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/function/SHOW-CREATE-FUNCTION.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/function/SHOW-FUNCTIONS.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/function/DROP-FUNCTION.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/function/SHOW-CREATE-FUNCTION.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/function/SHOW-FUNCTIONS.md
versioned_docs/version-2.0/sql-manual/sql-reference/Data-Definition-Statements/Drop/DROP-FUNCTION.md
versioned_docs/version-2.0/sql-manual/sql-reference/Show-Statements/SHOW-CREATE-FUNCTION.md
versioned_docs/version-2.0/sql-manual/sql-reference/Show-Statements/SHOW-FUNCTIONS.md
versioned_docs/version-2.1/sql-manual/sql-statements/function/DROP-FUNCTION.md
versioned_docs/version-2.1/sql-manual/sql-statements/function/SHOW-CREATE-FUNCTION.md
versioned_docs/version-2.1/sql-manual/sql-statements/function/SHOW-FUNCTIONS.md
versioned_docs/version-3.0/sql-manual/sql-statements/function/DROP-FUNCTION.md
versioned_docs/version-3.0/sql-manual/sql-statements/function/SHOW-CREATE-FUNCTION.md
versioned_docs/version-3.0/sql-manual/sql-statements/function/SHOW-FUNCTIONS.md

- [ ✅] dev
- [ ✅] 3.0
- [ ✅] 2.1
- [ ✅] 2.0
- [ ✅] Chinese
- [ ✅] English
- [ ✅] Checked by AI

Function class management statement

---

docs/lakehouse/best-practices/tpcds.md
docs/lakehouse/best-practices/tpch.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/best-practices/tpcds.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/best-practices/tpch.md
sidebars.json

[lakehouse] add tpc doc

---

docusaurus.config.js
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/admin-manual/maint-monitor/metadata-operation.md

refer to: https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-gtag
#1928

chore:remove google analytics

---

config/custom-docusaurus-plugin.js
config/ssrTemplate.js
docusaurus.config.js
src/pages/_download/index.tsx
src/theme/SearchBar/searchByWorker.js

chore:remove cdnd

---

docusaurus.config.js
yarn.lock

See https://github.com/apache/doris-website/issues/1928

Remove Google Analytics from the Doris Website - fixes #1928

---

docs/lakehouse/file-formats/text.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/file-formats/text.md

[file-format] add enable_text_validate_utf8 doc

---

docs/lakehouse/catalogs/iceberg-catalog.md
docs/lakehouse/catalogs/paimon-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/iceberg-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/paimon-catalog.md

[lakehouse] update iceberg and paimon

---

docs/sql-manual/sql-statements/table-and-view/view/ALTER-VIEW.md
docs/sql-manual/sql-statements/table-and-view/view/CREATE-VIEW.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/view/ALTER-VIEW.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/view/CREATE-VIEW.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/view/ALTER-VIEW.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/view/CREATE-VIEW.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/view/ALTER-VIEW.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/view/CREATE-VIEW.md
versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/view/ALTER-VIEW.md
versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/view/CREATE-VIEW.md
versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/view/ALTER-VIEW.md
versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/view/CREATE-VIEW.md

[doc] update view statement

---

docs/sql-manual/sql-statements/session/context/SWITCH-CATALOG.md
docs/sql-manual/sql-statements/session/context/USE-DATABASE.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/session/context/SWITCH-CATALOG.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/session/context/USE-DATABASE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/session/context/SWITCH-CATALOG.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/session/context/USE-DATABASE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/lakehouse-overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/session/context/SWITCH-CATALOG.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/session/context/USE-DATABASE.md
versioned_docs/version-2.1/sql-manual/sql-statements/session/context/SWITCH-CATALOG.md
versioned_docs/version-2.1/sql-manual/sql-statements/session/context/USE-DATABASE.md
versioned_docs/version-3.0/sql-manual/sql-statements/session/context/SWITCH-CATALOG.md
versioned_docs/version-3.0/sql-manual/sql-statements/session/context/USE-DATABASE.md

[doc] update fresh context statement

---

i18n/zh-CN/docusaurus-plugin-content-docs/current.json
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1.json
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0.json

[fix](doc)modify EN to CN path json description

---

docs/lakehouse/catalogs/iceberg-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/iceberg-catalog.md

[fix](iceberg) add sql hint

---

docs/sql-manual/sql-statements/recycle/DROP-CATALOG-RECYCLE-BIN.md
docs/sql-manual/sql-statements/recycle/RECOVER.md
docs/sql-manual/sql-statements/recycle/SHOW-CATALOG-RECYCLE-BIN.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/recycle/DROP-CATALOG-RECYCLE-BIN.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/recycle/RECOVER.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/recycle/SHOW-CATALOG-RECYCLE-BIN.md

[doc] update recycle statement

---

docs/sql-manual/sql-functions/scalar-functions/date-time-functions/minute-ceil.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/minute-ceil.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/minute-ceil.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/minute-ceil.md
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/minute-ceil.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/minute-ceil.md

[Doc] Fix `minute-ceil` function zh document url error

---

docs/sql-manual/sql-statements/session/queries/CLEAN-ALL-PROFILE.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/session/queries/CLEAN-ALL-PROFILE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/session/query/CLEAN-ALL-PROFILE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/session/queries/CLEAN-ALL-PROFILE.md
versioned_docs/version-2.1/sql-manual/sql-statements/session/query/CLEAN-ALL-PROFILE.md
versioned_docs/version-3.0/sql-manual/sql-statements/session/queries/CLEAN-ALL-PROFILE.md

- [ ✅] dev
- [ ✅] 3.0
- [ ✅] 2.1
- [ ✅] Chinese
- [ ✅] English
- [ ✅] Checked by AI

change file for clean profile

---

sidebars.json
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

Manage disater recovery sidebar - typo

---

docs/sql-manual/sql-functions/scalar-functions/array-functions/array-flatten.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/array-functions/array-flatten.md

adjust doc of array flatten

---

i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/encrypt-digest-functions/aes-decrypt.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/encrypt-digest-functions/aes-encrypt.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/encrypt-digest-functions/sm4-decrypt.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/encrypt-digest-functions/sm4-encrypt.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/encrypt-digest-functions/aes-decrypt.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/encrypt-digest-functions/aes-encrypt.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/encrypt-digest-functions/sm4-decrypt.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/encrypt-digest-functions/sm4-encrypt.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/encrypt-digest-functions/aes-decrypt.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/encrypt-digest-functions/aes-encrypt.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/encrypt-digest-functions/sm4-decrypt.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/encrypt-digest-functions/sm4-encrypt.md
versioned_docs/version-2.0/sql-manual/sql-functions/encrypt-digest-functions/aes-decrypt.md
versioned_docs/version-2.0/sql-manual/sql-functions/encrypt-digest-functions/aes-encrypt.md
versioned_docs/version-2.0/sql-manual/sql-functions/encrypt-digest-functions/sm4-decrypt.md
versioned_docs/version-2.0/sql-manual/sql-functions/encrypt-digest-functions/sm4-encrypt.md
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/encrypt-digest-functions/aes-decrypt.md
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/encrypt-digest-functions/aes-encrypt.md
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/encrypt-digest-functions/sm4-decrypt.md
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/encrypt-digest-functions/sm4-encrypt.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/encrypt-digest-functions/aes-decrypt.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/encrypt-digest-functions/aes-encrypt.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/encrypt-digest-functions/sm4-decrypt.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/encrypt-digest-functions/sm4-encrypt.md

which removed in https://github.com/apache/doris-website/pull/1463

Fix lost extremely important warnings

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/benchmark/ssb.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/benchmark/tpcds.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/benchmark/tpch.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/benchmark/ssb.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/benchmark/tpcds.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/benchmark/tpch.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/benchmark/ssb.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/benchmark/tpcds.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/benchmark/tpch.md

update benchmark typo

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/jdbc-catalog-overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/maxcompute-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/cloud-auth.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/database/clickhouse.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/database/max-compute.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/database/mysql.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/database/oracle.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/database/sap-hana.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/database/sqlserver.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/datalake-analytics/hive.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/datalake-analytics/paimon.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/datalake-building/hive-build.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/filecache.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/sql-dialect.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/cloud-auth.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/database/clickhouse.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/database/max-compute.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/database/mysql.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/database/oracle.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/database/sqlserver.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/datalake-analytics/hive.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/datalake-analytics/lakesoul.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/datalake-analytics/paimon.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/datalake-building/hive-build.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/filecache.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/sql-dialect.md
versioned_docs/version-2.1/lakehouse/datalake-analytics/hive.md
versioned_docs/version-3.0/lakehouse/datalake-analytics/hive.md

update lakehouse typo

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/db-connect/arrow-flight-sql-connect.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/db-connect/database-connect.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/db-connect/arrow-flight-sql-connect.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/db-connect/database-connect.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/db-connect/arrow-flight-sql-connect.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/db-connect/database-connect.md

update db-connect typo

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/install/cluster-deployment/k8s-deploy/compute-storage-coupled/access-cluster.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-config-cluster.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/config-fe.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/config-ms.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/install-fdb.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/install-quickstart.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/install/deploy-manually/storage-compute-decoupled-deploy-manually.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/cluster-deployment/k8s-deploy/access-cluster.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/cluster-deployment/k8s-deploy/install-config-cluster.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/cluster-deployment/k8s-deploy/install-doris-operator.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-coupled/access-cluster.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-coupled/install-config-cluster.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/config-fe.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/config-ms.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/install-fdb.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/cluster-deployment/k8s-deploy/compute-storage-decoupled/install-quickstart.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/deploy-manually/storage-compute-decoupled-deploy-manually.md

update installation typo

---

docs/gettingStarted/quick-start.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/gettingStarted/what-is-apache-doris.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/gettingStarted/what-is-apache-doris.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/gettingStarted/what-is-apache-doris.md
versioned_docs/version-2.1/gettingStarted/quick-start.md
versioned_docs/version-3.0/gettingStarted/quick-start.md

update getting started typo

---

docs/admin-manual/data-admin/ccr/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/data-admin/ccr/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/data-admin/ccr/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/data-admin/ccr/overview.md
versioned_docs/version-2.1/admin-manual/data-admin/ccr/overview.md
versioned_docs/version-3.0/admin-manual/data-admin/ccr/overview.md

Add CCR download addresses

---

docs/lakehouse/statistics.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/statistics.md

[lakehouse] add statistic doc

---

check_docs_version_diff.py

add check version diff tools

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/hive-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/datalake-building/hive-build.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/datalake-building/hive-build.md

fix some spelling errors

---

docs/admin-manual/cluster-management/load-balancing.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/cluster-management/load-balancing.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/cluster-management/load-balancing.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/cluster-management/load-balancing.md
versioned_docs/version-2.1/admin-manual/cluster-management/load-balancing.md
versioned_docs/version-3.0/admin-manual/cluster-management/load-balancing.md

[load-balance] opt the load balance doc

---

docs/ecosystem/doris-operator/doris-operator-overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/doris-operator/doris-operator-overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/doris-operator/doris-operator-overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/ecosystem/doris-operator/doris-operator-overview.md
versioned_docs/version-2.1/ecosystem/doris-operator/doris-operator-overview.md
versioned_docs/version-3.0/ecosystem/doris-operator/doris-operator-overview.md

[k8s](docs)Fix spelling errors

---

docs/data-operate/export/export-overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/export/export-overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/export/export-overview.md
versioned_docs/version-3.0/data-operate/export/export-overview.md

related pr: https://github.com/apache/doris/pull/44041

[fix](doc) update export-overview docs

---

modify-deadlink.py

update check tools

---

docs/sql-manual/sql-statements/data-modification/DML/INSERT.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/DML/INSERT.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/DML/INSERT.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/DML/INSERT.md
versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/DML/INSERT.md
versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/DML/INSERT.md

[docs](insert) Add removed insert_timeout description to 2.1\3.0\master

---

docs/sql-manual/sql-functions/scalar-functions/numeric-functions/normal-cdf.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/normal-cdf.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/normal-cdf.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/normal-cdf.md
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/normal-cdf.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/normal-cdf.md

[doc]add normal_cdf function

---

docs/install/deploy-manually/storage-compute-coupled-deploy-manually.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/install/deploy-manually/storage-compute-coupled-deploy-manually.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/deploy-manually/storage-compute-coupled-deploy-manually.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/deploy-manually/storage-compute-coupled-deploy-manually.md
versioned_docs/version-2.1/install/deploy-manually/storage-compute-coupled-deploy-manually.md
versioned_docs/version-3.0/install/deploy-manually/storage-compute-coupled-deploy-manually.md

Installation - update java heap for be configuration

---

i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/recycle/RECOVER.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/recycle/SHOW-CATALOG-RECYCLE-BIN.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/recycle/DROP-CATALOG-RECYCLE-BIN.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/recycle/RECOVER.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/recycle/SHOW-CATALOG-RECYCLE-BIN.md
versioned_docs/version-2.1/sql-manual/sql-statements/recycle/RECOVER.md
versioned_docs/version-2.1/sql-manual/sql-statements/recycle/SHOW-CATALOG-RECYCLE-BIN.md
versioned_docs/version-3.0/sql-manual/sql-statements/recycle/DROP-CATALOG-RECYCLE-BIN.md
versioned_docs/version-3.0/sql-manual/sql-statements/recycle/RECOVER.md
versioned_docs/version-3.0/sql-manual/sql-statements/recycle/SHOW-CATALOG-RECYCLE-BIN.md

[doc] update recycle statement for v3.0 and v2.1

---

src/components/newsletter-swiper/index.tsx
src/pages/index.tsx
src/theme/Layout/index.tsx

In this PR: Resolved dublicate key and key not passed warning also extra import which were not used remove.

---

docs/sql-manual/sql-statements/cluster-management/storage-management/SHOW-STORAGE-POLICY.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/cluster-management/storage-management/SHOW-STORAGE-POLICY.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/cluster-management/storage-management/SHOW STORAGE POLICY.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/storage-management/SHOW-STORAGE-POLICY.md
versioned_docs/version-2.1/sql-manual/sql-statements/cluster-management/storage-management/SHOW-STORAGE-POLICY.md
versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/storage-management/SHOW-STORAGE-POLICY.md

[improve](stoarge-policy)Add a storage policy statement with a usage description.

---

docs/lakehouse/catalogs/delta-lake-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/delta-lake-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/datalake-analytics/deltalake.md
versioned_docs/version-3.0/lakehouse/datalake-analytics/deltalake.md

[fix](DeltaLake) add hdfs link in the `deltaCatalog` docs

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/be-vlog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/check-rpc-channel.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/check-tablet-segment.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/checksum.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/compaction-run.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/compaction-status.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/config.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/download.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/health.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/meta.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/metrics.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/pad-rowset.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/reset-rpc-channel.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/snapshot.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/tablet-distribution.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/tablet-info.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/tablet-migration.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/tablet-reload.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/tablet-restore.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/version-info.md

【DOC】update be-http docs

---

docs/table-design/index/inverted-index.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/index/inverted-index.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/index/inverted-index.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/index/inverted-index.md
versioned_docs/version-2.1/table-design/index/inverted-index.md
versioned_docs/version-3.0/table-design/index/inverted-index.md

fix : fix format of inverted index

---

blog/arrow-flight-sql-in-apache-doris-for-10x-faster-data-transfer.md
docs/db-connect/arrow-flight-sql-connect.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/trouble-shooting/memory-management/memory-analysis/doris-cache-memory-analysis.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/trouble-shooting/memory-management/memory-analysis/jemalloc-memory-analysis.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/db-connect/arrow-flight-sql-connect.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/db-connect/arrow-flight-sql-connect.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/db-connect/arrow-flight-sql-connect.md
versioned_docs/version-2.1/db-connect/arrow-flight-sql-connect.md
versioned_docs/version-3.0/db-connect/arrow-flight-sql-connect.md

[fix] Fix memory and arrow flight

---

docs/table-design/auto-increment.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/auto-increment.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/auto-increment.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/auto-increment.md
versioned_docs/version-2.1/table-design/auto-increment.md
versioned_docs/version-3.0/table-design/auto-increment.md

fix : fix format of auto increment

---

docs/sql-manual/sql-statements/cluster-management/storage-management/CREATE-STORAGE-VAULT.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/cluster-management/storage-management/CREATE-STORAGE-VAULT.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/storage-management/CREATE-STORAGE-VAULT.md
versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/storage-management/CREATE-STORAGE-VAULT.md

[opt] Add `note` for creating storage vault with GCP

---

docs/data-operate/import/complex-types/bitmap.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/complex-types/bitmap.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/complex-types/bitmap.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/complex-types/bitmap.md
versioned_docs/version-2.1/data-operate/import/complex-types/bitmap.md
versioned_docs/version-3.0/data-operate/import/complex-types/bitmap.md

[docs](bitmap) add example of bitmap_from_string and bitmap_from_array

---

docs/lakehouse/catalogs/hudi-catalog.md
docs/lakehouse/catalogs/maxcompute-catalog.md
docs/lakehouse/metastores/hive-metastore.md
docs/lakehouse/metastores/iceberg-rest.md
docs/lakehouse/storages/aliyun-oss.md
docs/lakehouse/storages/hdfs.md
docs/lakehouse/storages/huawei-obs.md
docs/lakehouse/storages/tencent-cos.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/hudi-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/maxcompute-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/metastores/hive-metastore.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/metastores/iceberg-rest.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/storages/aliyun-oss.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/storages/hdfs.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/storages/huawei-obs.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/storages/tencent-cos.md

[lakhouse] add and modify properties doc

---

docs/ecosystem/flink-doris-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/flink-doris-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/flink-doris-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/ecosystem/flink-doris-connector.md
versioned_docs/version-2.1/ecosystem/flink-doris-connector.md
versioned_docs/version-3.0/ecosystem/flink-doris-connector.md

[doc] update flink connector doc

---

docs/sql-manual/sql-functions/scalar-functions/date-time-functions/year-of-week.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/year-of-week.md

add document of year of week

---

docs/db-connect/arrow-flight-sql-connect.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/db-connect/arrow-flight-sql-connect.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/db-connect/arrow-flight-sql-connect.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/db-connect/arrow-flight-sql-connect.md
versioned_docs/version-2.1/db-connect/arrow-flight-sql-connect.md
versioned_docs/version-3.0/db-connect/arrow-flight-sql-connect.md

[fix] arrow flight

---

docs/data-operate/import/load-data-convert.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/load-data-convert.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/load-data-convert.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/load-data-convert.md
versioned_docs/version-2.1/data-operate/import/load-data-convert.md
versioned_docs/version-3.0/data-operate/import/load-data-convert.md

[doc](load) optimize Pre-filtering doc

---

docs/data-operate/import/file-format/json.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/file-format/json.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/file-format/json.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/file-format/json.md
versioned_docs/version-2.1/data-operate/import/file-format/json.md
versioned_docs/version-3.0/data-operate/import/file-format/json.md

[update](load) json compress format

---

docs/lakehouse/catalogs/jdbc-oracle-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/jdbc-oracle-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/lakehouse/database/oracle.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/database/oracle.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/database/oracle.md
versioned_docs/version-2.0/lakehouse/database/oracle.md
versioned_docs/version-2.1/lakehouse/database/oracle.md
versioned_docs/version-3.0/lakehouse/database/oracle.md

oracle jdbc catalog rac-ons port description

---

docs/table-design/data-model/unique.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/data-model/unique.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/data-model/unique.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/data-model/unique.md
versioned_docs/version-2.1/table-design/data-model/unique.md
versioned_docs/version-3.0/table-design/data-model/unique.md

Table design - update unique key table 

---

docs/data-operate/import/group-commit-manual.md
docs/db-connect/database-connect.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/group-commit-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/db-connect/database-connect.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/group-commit-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/db-connect/database-connect.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/group-commit-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/db-connect/database-connect.md
versioned_docs/version-2.1/data-operate/import/group-commit-manual.md
versioned_docs/version-2.1/db-connect/database-connect.md
versioned_docs/version-3.0/data-operate/import/group-commit-manual.md
versioned_docs/version-3.0/db-connect/database-connect.md

[fix](jdbc) fix jdbc url session variables

---

docs/data-operate/update/update-of-unique-model.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/update/update-of-unique-model.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/data-operate/update/update-of-unique-model.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/update/update-of-unique-model.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/update/update-of-unique-model.md
versioned_docs/version-2.0/data-operate/update/update-of-unique-model.md
versioned_docs/version-2.1/data-operate/update/update-of-unique-model.md
versioned_docs/version-3.0/data-operate/update/update-of-unique-model.md

[Doc](partial update) update doc for partial update

---

docs/query-acceleration/performance-tuning-overview/analysis-tools.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/performance-tuning-overview/analysis-tools.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-acceleration/performance-tuning-overview/analysis-tools.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-acceleration/performance-tuning-overview/analysis-tools.md
versioned_docs/version-2.1/query-acceleration/performance-tuning-overview/analysis-tools.md
versioned_docs/version-3.0/query-acceleration/performance-tuning-overview/analysis-tools.md

[fix]Fixed formatting issues in Analysis Tools documentation

---

docs/query-acceleration/materialized-view/sync-materialized-view.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/materialized-view/sync-materialized-view.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-acceleration/materialized-view/sync-materialized-view.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-acceleration/materialized-view/sync-materialized-view.md
versioned_docs/version-2.1/query-acceleration/materialized-view/sync-materialized-view.md
versioned_docs/version-3.0/query-acceleration/materialized-view/sync-materialized-view.md

[fix]Fixed formatting issues in Sync Materialized View documentation

---

docs/sql-manual/sql-functions/scalar-functions/date-time-functions/date-trunc.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/date-trunc.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/date-trunc.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-trunc.md
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/date-trunc.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-trunc.md

Add DATE_TRUNC(<time_unit>, <datetime>)

---

docs/admin-manual/log-management/be-log.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/log-management/be-log.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/log-management/be-log.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/log-management/be-log.md
versioned_docs/version-2.1/admin-manual/log-management/be-log.md
versioned_docs/version-3.0/admin-manual/log-management/be-log.md

[docs](be-log) add description for sys_log_verbose_flags_v

---

docs/install/deploy-manually/integrated-storage-compute-deploy-manually.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/install/deploy-manually/integrated-storage-compute-deploy-manually.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/deploy-manually/integrated-storage-compute-deploy-manually.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/deploy-manually/integrated-storage-compute-deploy-manually.md
versioned_docs/version-2.1/install/deploy-manually/integrated-storage-compute-deploy-manually.md
versioned_docs/version-3.0/install/deploy-manually/integrated-storage-compute-deploy-manually.md

Fix the soft link error in the document

---

docs/faq/routineload-faq.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/faq/routineload-faq.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/faq/routineload-faq.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/faq/routineload-faq.md
sidebars.json
versioned_docs/version-2.1/faq/routineload-faq.md
versioned_docs/version-3.0/faq/routineload-faq.md
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

[doc](load) add routine load FAQ

---

src/theme/TOC/index.tsx

fix:remove toc items in blog page

---

docs/faq/lakehouse-faq.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/faq/lakehouse-faq.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/faq/lakehouse-faq.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/faq/lakehouse-faq.md
versioned_docs/version-2.1/faq/lakehouse-faq.md
versioned_docs/version-3.0/faq/lakehouse-faq.md

[doc] permission issues when adding and inserting data into Hive. 

---

docs/lakehouse/catalogs/paimon-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/paimon-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/datalake-analytics/paimon.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/datalake-analytics/paimon.md
versioned_docs/version-2.1/lakehouse/datalake-analytics/paimon.md
versioned_docs/version-3.0/lakehouse/datalake-analytics/paimon.md

[doc]add examples for paimon on gcs

---

docs/ecosystem/flink-doris-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/flink-doris-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/flink-doris-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/ecosystem/flink-doris-connector.md
versioned_docs/version-2.1/ecosystem/flink-doris-connector.md
versioned_docs/version-3.0/ecosystem/flink-doris-connector.md

[doc](flink) Update flink doc

---

i18n/zh-CN/docusaurus-plugin-content-docs-community/current/source-install/compilation-arm.mdx
i18n/zh-CN/docusaurus-plugin-content-docs-community/current/source-install/compilation-linux.md
i18n/zh-CN/docusaurus-plugin-content-docs-community/current/source-install/compilation-with-docker.md
i18n/zh-CN/docusaurus-plugin-content-docs-community/current/source-install/compilation-with-ldb-toolchain.md

modify the community web page, in source-install dir
i18n/zh-CN/docusaurus-plugin-content-docs-community/current/source-install

add install jdk17 if compile doris 3.0+ or master branch

---

docs/data-operate/import/load-best-practices.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/load-best-practices.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/load-best-practices.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/load-best-practices.md
sidebars.json
versioned_docs/version-2.1/data-operate/import/load-best-practices.md
versioned_docs/version-3.0/data-operate/import/load-best-practices.md
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

add load best practices

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/basic-element/sql-data-types/semi-structured/VARIANT.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/basic-element/sql-data-types/semi-structured/VARIANT.md
versioned_docs/version-2.1/sql-manual/basic-element/sql-data-types/semi-structured/VARIANT.md
versioned_docs/version-3.0/sql-manual/basic-element/sql-data-types/semi-structured/VARIANT.md

fix markdown in VARIANT.md

---

docs/data-operate/import/data-source/snowflake.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/snowflake.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/snowflake.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/snowflake.md
versioned_docs/version-2.1/data-operate/import/data-source/snowflake.md
versioned_docs/version-3.0/data-operate/import/data-source/snowflake.md

[load](datasource)  change title level for snowflake doc

---

docs/lakehouse/storages/aliyun-oss.md
docs/lakehouse/storages/hdfs.md
docs/lakehouse/storages/huawei-obs.md
docs/lakehouse/storages/s3.md
docs/lakehouse/storages/tencent-cos.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/storages/aliyun-oss.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/storages/hdfs.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/storages/huawei-obs.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/storages/s3.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/storages/tencent-cos.md

[opt](storage) add some storage faq and modify format

---

docs/sql-manual/sql-functions/aggregate-functions/hll-raw-agg.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/hll-raw-agg.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/aggregate-functions/hll-raw-agg.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/aggregate-functions/hll-raw-agg.md
versioned_docs/version-2.1/sql-manual/sql-functions/aggregate-functions/hll-raw-agg.md
versioned_docs/version-3.0/sql-manual/sql-functions/aggregate-functions/hll-raw-agg.md

[doc](function) update doc about hll_union/hll_raw_agg

---

docs/query-acceleration/dictionary.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/dictionary.md
sidebars.json

[docs] Support Dictionary

---

docs/data-operate/import/data-source/kafka.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/kafka.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/kafka.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/kafka.md
versioned_docs/version-2.1/data-operate/import/data-source/kafka.md
versioned_docs/version-3.0/data-operate/import/data-source/kafka.md

fix : fix format of data import

---

docs/admin-manual/workload-management/workload-group.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/workload-management/workload-group.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/workload-management/workload-group.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/workload-management/workload-group.md
versioned_docs/version-2.1/admin-manual/workload-management/workload-group.md
versioned_docs/version-3.0/admin-manual/workload-management/workload-group.md

[docs]add note for cpu_resource_limit

---

docs/ecosystem/bi/datagrip.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/bi/datagrip.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/ecosystem/bi/datagrip.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/ecosystem/bi/datagrip.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/bi/datagrip.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/ecosystem/bi/datagrip.md

issue：#2199
update references from DBeaver to DataGrip in datagrip.md

[fix](docs) update references from DBeaver to DataGrip

---

docusaurus.config.js
i18n/zh-CN/code.json
src/pages/events/index.tsx
src/theme/DocVersionBanner/index.tsx

[Feat]:support cn event

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/config/fe-config.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/config/fe-config.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/config/fe-config.md

[doc]Update some incorrect descriptions about fe-config

---

docs/compute-storage-decoupled/managing-storage-vault.md
docs/sql-manual/sql-statements/database/ALTER-DATABASE.md
docs/sql-manual/sql-statements/database/CREATE-DATABASE.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/managing-storage-vault.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/database/ALTER-DATABASE.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/database/CREATE-DATABASE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/compute-storage-decoupled/managing-storage-vault.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/database/ALTER-DATABASE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/database/CREATE-DATABASE.md
versioned_docs/version-3.0/compute-storage-decoupled/managing-storage-vault.md
versioned_docs/version-3.0/sql-manual/sql-statements/database/ALTER-DATABASE.md
versioned_docs/version-3.0/sql-manual/sql-statements/database/CREATE-DATABASE.md

[doc] Add docs for database storage vault
- [x ] Chinese
- [x ] English

[doc] Add docs for database storage vault

---

i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-governance/DROP-SQL_BLOCK_RULE.md

[fix]The Chinese document for drop SQL block rule is displayed in English

---

docs/ecosystem/flink-doris-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/flink-doris-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/flink-doris-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/ecosystem/flink-doris-connector.md
versioned_docs/version-2.1/ecosystem/flink-doris-connector.md
versioned_docs/version-3.0/ecosystem/flink-doris-connector.md

[ecosystem](flink) improve flink doc 

---

community/developer-guide/debug-tool.md
i18n/zh-CN/docusaurus-plugin-content-docs-community/current/developer-guide/debug-tool.md

[opt] memory debug tools

---

docs/table-design/index/ngram-bloomfilter-index.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/index/ngram-bloomfilter-index.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/table-design/index/ngram-bloomfilter-index.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/index/ngram-bloomfilter-index.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/index/ngram-bloomfilter-index.md
versioned_docs/version-2.0/table-design/index/ngram-bloomfilter-index.md
versioned_docs/version-2.1/table-design/index/ngram-bloomfilter-index.md
versioned_docs/version-3.0/table-design/index/ngram-bloomfilter-index.md

[Fix]Add necessary parameters for using n-gram bloomfilter index

---

docs/lakehouse/best-practices/doris-maxcompute.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/best-practices/doris-maxcompute.md
sidebars.json

[feat](maxcompute)add from maxcompute to doris best-practices.

---

docs/lakehouse/file-formats/text.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/file-formats/text.md

[feat](openx-json) add openx json doc

---

docs/data-operate/import/load-best-practices.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/load-best-practices.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/load-best-practices.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/load-best-practices.md
versioned_docs/version-2.1/data-operate/import/load-best-practices.md
versioned_docs/version-3.0/data-operate/import/load-best-practices.md

[opt](load) optimize the format for load best practices

---

docs/admin-manual/system-tables/information_schema/backend_active_tasks.md
docs/admin-manual/workload-management/sql-blocking.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/system-tables/information_schema/backend_active_tasks.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/workload-management/sql-blocking.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/system-tables/information_schema/backend_active_tasks.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/workload-management/sql-blocking.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/system-tables/information_schema/backend_active_tasks.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/workload-management/sql-blocking.md
versioned_docs/version-2.1/admin-manual/system-tables/information_schema/backend_active_tasks.md
versioned_docs/version-2.1/admin-manual/workload-management/sql-blocking.md
versioned_docs/version-3.0/admin-manual/system-tables/information_schema/backend_active_tasks.md
versioned_docs/version-3.0/admin-manual/workload-management/sql-blocking.md

[docs] fix some typo for workload management

---

docs/data-operate/import/data-source/bigquery.md
docs/data-operate/import/data-source/snowflake.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/bigquery.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/snowflake.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/bigquery.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/snowflake.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/bigquery.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/snowflake.md
versioned_docs/version-2.1/data-operate/import/data-source/bigquery.md
versioned_docs/version-2.1/data-operate/import/data-source/snowflake.md
versioned_docs/version-3.0/data-operate/import/data-source/bigquery.md
versioned_docs/version-3.0/data-operate/import/data-source/snowflake.md

[improve](datasource) update typo for datasource

---

docs/data-operate/import/load-best-practices.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/load-best-practices.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/load-best-practices.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/load-best-practices.md
versioned_docs/version-2.1/data-operate/import/load-best-practices.md
versioned_docs/version-3.0/data-operate/import/load-best-practices.md

[fix](load) fix the format of load best practices

---

docs/sql-manual/basic-element/sql-data-types/semi-structured/VARIANT.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/basic-element/sql-data-types/semi-structured/VARIANT.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/basic-element/sql-data-types/semi-structured/VARIANT.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/basic-element/sql-data-types/semi-structured/VARIANT.md
versioned_docs/version-2.1/sql-manual/basic-element/sql-data-types/semi-structured/VARIANT.md
versioned_docs/version-3.0/sql-manual/basic-element/sql-data-types/semi-structured/VARIANT.md

select variant fields recommendation

[variant] optimize description on some user cases

---

docs/data-operate/import/data-source/snowflake.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/snowflake.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/snowflake.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/snowflake.md
versioned_docs/version-2.1/data-operate/import/data-source/snowflake.md
versioned_docs/version-3.0/data-operate/import/data-source/snowflake.md

[doc](load) fix snowflake datasource style

---

i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/datalake-building/hive-build.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/datalake-building/iceberg-build.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/datalake-building/hive-build.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/datalake-building/iceberg-build.md
versioned_docs/version-2.1/lakehouse/datalake-building/hive-build.md
versioned_docs/version-2.1/lakehouse/datalake-building/iceberg-build.md
versioned_docs/version-3.0/lakehouse/datalake-building/hive-build.md
versioned_docs/version-3.0/lakehouse/datalake-building/iceberg-build.md

[opt](catalog) remove experimental for iceberg/hive

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/faq/load-faq.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/faq/load-faq.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/faq/load-faq.md

[fix](load) fix format of load FAQ

---

docs/query-acceleration/dictionary.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/dictionary.md

[Fix](dictionary) Fix wrong description in dictionary docs

---

docs/admin-manual/data-admin/ccr/overview.md
docs/admin-manual/data-admin/ccr/quickstart.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/data-admin/ccr/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/data-admin/ccr/quickstart.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/data-admin/ccr/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/data-admin/ccr/quickstart.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/data-admin/ccr/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/data-admin/ccr/quickstart.md
versioned_docs/version-2.1/admin-manual/data-admin/ccr/overview.md
versioned_docs/version-2.1/admin-manual/data-admin/ccr/quickstart.md
versioned_docs/version-3.0/admin-manual/data-admin/ccr/overview.md
versioned_docs/version-3.0/admin-manual/data-admin/ccr/quickstart.md

Fix ccr-syncer download address

---

docs/sql-manual/sql-functions/scalar-functions/string-functions/regexp-extract-all.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/string-functions/regexp-extract-all.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/string-functions/regexp/regexp-extract-all.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/string-functions/regexp/regexp-extract-all.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/regexp-extract-all.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/regexp-extract-all.md
versioned_docs/version-1.2/sql-manual/sql-functions/string-functions/regexp/regexp-extract-all.md
versioned_docs/version-2.0/sql-manual/sql-functions/string-functions/regexp/regexp-extract-all.md
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/regexp-extract-all.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/regexp-extract-all.md

fxi return type of REGEXP_EXTRACT_ALL

---

docs/query-acceleration/tuning/tuning-execution/parallelism-tuning.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/parallelism-tuning.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/tuning/tuning-execution/parallelism-tuning.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-acceleration/tuning/parallelism-tuning.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-acceleration/tuning/tuning-execution/parallelism-tuning.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-acceleration/tuning/parallelism-tuning.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-acceleration/tuning/tuning-execution/parallelism-tuning.md
versioned_docs/version-2.1/query-acceleration/tuning/parallelism-tuning.md
versioned_docs/version-2.1/query-acceleration/tuning/tuning-execution/parallelism-tuning.md
versioned_docs/version-3.0/query-acceleration/tuning/parallelism-tuning.md
versioned_docs/version-3.0/query-acceleration/tuning/tuning-execution/parallelism-tuning.md

[fix](execute) fix set var error

---

docs/lakehouse/meta-cache.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/meta-cache.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/metacache.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/metacache.md
versioned_docs/version-2.1/lakehouse/metacache.md
versioned_docs/version-3.0/lakehouse/metacache.md

[fix](meta-cache) fix wrong config name

---

package.json
yarn.lock

[perf]:boost document score when search hits title

---

docs/query-data/udf/java-user-defined-function.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query-data/udf/java-user-defined-function.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-data/udf/java-user-defined-function.md
versioned_docs/version-3.0/query-data/udf/java-user-defined-function.md

[doc](udf) support list/map basic class for array/map type

---

docs/lakehouse/meta-cache.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/meta-cache.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/metacache.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/metacache.md
versioned_docs/version-2.1/lakehouse/metacache.md
versioned_docs/version-3.0/lakehouse/metacache.md

[fix](catalog) remove use_meta_cache doc

---

docs/query-acceleration/high-concurrent-point-query.md
docs/table-design/row-store.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/high-concurrent-point-query.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/row-store.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-acceleration/high-concurrent-point-query.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/row-store.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-acceleration/high-concurrent-point-query.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/row-store.md
versioned_docs/version-2.1/query-acceleration/high-concurrent-point-query.md
versioned_docs/version-3.0/query-acceleration/high-concurrent-point-query.md
versioned_docs/version-3.0/table-design/row-store.md

correct `row_store_columns` version in doc

---

docs/admin-manual/data-admin/ccr/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/data-admin/ccr/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/data-admin/ccr/overview.md
versioned_docs/version-2.1/admin-manual/data-admin/ccr/overview.md
versioned_docs/version-3.0/admin-manual/data-admin/ccr/overview.md

update ccr binary addresses

---

docs/data-operate/import/data-source/flink.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/data-source/flink.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/flink.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/flink.md
versioned_docs/version-2.1/data-operate/import/data-source/flink.md
versioned_docs/version-3.0/data-operate/import/data-source/flink.md

fix : fix format of flink

---

docs/admin-manual/system-tables/internal_schema/audit_log.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/system-tables/internal_schema/audit_log.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/system-tables/internal_schema/audit_log.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/system-tables/internal_schema/audit_log.md
versioned_docs/version-2.1/admin-manual/system-tables/internal_schema/audit_log.md
versioned_docs/version-3.0/admin-manual/system-tables/internal_schema/audit_log.md

https://github.com/apache/doris/pull/42262
this pr remove trace_id in audit_log

[doc](audit_log) update audit_log about trace_id

---

docs/faq/lakehouse-faq.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/faq/lakehouse-faq.md

[opt](lh) add dfs.client.use.datanode.hostname doc

---

docs/lakehouse/meta-cache.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/meta-cache.md

[feat](meta-cache) add schema cache doc

---

docs/sql-manual/basic-element/sql-data-types/semi-structured/JSON.md
docs/sql-manual/basic-element/sql-data-types/semi-structured/VARIANT.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/basic-element/sql-data-types/semi-structured/JSON.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/basic-element/sql-data-types/semi-structured/VARIANT.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-data-types/semi-structured/JSON.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/basic-element/sql-data-types/semi-structured/JSON.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/basic-element/sql-data-types/semi-structured/VARIANT.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/basic-element/sql-data-types/semi-structured/JSON.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/basic-element/sql-data-types/semi-structured/VARIANT.md
versioned_docs/version-2.0/sql-manual/sql-data-types/semi-structured/JSON.md
versioned_docs/version-2.1/sql-manual/basic-element/sql-data-types/semi-structured/JSON.md
versioned_docs/version-2.1/sql-manual/basic-element/sql-data-types/semi-structured/VARIANT.md
versioned_docs/version-3.0/sql-manual/basic-element/sql-data-types/semi-structured/JSON.md
versioned_docs/version-3.0/sql-manual/basic-element/sql-data-types/semi-structured/VARIANT.md

Add FAQ for null value description in VARIANT and JSON type

---

docs/table-design/index/inverted-index.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/index/DROP-INDEX.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/index/inverted-index.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/table-design/index/inverted-index.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/index/DROP-INDEX.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/index/inverted-index.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/index/DROP-INDEX.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/index/inverted-index.md
versioned_docs/version-2.0/table-design/index/inverted-index.md
versioned_docs/version-2.1/table-design/index/inverted-index.md
versioned_docs/version-3.0/table-design/index/inverted-index.md

1. update match_regexp usage
2. add multi_match usage

Update inverted index docs for match_regexp and multi_match

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/basic-element/sql-data-types/semi-structured/JSON.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/basic-element/sql-data-types/semi-structured/VARIANT.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-data-types/semi-structured/JSON.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/basic-element/sql-data-types/semi-structured/JSON.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/basic-element/sql-data-types/semi-structured/VARIANT.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/basic-element/sql-data-types/semi-structured/JSON.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/basic-element/sql-data-types/semi-structured/VARIANT.md

format document introduce by #2396

---

docs/sql-manual/sql-functions/scalar-functions/array-functions/array-match-all.md
docs/sql-manual/sql-functions/scalar-functions/array-functions/array-match-any.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/array-functions/array-match-all.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/array-functions/array-match-any.md

[doc](array-match-all/any)fix docs for function array_match_all/any

---

docs/admin-manual/auth/integrations/aws-authentication-and-authorization.md
docs/compute-storage-decoupled/managing-storage-vault.md
docs/data-operate/import/data-source/amazon-s3.md
docs/sql-manual/sql-statements/cluster-management/compute-management/CREATE-RESOURCE.md
docs/sql-manual/sql-statements/cluster-management/storage-management/CREATE-STORAGE-VAULT.md
docs/sql-manual/sql-statements/data-modification/backup-and-restore/CREATE-REPOSITORY.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/auth/integrations/aws-authentication-and-authorization.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/managing-storage-vault.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/cluster-management/storage-management/CREATE-STORAGE-VAULT.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/backup-and-restore/CREATE-REPOSITORY.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/auth/integrations/aws-authentication-and-authorization.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/compute-storage-decoupled/managing-storage-vault.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/storage-management/CREATE-STORAGE-VAULT.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/CREATE-REPOSITORY.md
versioned_docs/version-3.0/admin-manual/auth/integrations/aws-authentication-and-authorization.md
versioned_docs/version-3.0/compute-storage-decoupled/managing-storage-vault.md
versioned_docs/version-3.0/data-operate/import/data-source/amazon-s3.md
versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/compute-management/CREATE-RESOURCE.md
versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/storage-management/CREATE-STORAGE-VAULT.md
versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/CREATE-REPOSITORY.md

[docs](vault) Add important `notes` for vault and aws iam role auth

---

blog/log-analysis-elasticsearch-vs-apache-doris.md
docs/log-storage-analysis.md
docs/observability/log.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/log-storage-analysis.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/observability/log-storage-analysis.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/observability/log.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/log-storage-analysis.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/log-storage-analysis.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/observability/log-storage-analysis.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/observability/log.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/log-storage-analysis.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/observability/log-storage-analysis.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/observability/log.md
versioned_docs/version-2.0/practical-guide/log-storage-analysis.md
versioned_docs/version-2.1/log-storage-analysis.md
versioned_docs/version-2.1/observability/log.md
versioned_docs/version-2.1/practical-guide/log-storage-analysis.md
versioned_docs/version-3.0/log-storage-analysis.md
versioned_docs/version-3.0/observability/log.md
versioned_docs/version-3.0/practical-guide/log-storage-analysis.md

[doc](log analysis) update log-analysis example

---

docs/sql-manual/sql-functions/scalar-functions/encrypt-digest-functions/sha2.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/encrypt-digest-functions/sha2.md

[Fix](function) Add lost check of function SHA2 in nereids

---

i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/data-operate/export/export-manual.md
versioned_docs/version-2.0/data-operate/export/export-manual.md

"parallelusm" -> "parallelism"

fix Word spelling error

---

docs/admin-manual/workload-management/workload-group-bind-compute-group.md
docs/data-operate/import/import-way/broker-load-manual.md
docs/data-operate/import/import-way/routine-load-manual.md
docs/data-operate/import/import-way/stream-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/workload-management/workload-group-bind-compute-group.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/broker-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/routine-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/stream-load-manual.md
sidebars.json

[docs]add job bind compute group docs

---

docs/data-operate/import/import-way/routine-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/routine-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/routine-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/routine-load-manual.md
versioned_docs/version-2.1/data-operate/import/import-way/routine-load-manual.md
versioned_docs/version-3.0/data-operate/import/import-way/routine-load-manual.md

[opt](routine-load) add sasl example

---

docs/lakehouse/sql-convertor/sql-convertor-overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/sql-convertor/sql-convertor-overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/sql-dialect.md
versioned_docs/version-3.0/lakehouse/sql-dialect.md

[feat](sql-convertor) add some sql convertor variables

---

docs/sql-manual/sql-functions/aggregate-functions/regr_intercept.md
docs/sql-manual/sql-functions/aggregate-functions/regr_slope.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/regr_intercept.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/regr_slope.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/aggregate-functions/regr_intercept.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/aggregate-functions/regr_slope.md
sidebars.json
versioned_docs/version-3.0/sql-manual/sql-functions/aggregate-functions/regr_intercept.md
versioned_docs/version-3.0/sql-manual/sql-functions/aggregate-functions/regr_slope.md
versioned_sidebars/version-3.0-sidebars.json

[docs](function) support aggregrate function regr_slope regr_intercept

---

docs/table-design/data-type.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/data-type.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/data-type.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/data-type.md
versioned_docs/version-2.1/table-design/data-type.md
versioned_docs/version-3.0/table-design/data-type.md

[Doc](date_type) fix date/datetime date_type size not correct

---

docs/sql-manual/sql-functions/scalar-functions/date-time-functions/time.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/time.md
sidebars.json

[doc](function)add docs for time function

---

docs/admin-manual/open-api/fe-http/get-wal-size-action.md
versioned_docs/version-2.1/admin-manual/open-api/fe-http/get-wal-size-action.md
versioned_docs/version-3.0/admin-manual/open-api/fe-http/get-wal-size-action.md
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

[Fix](doc) Fix  invalid get wal size action api

---

docs/sql-manual/sql-statements/table-and-view/index/BUILD-INDEX.md
docs/sql-manual/sql-statements/table-and-view/index/CREATE-INDEX.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/index/BUILD-INDEX.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/index/CREATE-INDEX.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/index/BUILD-INDEX.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/index/CREATE-INDEX.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/index/BUILD-INDEX.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/index/CREATE-INDEX.md
versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/index/BUILD-INDEX.md
versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/index/CREATE-INDEX.md
versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/index/BUILD-INDEX.md
versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/index/CREATE-INDEX.md

[docs]Fix doc error

---

docs/install/deploy-on-kubernetes/integrated-storage-compute/cluster-operation.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/install/deploy-on-kubernetes/integrated-storage-compute/cluster-operation.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/deploy-on-kubernetes/cluster-operation.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/deploy-on-kubernetes/integrated-storage-compute/cluster-operation.md
versioned_docs/version-2.1/install/deploy-on-kubernetes/cluster-operation.md
versioned_docs/version-3.0/install/deploy-on-kubernetes/integrated-storage-compute/cluster-operation.md

[Docs]image from selectdb to apache

---

docs/install/deploy-on-kubernetes/separating-storage-compute/config-cluster.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/install/deploy-on-kubernetes/separating-storage-compute/config-cluster.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/deploy-on-kubernetes/separating-storage-compute/config-cluster.md
versioned_docs/version-3.0/install/deploy-on-kubernetes/separating-storage-compute/config-cluster.md

[doc] k8s decoupled cluster support kerberos

---

docs/sql-manual/basic-element/sql-data-types/numeric/DECIMAL.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/basic-element/sql-data-types/numeric/DECIMAL.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/basic-element/sql-data-types/numeric/DECIMAL.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/basic-element/sql-data-types/numeric/DECIMAL.md
versioned_docs/version-2.1/sql-manual/basic-element/sql-data-types/numeric/DECIMAL.md
versioned_docs/version-3.0/sql-manual/basic-element/sql-data-types/numeric/DECIMAL.md

[docs] add decimal examples

---

docs/lakehouse/file-formats/orc.md
docs/lakehouse/file-formats/parquet.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/file-formats/orc.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/file-formats/parquet.md

[doc](catalog)add parquet orc reader parameter

---

i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/table-design/data-partitioning/auto-bucket.md

[fix](auto bucket) partition size estimated as one bucket

---

docs/admin-manual/auth/integrations/aws-authentication-and-authorization.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/auth/integrations/aws-authentication-and-authorization.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/auth/integrations/aws-authentication-and-authorization.md
versioned_docs/version-3.0/admin-manual/auth/integrations/aws-authentication-and-authorization.md

[chore](iam role) Optimize the document format about aws iam role

---

docs/admin-manual/data-admin/ccr/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/data-admin/ccr/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/data-admin/ccr/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/data-admin/ccr/overview.md
versioned_docs/version-2.1/admin-manual/data-admin/ccr/overview.md
versioned_docs/version-3.0/admin-manual/data-admin/ccr/overview.md

update ccr address to 2.1.10-rc02/3.0.6-rc02

---

docs/lakehouse/catalogs/hudi-catalog.md
docs/sql-manual/sql-functions/table-valued-functions/hudi-meta.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/hudi-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-valued-functions/hudi-meta.md

[fix](hudi) add hudi_meta release version

---

docs/admin-manual/system-tables/information_schema/partitions.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/system-tables/information_schema/partitions.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/system-tables/information_schema/partitions.md
versioned_docs/version-3.0/admin-manual/system-tables/information_schema/partitions.md

https://github.com/apache/doris/pull/51025

[docs](system-table)update infomation_schema partitions doc

---

docs/admin-manual/open-api/fe-http/node-action.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/fe-http/node-action.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/open-api/fe-http/node-action.md
versioned_docs/version-3.0/admin-manual/open-api/fe-http/node-action.md

[feat](http-api) add broker op api

---

docs/sql-manual/sql-statements/cluster-management/storage-management/ALTER-STORAGE-VAULT.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/cluster-management/storage-management/ALTER-STORAGE-VAULT.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/cluster-management/storage-management/ALTER-STORAGE-VAULT.md
versioned_docs/version-3.0/sql-manual/sql-statements/cluster-management/storage-management/ALTER-STORAGE-VAULT.md

Add some msgs for alter vault's name

---

docs/lakehouse/storages/s3.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/storages/s3.md

[lakehouse](storage) add s3 directory bucket doc

---

docs/lakehouse/storages/hdfs.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/storages/hdfs.md

[opt](hdfs) add hdfs client tool

---

docs/lakehouse/catalogs/iceberg-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/iceberg-catalog.md

pr: https://github.com/apache/doris/pull/52591

[doc](iceberg) support schema change ddl for iceberg

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/tiered-storage/remote-storage.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/table-design/cold-hot-separation.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/tiered-storage/remote-storage.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/tiered-storage/remote-storage.m
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/tiered-storage/remote-storage.md
versioned_docs/version-2.0/table-design/cold-hot-separation.md
versioned_docs/version-2.1/table-design/tiered-storage/remote-storage.md
versioned_docs/version-3.0/table-design/tiered-storage/remote-storage.md

Add property `root_path` in HDFS based tiered-storage examples

---

docs/lakehouse/catalogs/iceberg-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/iceberg-catalog.md

[opt](iceberg) opt iceberg sql

---

docs/table-design/row-store.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/row-store.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/row-store.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/row-store.md
versioned_docs/version-3.0/table-design/row-store.md

make row-store hit condition more clear

---

i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/deploy-manually/integrated-storage-compute-deploy-manually.md

[Doc] fix typo

---

docs/admin-manual/open-api/fe-http/profile-action.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/fe-http/profile-action.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/open-api/fe-http/profile-action.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/open-api/fe-http/profile-action.md
versioned_docs/version-2.1/admin-manual/open-api/fe-http/profile-action.md
versioned_docs/version-3.0/admin-manual/open-api/fe-http/profile-action.md

[auth]profile action add notice

---

community/how-to-contribute/jdbc-catalog-developer-guide.md
community/how-to-contribute/trino-connector-developer-guide.md
docs/lakehouse/catalogs/jdbc-catalog-overview.md
i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-contribute/jdbc-catalog-developer-guide.md
i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-contribute/trino-connector-developer-guide.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/jdbc-catalog-overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/catalogs/jdbc-catalog-overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/catalogs/jdbc-catalog-overview.md
sidebarsCommunity.json
versioned_docs/version-2.1/lakehouse/catalogs/jdbc-catalog-overview.md
versioned_docs/version-3.0/lakehouse/catalogs/jdbc-catalog-overview.md

[add](jdbc) add jdbc catalog developer guide

---

docs/lakehouse/catalogs/paimon-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/paimon-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/catalogs/paimon-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/catalogs/paimon-catalog.md
versioned_docs/version-2.1/lakehouse/catalogs/paimon-catalog.md
versioned_docs/version-3.0/lakehouse/catalogs/paimon-catalog.md

[doc][lakehouse]Fix paimon catalog system table

---

docs/sql-manual/sql-functions/aggregate-functions/stddev.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/stddev.md

[Doc](Agg) Add alias name:std to stddev

---

docs/sql-manual/sql-functions/aggregate-functions/avg.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/avg.md

update doc of function avg

---

i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/backup-and-restore/RESTORE.md

Delete duplicate content for RESTORE

---

community/developer-guide/arthas.md
i18n/zh-CN/docusaurus-plugin-content-docs-community/current/developer-guide/arthas.md

[opt](arths) opt arths

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/metastores/aliyun-dlf.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/metastores/aws-glue.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/metastores/hive-metastore.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/metastores/s3tables.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/storages/aliyun-oss.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/storages/huawei-obs.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/storages/s3.md

Master new catalog

---

docs/sql-manual/sql-statements/table-and-view/table/CREATE-TABLE.md
docs/table-design/data-partitioning/auto-partitioning.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/table/CREATE-TABLE.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/data-partitioning/auto-partitioning.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/table/CREATE-TABLE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/data-partitioning/auto-partitioning.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/table/CREATE-TABLE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/data-partitioning/auto-partitioning.md
versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/table/CREATE-TABLE.md
versioned_docs/version-2.1/table-design/data-partitioning/auto-partitioning.md
versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/table/CREATE-TABLE.md
versioned_docs/version-3.0/table-design/data-partitioning/auto-partitioning.md

[DDL] fix wrong create table describe about auto partition

---

docs/sql-manual/basic-element/sql-data-types/conversion/time-conversion.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/basic-element/sql-data-types/conversion/time-conversion.md

Fix wrong time conversion rules of non-restrict mode

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/ai-functions/llm-functions/llm-function.md

[fix](sql-manual)Fix typos

---

docs/ai/llm-function-overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/ai/llm-function-overview.md
sidebars.json

add ai and llm catagory

---

docs/lakehouse/catalogs/paimon-catalog.md
docs/lakehouse/metastores/aws-glue.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/paimon-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/metastores/aliyun-dlf.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/catalogs/paimon-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/metastores/aliyun-dlf.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/catalogs/paimon-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/metastores/aliyun-dlf.md
versioned_docs/version-2.1/lakehouse/catalogs/paimon-catalog.md
versioned_docs/version-3.0/lakehouse/catalogs/paimon-catalog.md

[opt](paimon) add paimon dlf rest catalog doc

---

i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/system-tables/information_schema/backend_configuration.md
versioned_docs/version-3.0/admin-manual/system-tables/information_schema/backend_configuration.md

[doc]add version info for backend_conf table doc

---

docs/lakehouse/best-practices/doris-aws-s3tables.md
docs/lakehouse/best-practices/doris-dlf-paimon.md
docs/lakehouse/catalogs/paimon-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/best-practices/doris-dlf-paimon.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/paimon-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/best-practices/doris-dlf-paimon.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/catalogs/paimon-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/best-practices/doris-dlf-paimon.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/catalogs/paimon-catalog.md
sidebars.json
versioned_docs/version-2.1/lakehouse/best-practices/doris-aws-s3tables.md
versioned_docs/version-2.1/lakehouse/best-practices/doris-dlf-paimon.md
versioned_docs/version-2.1/lakehouse/catalogs/paimon-catalog.md
versioned_docs/version-3.0/lakehouse/best-practices/doris-aws-s3tables.md
versioned_docs/version-3.0/lakehouse/best-practices/doris-dlf-paimon.md
versioned_docs/version-3.0/lakehouse/catalogs/paimon-catalog.md
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

[opt](paimon) add paimon dlf 2.5

---

docs/lakehouse/best-practices/doris-dlf-paimon.md
versioned_docs/version-2.1/lakehouse/best-practices/doris-dlf-paimon.md
versioned_docs/version-3.0/lakehouse/best-practices/doris-dlf-paimon.md

[opt](paimon) change alibaba to aliyun

---

docs/sql-manual/basic-element/sql-data-types/conversion/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/basic-element/sql-data-types/conversion/overview.md
sidebars.json

add type conversion docs

---

docs/admin-manual/cluster-management/time-zone.md
sidebars.json

Add link from time-zone doc to datetime doc directory

---

docs/sql-manual/sql-functions/scalar-functions/numeric-functions/isinf.md
docs/sql-manual/sql-functions/scalar-functions/numeric-functions/isnan.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/isinf.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/isnan.md
sidebars.json

[doc](function)add docs for isnan,isinf

---

docs/ecosystem/doris-kafka-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/doris-kafka-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/doris-kafka-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/ecosystem/doris-kafka-connector.md
versioned_docs/version-2.1/ecosystem/doris-kafka-connector.md
versioned_docs/version-3.0/ecosystem/doris-kafka-connector.md

[Fix](ecosystem) update kafka connector doc

---

docs/sql-manual/sql-functions/scalar-functions/map-functions/map.md
docs/sql-manual/sql-functions/scalar-functions/struct-functions/struct-element.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/map-functions/map.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/struct-functions/struct-element.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/map-functions/map.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/struct-functions/struct-element.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/map-functions/map.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/struct-functions/struct-element.md
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/map-functions/map.md
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/struct-functions/struct-element.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/map-functions/map.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/struct-functions/struct-element.md

[doc](function) add case sensitive for element_at, struct_element function

---

docs/lakehouse/best-practices/doris-dlf-paimon.md
docs/lakehouse/catalogs/iceberg-catalog.md
docs/lakehouse/catalogs/paimon-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/best-practices/doris-dlf-paimon.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/iceberg-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/paimon-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/best-practices/doris-dlf-paimon.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/catalogs/iceberg-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/catalogs/paimon-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/best-practices/doris-dlf-paimon.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/catalogs/iceberg-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/catalogs/paimon-catalog.md
versioned_docs/version-2.1/lakehouse/best-practices/doris-dlf-paimon.md
versioned_docs/version-2.1/lakehouse/catalogs/iceberg-catalog.md
versioned_docs/version-2.1/lakehouse/catalogs/paimon-catalog.md
versioned_docs/version-3.0/lakehouse/best-practices/doris-dlf-paimon.md
versioned_docs/version-3.0/lakehouse/catalogs/iceberg-catalog.md
versioned_docs/version-3.0/lakehouse/catalogs/paimon-catalog.md

[opt](iceberg) add some timezone doc for iceberg and paimon

---

docs/sql-manual/sql-functions/aggregate-functions/retention.md
i18n/zh-CN/docusaurus-plugin-content-docs/current.json
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/retention.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/aggregate-functions/retention.md
versioned_docs/version-3.0/sql-manual/sql-functions/aggregate-functions/retention.md

[doc](function)update some doc about retention function

---

docs/sql-manual/sql-functions/table-functions/explode-json-array-double-outer.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-functions/explode-json-array-double-outer.md

Fix explode

---

docs/gettingStarted/alternatives/alternative-to-clickhouse.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/gettingStarted/alternatives/alternative-to-clickhouse.mdx

[alternative](ck) add storage and compute seperation and opensource

---

docs/compute-storage-decoupled/recycler.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/compute-storage-decoupled/recycler.md
sidebars.json

Add recycler doc

---

docs/lakehouse/metastores/aliyun-dlf.md
docs/lakehouse/storages/aliyun-oss.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/metastores/aliyun-dlf.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/storages/aliyun-oss.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/metastores/aliyun-dlf.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/storages/aliyun-oss.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/metastores/aliyun-dlf.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/storages/aliyun-oss.md
versioned_docs/version-2.1/lakehouse/metastores/aliyun-dlf.md
versioned_docs/version-2.1/lakehouse/storages/aliyun-oss.md
versioned_docs/version-3.0/lakehouse/metastores/aliyun-dlf.md
versioned_docs/version-3.0/lakehouse/storages/aliyun-oss.md

[opt](dlf) opt oss and dlf doc

---

docs/admin-manual/workload-management/spill-disk.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/workload-management/spill-disk.md
sidebars.json

- [x ] dev
- [x ] Chinese
- [ x] English
- [ x] Checked by AI

add spill disk doc

---

docs/table-design/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/overview.md
versioned_docs/version-2.1/table-design/overview.md
versioned_docs/version-3.0/table-design/overview.md

[opt] add dynamic partition attributes in table overview

---

docs/lakehouse/catalogs/jdbc-ibmdb2-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/jdbc-ibmdb2-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/catalogs/jdbc-ibmdb2-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/catalogs/jdbc-ibmdb2-catalog.md
versioned_docs/version-2.1/lakehouse/catalogs/jdbc-ibmdb2-catalog.md
versioned_docs/version-3.0/lakehouse/catalogs/jdbc-ibmdb2-catalog.md

[opt](db2) add charset options

---

i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/compute-storage-decoupled/recycler.md
versioned_docs/version-3.0/compute-storage-decoupled/recycler.md

Add recycler doc for 3.0

---

docs/lakehouse/catalogs/iceberg-catalog.md
docs/lakehouse/catalogs/jdbc-ibmdb2-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/iceberg-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/jdbc-ibmdb2-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/catalogs/iceberg-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/catalogs/jdbc-ibmdb2-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/catalogs/iceberg-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/catalogs/jdbc-ibmdb2-catalog.md
versioned_docs/version-2.1/lakehouse/catalogs/iceberg-catalog.md
versioned_docs/version-2.1/lakehouse/catalogs/jdbc-ibmdb2-catalog.md
versioned_docs/version-3.0/lakehouse/catalogs/iceberg-catalog.md
versioned_docs/version-3.0/lakehouse/catalogs/jdbc-ibmdb2-catalog.md

[opt](catalog) add db2 charset options and opt iceberg doc

---

docs/sql-manual/sql-functions/scalar-functions/numeric-functions/format-round.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/format-round.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/format-round.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/format-round.md

[doc] Add a range limit to the second parameter of format_round.

---

docs/lakehouse/catalogs/hive-catalog.mdx
docs/lakehouse/catalogs/iceberg-catalog.mdx
docs/lakehouse/catalogs/paimon-catalog.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/hive-catalog.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/iceberg-catalog.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/paimon-catalog.mdx

[opt](catalog) opt example for hive,iceberg,paimon

---

docs/lakehouse/catalogs/iceberg-catalog.mdx
docs/lakehouse/catalogs/paimon-catalog.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/iceberg-catalog.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/paimon-catalog.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/catalogs/iceberg-catalog.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/catalogs/paimon-catalog.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/catalogs/iceberg-catalog.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/catalogs/paimon-catalog.mdx
versioned_docs/version-2.1/lakehouse/catalogs/iceberg-catalog.mdx
versioned_docs/version-2.1/lakehouse/catalogs/paimon-catalog.mdx
versioned_docs/version-3.0/lakehouse/catalogs/iceberg-catalog.mdx
versioned_docs/version-3.0/lakehouse/catalogs/paimon-catalog.mdx

update minio & paimon s3 catalog

---

src/constant/download.data.ts

Update 3.0.8 download

---

docs/sql-manual/sql-functions/scalar-functions/string-functions/make-set.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/string-functions/make-set.md
sidebars.json

[Feature](func) Support function MAKE_SET

---

docs/admin-manual/system-tables/information_schema/processlist.md
docs/data-operate/import/import-way/stream-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/system-tables/information_schema/processlist.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/stream-load-manual.md

[doc](load) document the compute_group argument

---

sidebars.json

- [x ] dev
- [ x] Chinese
- [x ] English

add vector search sidebar

---

docs/ai/vector-search.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/ai/vector-search.md

- [ x] dev
- [x ] Chinese
- [x ] English

[fix] rename quant to quantizer
