docusaurus.config.js

Google Analytics 4 need to using plugin-google-gtag

[fix] use plugin-google-gtag

---

.github/workflows/manual-deploy-website.yml
.gitmodules

Because ```aliyun-oss-website-action``` is not created by Github or verified creators, and it does not comply with Apache rules, We use ```git submodule``` use it in our repo. ```actions/checkout``` need set to submodules: recursive makes it work.

[CDN] Use aliyun-oss-website-action in our repo

---

.github/workflows/manual-deploy-website.yml

```git push --verbose "https://${{ secrets.GITHUB_TOKEN }}@github.com/apache/doris-website.git" asf-site:asf-site```
not work, use ```actions-gh-pages``` instead it.

[CDN] Use actions-gh-pages deploy website

---

docs/data-table/data-model.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-table/data-model.md

When creating the table of the Duplicate model, specify the SortKet of error_code as Yes, but when creating the table later, the DUPLICATE KEY does not contain the error_code field, only the timestamp and type fields exist. Please check whether to add this field.

Modify the Duplicate model document error in the data-module directory

---

docs/admin-manual/config/be-config.md
docs/install/install-deploy.md

In document, add a notice that mix of SSD and HDD disks should specify the storage directory only

[typo](docs) mix of SSD and HDD disks should specify the storage directory only

---

.github/workflows/cron-deploy-website.yml
.github/workflows/manual-deploy-website.yml
.gitmodules

- ```index.html```: hosted by Apache and Apache CDN (which is based on Cloudflare)
- ``` other resources ``` like CSS, images, Javascript...etc hosted By SelectDB OSS and CDN (which is based on Aliyun/Tencent Cloud)
Our Deploy Action, push ```index.html``` to Apache and other resources to Aliyun, but two infra refresh CDN was not very in time.
Our expectation is when I release the index.html to Apache, Apache refreshes files to CDN, and the user can visit the new index.html from Apache CDN, and load other resources from Aliyun CDN. But we found that users do not always visit the new index.html from Apache CDN, and old files from Aliyun CDN were deleted, the below error happened.
Do not delete Aliyun CDN files, While the user visits the expired index.html file, Aliyun can provide …

(OSS) Do not delete expired files

---

src/constant/download.data.ts

There is no mirror site for achieve in China. So use same link as apache

[fix](download_link) use apache link for archieve

---

src/constant/download.data.ts
src/constant/newsletter.data.ts
src/pages/download/index.tsx

[fix] releasenote 2.0.0 use github issue url

[fix] releasenote 2.0.0 use github issue url

---

src/pages/download/index.tsx

- [(typo) use 2.0.1 in download page](https://github.com/apache/doris-website/commit/8d72e35fee02ca73ef168170065851f4afad0ce6)

(typo) use 2.0.1 in download page

---

src/pages/index.tsx

Update link of what is Apache Doris on home page

[home](fix) Update link of what is Apache Doris on home page

---

docs/query-acceleration/async-materialized-view/query-async-materialized-view.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query-acceleration/async-materialized-view/query-async-materialized-view.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-acceleration/async-materialized-view/query-async-materialized-view.md
versioned_docs/version-2.1/query-acceleration/async-materialized-view/query-async-materialized-view.md

This pattern of rewriting is supported for multi-table joins and supported join types is as following:
* INNER JOIN
* LEFT OUTER JOIN
* RIGHT OUTER JOIN
* FULL OUTER JOIN
* LEFT SEMI JOIN
* RIGHT SEMI JOIN
* LEFT ANTI JOIN
* RIGHT ANTI JOIN

[doc](mtmv) Support more join types for query rewriting by materialized view

---

docs/lakehouse/datalake-analytics/iceberg.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/datalake-analytics/iceberg.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/lakehouse/multi-catalog/iceberg.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/lakehouse/datalake/iceberg.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/datalake-analytics/iceberg.md
versioned_docs/version-1.2/lakehouse/multi-catalog/iceberg.md
versioned_docs/version-2.0/lakehouse/datalake/iceberg.md
versioned_docs/version-2.1/lakehouse/datalake-analytics/iceberg.md

Fix the 'Column Type Mapping' error problem in the Iceberg documentation

[doc](iceberg) fix iceberg column type map error.

---

docs/data-operate/import/transaction-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/transaction-load-manual.md
sidebars.json

PR: https://github.com/apache/doris/pull/32980

[Doc](txn-insert) Add txn-insert doc

---

docs/query/query-data/lateral-view.md
docs/sql-manual/sql-functions/aggregate-functions/group-concat.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query/query-data/lateral-view.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/group-concat.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/advanced/lateral-view.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/aggregate-functions/group_concat.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/query/query-data/lateral-view.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/aggregate-functions/group-concat.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query/query-data/lateral-view.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/aggregate-functions/group-concat.md
versioned_docs/version-1.2/advanced/lateral-view.md
versioned_docs/version-1.2/sql-manual/sql-functions/aggregate-functions/group_concat.md
versioned_docs/version-2.0/query/query-data/lateral-view.md
versioned_docs/version-2.0/sql-manual/sql-functions/aggregate-functions/group-concat.md
versioned_docs/version-2.1/query/query-data/lateral-view.md
versioned_docs/version-2.1/sql-manual/sql-functions/aggregate-functions/group-concat.md

1. group_concat: don't support using `distinct` with `order by` together.
2. table_identifier is required in lateral view syntax

[doc](fix) add caution for `group_concat` and `lateral view`

---

docs/sql-manual/sql-statements/Show-Statements/SHOW-STORAGE-POLICY-USING.md
docs/table-design/cold-hot-separation.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Show-Statements/SHOW-STORAGE-POLICY-USING.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/cold-hot-separation.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-reference/Show-Statements/SHOW-STORAGE-POLICY-USING.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/table-design/cold-hot-separation.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/Show-Statements/SHOW-STORAGE-POLICY-USING.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/cold-hot-separation.md
sidebars.json
versioned_docs/version-2.0/sql-manual/sql-reference/Show-Statements/SHOW-STORAGE-POLICY-USING.md
versioned_docs/version-2.0/table-design/cold-hot-separation.md
versioned_docs/version-2.1/sql-manual/sql-statements/Show-Statements/SHOW-STORAGE-POLICY-USING.md
versioned_docs/version-2.1/table-design/cold-hot-separation.md
versioned_sidebars/version-2.0-sidebars.json
versioned_sidebars/version-2.1-sidebars.json

```
mysql> show storage policy using for test_policy;  
+-------------+----------+---------------------------------+-----------------+
| PolicyName  | Database | Table                           | Partitions      |
+-------------+----------+---------------------------------+-----------------+
| test_policy | db1      | target_test_1                   | ALL             | 
| test_policy | db1      | cooldown_test                   | ALL             |
| test_policy | db1      | partition_test_2                | p201701         |
| test_policy | db1      | partition_with_storage_policy_1 | p201701         | 
| test_policy | db1      | partition_test_1                | p201701,p201702 |
| test_policy | db2      | db2_test_1                      | ALL             | …
```

[Improvement](cooldown) add statment to show objects which use storage policy

---

docs/install/source-install/compilation-mac.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/source-install/compilation-mac.md

Add an error resolution for compiling under Mac with M3 chip.

[doc] (compile) Add an error resolution for compiling under Mac

---

docs/admin-manual/config/fe-config.md
docs/data-operate/delete/batch-delete-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/config/fe-config.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/delete/batch-delete-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/delete/batch-delete-manual.md
versioned_docs/version-2.1/data-operate/delete/batch-delete-manual.md

batch delete is supported as a default feature since 0.15, we don't need the contents about "How to Enable Batch Delete Support" in our documents, remove the in the docs of master and version 2.1
remove the outdated config `enable_batch_delete_by_default` as well, related doris PR: https://github.com/apache/doris/pull/36485

[doc](batch-delete) remove outdated contents

---

docs/sql-manual/sql-functions/numeric-functions/random.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/numeric-functions/random.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/numeric-functions/random.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/numeric-functions/random.md
versioned_docs/version-2.1/sql-manual/sql-functions/numeric-functions/random.md
versioned_docs/version-3.0/sql-manual/sql-functions/numeric-functions/random.md

master pr: https://github.com/apache/doris/pull/39255

[fix](function) Add parameter restrictions for function random

---

common_docs_zh/gettingStarted/quick-start.md
gettingStarted/quick-start.md
src/theme/DocItem/Layout/pathTransfer.ts

- update the QuickStart page 
- The path in the edit button may not work correctly

[Doc] Fix `apache-doris/fe/conf/fe.conf` path error in QuickStart page

---

src/scss/components/navbar.scss
src/theme/Navbar/Content/styles.module.css

fix search bar disappear bug while the screen < 1366px

[fix](docs): fix search bar disappear bug while the screen < 1366px

---

docs/sql-manual/sql-functions/aggregate-functions/kurt.md
docs/sql-manual/sql-functions/aggregate-functions/skew.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/kurt.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/skew.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/aggregate-functions/kurt.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/aggregate-functions/skew.md
sidebars.json
versioned_docs/version-3.0/sql-manual/sql-functions/aggregate-functions/kurt.md
versioned_docs/version-3.0/sql-manual/sql-functions/aggregate-functions/skew.md
versioned_sidebars/version-3.0-sidebars.json

ref https://github.com/apache/doris/pull/40945

Docs for skew and kurt

---

docs/sql-manual/sql-functions/string-functions/ngram-search.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/string-functions/ngram-search.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/string-functions/ngram-search.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/string-functions/ngram-search.md
sidebars.json
versioned_docs/version-2.1/sql-manual/sql-functions/string-functions/ngram-search.md
versioned_docs/version-3.0/sql-manual/sql-functions/string-functions/ngram-search.md
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

https://github.com/apache/doris/pull/38226

[doc] support ngram_search function

---

docs/query/query-variables/variables.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query/query-variables/variables.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query/query-variables/variables.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query/query-variables/variables.md
versioned_docs/version-2.1/query/query-variables/variables.md
versioned_docs/version-3.0/query/query-variables/variables.md

https://github.com/apache/doris/pull/39927

session vars used to control scanner

---

docs/sql-manual/sql-functions/bitwise-functions/bit_test.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/bitwise-functions/bit_test.md
sidebars.json

[doc](function)support bit_test function

---

docs/data-operate/import/import-way/stream-load-manual.md
docs/data-operate/update/update-of-unique-model.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/stream-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/update/update-of-unique-model.md

Doc for https://github.com/apache/doris/pull/39756

[Docs] Add doc for flexible partial update

---

docs/query/query-variables/variables.md
docs/sql-manual/sql-statements/Data-Manipulation-Statements/Manipulation/INSERT-OVERWRITE.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query/query-variables/variables.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Data-Manipulation-Statements/Manipulation/INSERT-OVERWRITE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-data/delete-query-variables/variables.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/Data-Manipulation-Statements/Manipulation/INSERT-OVERWRITE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query/query-variables/variables.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/Data-Manipulation-Statements/Manipulation/INSERT-OVERWRITE.md
versioned_docs/version-2.1/query-data/delete-query-variables/variables.md
versioned_docs/version-2.1/sql-manual/sql-statements/Data-Manipulation-Statements/Manipulation/INSERT-OVERWRITE.md
versioned_docs/version-3.0/query/query-variables/variables.md
versioned_docs/version-3.0/sql-manual/sql-statements/Data-Manipulation-Statements/Manipulation/INSERT-OVERWRITE.md

doc of: https://github.com/apache/doris/pull/38628

[Feature](insert-overwrite) Support create partition for auto partition table when insert overwrite

---

docs/admin-manual/log-management/be-log.md
docs/admin-manual/open-api/be-http/be-vlog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/log-management/be-log.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/open-api/be-http/be-vlog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/log-management/be-log.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/open-api/be-http/be-vlog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/log-management/be-log.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/open-api/be-http/be-vlog.md
sidebars.json
versioned_docs/version-2.1/admin-manual/log-management/be-log.md
versioned_docs/version-2.1/admin-manual/open-api/be-http/be-vlog.md
versioned_docs/version-3.0/admin-manual/log-management/be-log.md
versioned_docs/version-3.0/admin-manual/open-api/be-http/be-vlog.md
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

code pr: https://github.com/apache/doris/pull/28785

[Doc](RESTapi) Add document of BE VLOG adjustment RESTful api

---

docs/table-design/tiered-storage/remote-storage.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/tiered-storage/remote-storage.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/table-design/cold-hot-separation.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/tiered-storage/remote-storage.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/tiered-storage/remote-storage.md
versioned_docs/version-2.0/table-design/cold-hot-separation.md
versioned_docs/version-2.1/table-design/tiered-storage/remote-storage.md
versioned_docs/version-3.0/table-design/tiered-storage/remote-storage.md

[doc](typo) fix some typo in `remote-storage` section

---

docs/data-operate/import/import-way/routine-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/routine-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/import-way/routine-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/import-way/routine-load-manual.md
versioned_docs/version-2.1/data-operate/import/import-way/routine-load-manual.md
versioned_docs/version-3.0/data-operate/import/import-way/routine-load-manual.md

[doc](routine load) fix routine load doc error

---

docs/admin-manual/config/fe-config.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/config/fe-config.md

Add restore_download_snapshot_batch_size/backup_upload_snapshot_batch_size config

---

src/components/download-form/download-form-tools.tsx
src/constant/download.data.ts

Doris connector supports selecting Flink/Spark versions.

[web]Update the version selection on the upgrade page

---

docs/sql-manual/sql-functions/aggregate-functions/approx-count-distinct.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/aggregate-functions/approx-count-distinct.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/aggregate-functions/approx-count-distinct.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/aggregate-functions/approx-count-distinct.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/aggregate-functions/approx-count-distinct.md
versioned_docs/version-2.0/sql-manual/sql-functions/aggregate-functions/approx-count-distinct.md
versioned_docs/version-2.1/sql-manual/sql-functions/aggregate-functions/approx-count-distinct.md
versioned_docs/version-3.0/sql-manual/sql-functions/aggregate-functions/approx-count-distinct.md

[Enhancement](function) Add more detail explanation about approx_count_distinct function 

---

docs/query-data/complex-type.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/query-data/complex-type.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/query-data/complex-type.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/query-data/complex-type.md
versioned_docs/version-2.1/query-data/complex-type.md
versioned_docs/version-3.0/query-data/complex-type.md

[fix] Fix deadlink of complex data type

---

src/theme/SearchBar/SearchBar.jsx

If the URL contains a version, such as https://doris.apache.org/docs/releasenotes/v3.0/release-3.0.1, `location.pathname.includes(version)` will mistakenly think that the current version is 3.0

fix:search-index url

---

docs/admin-manual/memory-management/memory-analysis/doris-cache-memory-analysis.md
docs/admin-manual/memory-management/memory-analysis/metadata-memory-analysis.md
docs/admin-manual/memory-management/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/memory-management/memory-analysis/doris-cache-memory-analysis.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/memory-management/memory-analysis/metadata-memory-analysis.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/memory-management/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/memory-management/memory-analysis/doris-cache-memory-analysis.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/memory-management/memory-analysis/metadata-memory-analysis.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/memory-management/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/memory-management/memory-analysis/doris-cache-memory-analysis.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/memory-management/memory-analysis/metadata-memory-analysis.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/memory-management/overview.md
versioned_docs/version-2.1/admin-manual/memory-management/memory-analysis/doris-cache-memory-analysis.md
versioned_docs/version-2.1/admin-manual/memory-management/memory-analysis/metadata-memory-analysis.md
versioned_docs/version-2.1/admin-manual/memory-management/overview.md
versioned_docs/version-3.0/admin-manual/memory-management/memory-analysis/doris-cache-memory-analysis.md
versioned_docs/version-3.0/admin-manual/memory-management/memory-analysis/metadata-memory-analysis.md
versioned_docs/version-3.0/admin-manual/memory-management/overview.md

Fix http url error

---

i18n/zh-CN/docusaurus-plugin-content-docs/current.json
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/auth/authentication-and-authorization.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1.json
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/auth/authentication-and-authorization.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0.json
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/auth/authentication-and-authorization.md
sidebars.json
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

update sidebar for security

---

docs/admin-manual/data-admin/backup-restore/backup.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/data-admin/backup-restore/backup.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/data-admin/backup-restore/backup.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/data-admin/backup-restore/backup.md
versioned_docs/version-2.1/admin-manual/data-admin/backup-restore/backup.md
versioned_docs/version-3.0/admin-manual/data-admin/backup-restore/backup.md

auzre is not supported in 2.1

---

docs/admin-manual/config/fe-config.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/admin-manual/config/fe-config.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/config/fe-config.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/config/fe-config.md
versioned_docs/version-2.0/admin-manual/config/fe-config.md
versioned_docs/version-2.1/admin-manual/config/fe-config.md
versioned_docs/version-3.0/admin-manual/config/fe-config.md

- [ ✔ ] dev
- [✔  ] 3.0
- [✔  ] 2.1
- [✔  ] 2.0
- [ ✔ ] Chinese
- [✔  ] English

[doc]The maximum character length of the load label

---

docs/ecosystem/flink-doris-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/flink-doris-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/ecosystem/flink-doris-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/flink-doris-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/ecosystem/flink-doris-connector.md
versioned_docs/version-2.0/ecosystem/flink-doris-connector.md
versioned_docs/version-2.1/ecosystem/flink-doris-connector.md
versioned_docs/version-3.0/ecosystem/flink-doris-connector.md

[ecosystem](flink) update flink connector faq

---

docs/data-operate/export/export-manual.md
docs/data-operate/export/outfile.md
docs/sql-manual/sql-statements/Data-Manipulation-Statements/OUTFILE.md
docs/sql-manual/sql-statements/Show-Statements/SHOW-EXPORT.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/export/export-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/export/outfile.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Data-Manipulation-Statements/OUTFILE.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/Show-Statements/SHOW-EXPORT.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/export/export-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/export/outfile.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/OUTFILE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/SHOW-EXPORT.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/export/export-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/export/outfile.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/OUTFILE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/SHOW-EXPORT.md
versioned_docs/version-2.1/data-operate/export/export-manual.md
versioned_docs/version-2.1/data-operate/export/outfile.md
versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/OUTFILE.md
versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/SHOW-EXPORT.md
versioned_docs/version-3.0/data-operate/export/export-manual.md
versioned_docs/version-3.0/data-operate/export/outfile.md
versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/OUTFILE.md
versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/SHOW-EXPORT.md

[fix](outfile/export) refactor the documents of `Outfile` and `Export`

---

docs/data-operate/import/data-source/kafka.md
docs/ecosystem/doris-kafka-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/ecosystem/doris-kafka-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/import/data-source/kafka.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/doris-kafka-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/import/data-source/kafka.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/ecosystem/doris-kafka-connector.md
versioned_docs/version-2.0/ecosystem/doris-kafka-connector.md
versioned_docs/version-2.1/data-operate/import/data-source/kafka.md
versioned_docs/version-2.1/ecosystem/doris-kafka-connector.md
versioned_docs/version-3.0/data-operate/import/data-source/kafka.md
versioned_docs/version-3.0/ecosystem/doris-kafka-connector.md

Fix the prompt of kafka server, because sometimes it is mistaken for doris broker load

[ecosystem]fix kafka server prompt address

---

docs/data-operate/delete/batch-delete-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/delete/batch-delete-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/delete/batch-delete-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/data-operate/delete/batch-delete-manual.md
versioned_docs/version-2.1/data-operate/delete/batch-delete-manual.md
versioned_docs/version-3.0/data-operate/delete/batch-delete-manual.md

[doc](batch delete) address comment and translate en doc by LLM

---

docs/table-design/data-model/unique.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/table-design/data-model/unique.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/table-design/data-model/unique.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/table-design/data-model/unique.md
versioned_docs/version-2.1/table-design/data-model/unique.md
versioned_docs/version-3.0/table-design/data-model/unique.md

[fix] Fix data-model/unique typo (#1743)

---

docusaurus.config.js
i18n/zh-CN/code.json
src/pages/archive-docs/index.scss
src/pages/archive-docs/index.tsx

style:update archived page style

---

docs/sql-manual/sql-functions/scalar-functions/numeric-functions/dexp.md
docs/sql-manual/sql-functions/scalar-functions/numeric-functions/exp.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/dexp.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/numeric-functions/exp.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/dexp.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/exp.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/dexp.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/exp.md
sidebars.json
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/dexp.md
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/numeric-functions/exp.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/dexp.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/numeric-functions/exp.md
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-3.0-sidebars.json

- [✔️] dev
- [✔️ ] 3.0
- [✔️] 2.1
- [✔️] Chinese
- [✔️] English

exp function modify and dexp clear

---

docs/sql-manual/sql-functions/scalar-functions/conditional-functions/not-null-or-empty.md
docs/sql-manual/sql-functions/scalar-functions/conditional-functions/null-or-empty.md
docs/sql-manual/sql-functions/scalar-functions/string-functions/digital-masking.md
docs/sql-manual/sql-functions/scalar-functions/string-functions/sub-replace.md
docs/sql-manual/sql-functions/scalar-functions/string-functions/unhex.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/conditional-functions/not-null-or-empty.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/conditional-functions/null-or-empty.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/string-functions/digital-masking.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/string-functions/sub-replace.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/string-functions/unhex.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/conditional-functions/not-null-or-empty.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/conditional-functions/null-or-empty.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/digital-masking.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/sub-replace.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/unhex.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/conditional-functions/not-null-or-empty.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/conditional-functions/null-or-empty.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/digital-masking.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/sub-replace.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/unhex.md
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/conditional-functions/not-null-or-empty.md
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/conditional-functions/null-or-empty.md
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/digital-masking.md
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/sub-replace.md
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/unhex.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/conditional-functions/not-null-or-empty.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/conditional-functions/null-or-empty.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/digital-masking.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/sub-replace.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/unhex.md

[doc]str func

---

docs/sql-manual/sql-statements/transaction/SHOW-TRANSACTION.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/transaction/SHOW-TRANSACTION.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/transaction/SHOW-TRANSACTION.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/transaction/SHOW-TRANSACTION.md
versioned_docs/version-2.1/sql-manual/sql-statements/transaction/SHOW-TRANSACTION.md
versioned_docs/version-3.0/sql-manual/sql-statements/transaction/SHOW-TRANSACTION.md

[doc]modify show transaction doc

---

docs/sql-manual/sql-statements/types/SHOW-DATA-TYPES.md
docs/sql-manual/sql-statements/types/SHOW-TYPECAST.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/types/SHOW-DATA-TYPES.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/types/SHOW-TYPECAST.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/types/SHOW-DATA-TYPES.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/types/SHOW-TYPECAST.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/types/SHOW-DATA-TYPES.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/types/SHOW-TYPECAST.md
versioned_docs/version-2.1/sql-manual/sql-statements/types/SHOW-DATA-TYPES.md
versioned_docs/version-2.1/sql-manual/sql-statements/types/SHOW-TYPECAST.md
versioned_docs/version-3.0/sql-manual/sql-statements/types/SHOW-DATA-TYPES.md
versioned_docs/version-3.0/sql-manual/sql-statements/types/SHOW-TYPECAST.md

[improve](docs)Improve type casting documentation clarity and example

---

docs/sql-manual/sql-statements/session/variable/SET-VARIABLE.md
docs/sql-manual/sql-statements/session/variable/SHOW-VARIABLES.md
docs/sql-manual/sql-statements/session/variable/UNSET-VARIABLE.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/session/variables/SET-VARIABLE.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/session/variables/SHOW-VARIABLES.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/session/variables/UNSET-VARIABLE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/session/variable/SET-VARIABLE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/session/variable/SHOW-VARIABLES.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/session/variable/UNSET-VARIABLE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/session/variables/SET-VARIABLE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/session/variables/SHOW-VARIABLES.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/session/variables/UNSET-VARIABLE.md
versioned_docs/version-2.1/sql-manual/sql-statements/session/variable/SET-VARIABLE.md
versioned_docs/version-2.1/sql-manual/sql-statements/session/variable/SHOW-VARIABLES.md
versioned_docs/version-2.1/sql-manual/sql-statements/session/variable/UNSET-VARIABLE.md
versioned_docs/version-3.0/sql-manual/sql-statements/session/variable/SET-VARIABLE.md
versioned_docs/version-3.0/sql-manual/sql-statements/session/variable/SHOW-VARIABLES.md
versioned_docs/version-3.0/sql-manual/sql-statements/session/variable/UNSET-VARIABLE.md

[docs]Fix variable docs of SHOW, SET and UNSET variables 

---

docs/sql-manual/sql-statements/table-and-view/materialized-view/CANCEL-MATERIALIZED-VIEW-TASK.md
docs/sql-manual/sql-statements/table-and-view/materialized-view/PAUSE-MATERIALIZED-VIEW-JOB.md
docs/sql-manual/sql-statements/table-and-view/materialized-view/REFRESH-MATERIALIZED-VIEW.md
docs/sql-manual/sql-statements/table-and-view/materialized-view/RESUME-MATERIALIZED-VIEW-JOB.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/materialized-view/CANCEL-MATERIALIZED-VIEW-TASK.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/materialized-view/PAUSE-MATERIALIZED-VIEW.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/materialized-view/REFRESH-MATERIALIZED-VIEW.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/table-and-view/materialized-view/RESUME-MATERIALIZED-VIEW.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/materialized-view/CANCEL-MATERIALIZED-VIEW-TASK.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/materialized-view/PAUSE-MATERIALIZED-VIEW.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/materialized-view/REFRESH-MATERIALIZED-VIEW.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/table-and-view/materialized-view/RESUME-MATERIALIZED-VIEW.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/materialized-view/CANCEL-MATERIALIZED-VIEW-TASK.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/materialized-view/PAUSE-MATERIALIZED-VIEW.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/materialized-view/REFRESH-MATERIALIZED-VIEW.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/table-and-view/materialized-view/RESUME-MATERIALIZED-VIEW.md
versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/materialized-view/CANCEL-MATERIALIZED-VIEW-TASK.md
versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/materialized-view/PAUSE-MATERIALIZED-VIEW.md
versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/materialized-view/REFRESH-MATERIALIZED-VIEW.md
versioned_docs/version-2.1/sql-manual/sql-statements/table-and-view/materialized-view/RESUME-MATERIALIZED-VIEW.md
versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/materialized-view/CANCEL-MATERIALIZED-VIEW-TASK.md
versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/materialized-view/PAUSE-MATERIALIZED-VIEW-JOB.md
versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/materialized-view/REFRESH-MATERIALIZED-VIEW.md
versioned_docs/version-3.0/sql-manual/sql-statements/table-and-view/materialized-view/RESUME-MATERIALIZED-VIEW-JOB.md

[docs]Fix statement docs of CANCAL, REFRESH, PAUSE and RESUME MATERIALIZED VIEW

---

docs/ecosystem/spark-doris-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/spark-doris-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/spark-doris-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/ecosystem/spark-doris-connector.md
versioned_docs/version-2.1/ecosystem/spark-doris-connector.md
versioned_docs/version-3.0/ecosystem/spark-doris-connector.md

improve spark connector docs

---

docs/sql-manual/sql-functions/scalar-functions/quantile-functions/quantile-percent.md
docs/sql-manual/sql-functions/scalar-functions/quantile-functions/quantile-state-empty.md
docs/sql-manual/sql-functions/scalar-functions/quantile-functions/to-quantile-state.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/quantile-functions/quantile-percent.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/quantile-functions/quantile-state-empty.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/quantile-functions/to-quantile-state.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/quantile-functions/quantile-percent.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/quantile-functions/quantile-state-empty.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/quantile-functions/to-quantile-state.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/quantile-functions/quantile-percent.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/quantile-functions/quantile-state-empty.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/quantile-functions/to-quantile-state.md
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/quantile-functions/quantile-percent.md
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/quantile-functions/quantile-state-empty.md
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/quantile-functions/to-quantile-state.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/quantile-functions/quantile-percent.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/quantile-functions/quantile-state-empty.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/quantile-functions/to-quantile-state.md

Quantile serias scalar function

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/string-functions/starts-with.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/starts-with.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/starts-with.md

Fix the confusion between Chinese and English in start_with function

---

docs/admin-manual/auth/authorization/data.md
docs/admin-manual/auth/authorization/ranger.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/auth/authorization/data.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/auth/authorization/ranger.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/auth/authorization/data.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/auth/authorization/ranger.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/auth/authorization/data.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/auth/authorization/ranger.md
versioned_docs/version-2.1/admin-manual/auth/authorization/data.md
versioned_docs/version-2.1/admin-manual/auth/authorization/ranger.md
versioned_docs/version-3.0/admin-manual/auth/authorization/data.md
versioned_docs/version-3.0/admin-manual/auth/authorization/ranger.md

- Super users are not controlled by datamask
- Ranger example configuration file
- Configuring row permissions still requires configuring relevant permissions

[auth]Improve the ranger documentation

---

docs/ecosystem/spark-doris-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/spark-doris-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/spark-doris-connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/ecosystem/spark-doris-connector.md
versioned_docs/version-2.1/ecosystem/spark-doris-connector.md
versioned_docs/version-3.0/ecosystem/spark-doris-connector.md

update doc for Spark connector v 25.0.1

---

docs/admin-manual/system-tables/information_schema/routine_load_job.md
i18n/en/docusaurus-plugin-content-docs/current/admin-manual/system-tables/information_schema/routine_load_job.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/system-tables/information_schema/routine_load_job.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/system-tables/information_schema/routine_load_job.md
sidebars.json
versioned_docs/version-3.0/admin-manual/system-tables/information_schema/routine_load_job.md
versioned_sidebars/version-3.0-sidebars.json

[doc](load) add routine load job system table doc

---

docs/install/deploy-on-kubernetes/integrated-storage-compute/install-config-cluster.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/install/deploy-on-kubernetes/integrated-storage-compute/install-config-cluster.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/deploy-on-kubernetes/install-config-cluster.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/deploy-on-kubernetes/integrated-storage-compute/install-config-cluster.md
versioned_docs/version-2.1/install/deploy-on-kubernetes/install-config-cluster.md
versioned_docs/version-3.0/install/deploy-on-kubernetes/integrated-storage-compute/install-config-cluster.md

[Doc][Enhancement]kerberos config on kubernetes

---

docs/sql-manual/sql-statements/data-modification/DML/INSERT-OVERWRITE.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/DML/INSERT-OVERWRITE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/DML/INSERT-OVERWRITE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/DML/INSERT-OVERWRITE.md
versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/DML/INSERT-OVERWRITE.md
versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/DML/INSERT-OVERWRITE.md

[Fix](DML) Add quick conclusion for insert overwrite behaviour and fix wrong version label in English docs

---

docs/lakehouse/catalogs/iceberg-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/iceberg-catalog.md

[opt](iceberg) add iceberg sys tables

---

docs/sql-manual/sql-functions/window-functions/nth-value.md
docs/sql-manual/sql-functions/window-functions/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/window-functions/nth-value.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/window-functions/overview.md

[doc](function) support nth_value function 

---

docs/lakehouse/catalog-overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalog-overview.md

Add docs for pr: https://github.com/apache/doris/pull/49658

[feat](bi) support default_init_catalog user property for external catalog

---

docs/ecosystem/bi/tableau.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/ecosystem/bi/tableau.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/ecosystem/bi/tableau.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/ecosystem/bi/tableau.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/ecosystem/bi/tableau.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/ecosystem/bi/tableau.md
versioned_docs/version-1.2/ecosystem/bi/tableau.md
versioned_docs/version-2.0/ecosystem/bi/tableau.md
versioned_docs/version-2.1/ecosystem/bi/tableau.md
versioned_docs/version-3.0/ecosystem/bi/tableau.md

[doc](bi)update the way to connect doris by tableau

---

docs/sql-manual/sql-functions/scalar-functions/string-functions/substring-index.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/string-functions/substring-index.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/substring-index.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/substring-index.md
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/substring-index.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/substring-index.md

because: https://github.com/apache/doris/pull/50149

Remove the description that the parameter does not support variables

---

docs/admin-manual/workload-management/kill-query.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/workload-management/kill-query.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/workload-management/kill-query.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/workload-management/kill-query.md
versioned_docs/version-2.1/admin-manual/workload-management/kill-query.md
versioned_docs/version-3.0/admin-manual/workload-management/kill-query.md

[fix](kill) opt kill query doc

---

docs/install/deploy-on-kubernetes/integrated-storage-compute/install-config-cluster.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/install/deploy-on-kubernetes/integrated-storage-compute/install-config-cluster.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/install/deploy-on-kubernetes/install-config-cluster.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/deploy-on-kubernetes/integrated-storage-compute/install-config-cluster.md
versioned_docs/version-2.1/install/deploy-on-kubernetes/install-config-cluster.md
versioned_docs/version-3.0/install/deploy-on-kubernetes/integrated-storage-compute/install-config-cluster.md

shard pv used doc

---

docs/lakehouse/file-analysis.md
docs/sql-manual/sql-functions/table-valued-functions/file.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/file-analysis.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/table-valued-functions/file.md
sidebars.json

doris pr: https://github.com/apache/doris/pull/50879

[Feature](tvf) Support file tvf

---

docs/sql-manual/sql-statements/data-modification/load-and-export/OUTFILE.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-statements/data-modification/load-and-export/OUTFILE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-reference/Data-Manipulation-Statements/OUTFILE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/OUTFILE.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/OUTFILE.md
versioned_docs/version-2.0/sql-manual/sql-reference/Data-Manipulation-Statements/OUTFILE.md
versioned_docs/version-2.1/sql-manual/sql-statements/data-modification/load-and-export/OUTFILE.md
versioned_docs/version-3.0/sql-manual/sql-statements/data-modification/load-and-export/OUTFILE.md

[doc] fix markdown table format error

---

docs/data-operate/import/complex-types/array.md
docs/data-operate/import/complex-types/map.md
docs/data-operate/import/complex-types/struct.md
docs/sql-manual/basic-element/sql-data-types/semi-structured/ARRAY.md
docs/sql-manual/basic-element/sql-data-types/semi-structured/MAP.md
docs/sql-manual/basic-element/sql-data-types/semi-structured/STRUCT.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/complex-types/array.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/complex-types/map.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/complex-types/struct.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/basic-element/sql-data-types/semi-structured/ARRAY.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/basic-element/sql-data-types/semi-structured/MAP.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/basic-element/sql-data-types/semi-structured/STRUCT.md

[fix](complex type) array map struct data type

---

docs/admin-manual/system-tables/information_schema/catalog_meta_cache_statistics.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/admin-manual/system-tables/information_schema/catalog_meta_cache_statistics.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/admin-manual/system-tables/information_schema/catalog_meta_cache_statistics.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/admin-manual/system-tables/information_schema/catalog_meta_cache_statistics.md
versioned_docs/version-2.1/admin-manual/system-tables/information_schema/catalog_meta_cache_statistics.md
versioned_docs/version-3.0/admin-manual/system-tables/information_schema/catalog_meta_cache_statistics.md

This PR adds practical usage examples for the `catalog_meta_cache_statistics` system table based on the Caffeine cache metrics implementation in ExternalMetaCacheMgr.

[doc][lakehouse]add some usage example for catalog_meta_cache_statistics

---

docs/lakehouse/catalog-overview.md
docs/lakehouse/catalogs/iceberg-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalog-overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/iceberg-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/catalog-overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/catalogs/iceberg-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/catalog-overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/catalogs/iceberg-catalog.md
versioned_docs/version-2.1/lakehouse/catalog-overview.md
versioned_docs/version-2.1/lakehouse/catalogs/iceberg-catalog.md
versioned_docs/version-3.0/lakehouse/catalog-overview.md
versioned_docs/version-3.0/lakehouse/catalogs/iceberg-catalog.md

bp: https://github.com/apache/doris/pull/52591

[docs] add more doc about iceberg table

---

docs/install/deploy-on-kubernetes/integrated-storage-compute/install-config-cluster.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/install/deploy-on-kubernetes/integrated-storage-compute/install-config-cluster.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/install/deploy-on-kubernetes/integrated-storage-compute/install-config-cluster.md
versioned_docs/version-3.0/install/deploy-on-kubernetes/integrated-storage-compute/install-config-cluster.md

[upgrade] [conf]docs 3.0 update conf use jdk17

---

docs/data-operate/import/handling-messy-data.md
docs/data-operate/import/import-way/stream-load-manual.md
docs/data-operate/update/update-of-unique-model.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/handling-messy-data.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/import/import-way/stream-load-manual.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data-operate/update/update-of-unique-model.md

[Doc](partial update) use a separate config to control the behavior of newly inserted rows in partial update

---

docs/sql-manual/sql-functions/scalar-functions/struct-functions/struct-element.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/struct-functions/struct-element.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/struct-functions/struct-element.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/struct-functions/struct-element.md
versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/struct-functions/struct-element.md
versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/struct-functions/struct-element.md

[Fix](function) Fix wrong punctuation marks in function struct_element docs

---

docs/lakehouse/catalogs/hudi-catalog.md
docs/lakehouse/catalogs/iceberg-catalog.md
docs/lakehouse/catalogs/paimon-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/hudi-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/iceberg-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/lakehouse/catalogs/paimon-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/catalogs/hudi-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/catalogs/iceberg-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/lakehouse/catalogs/paimon-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/catalogs/hudi-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/catalogs/iceberg-catalog.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/lakehouse/catalogs/paimon-catalog.md
versioned_docs/version-2.1/lakehouse/catalogs/hudi-catalog.md
versioned_docs/version-2.1/lakehouse/catalogs/iceberg-catalog.md
versioned_docs/version-2.1/lakehouse/catalogs/paimon-catalog.md
versioned_docs/version-3.0/lakehouse/catalogs/hudi-catalog.md
versioned_docs/version-3.0/lakehouse/catalogs/iceberg-catalog.md
versioned_docs/version-3.0/lakehouse/catalogs/paimon-catalog.md

1. fix hudi incr query description about https://github.com/apache/doris/pull/55003
2. replace `@brand` by `@branch`

[dcc](hudi/iceberg) fix hudi incr query description and iceberg branch query typo
